### ISSUE TITLE
Test dynamic and admin view

### ISSUE THREAD

**Issue by dkhan11** [jruizgit/rules#10]
Hi,

First, let me say that I really love your framework and how you build your architecture!
I'm trying to use the testdynamic.js and testdynamic.html test in order to understand how it works. Unfortunately, just out of the box, it gives endless errors on the client side while trying to register new rules(but it works). The post message doesn't work as well and the HTTP request failed with no clear error. I tried to debug it without success.
Also, I was trying to get one example running the admin.html and the D3 example. Both fail on the client side with errors. I tried both Chrome and Safari. I'm opening a http://localhost:5000/first/a/admin.html. The page is found but never loads, no matter what the rule is. 
Would love to get your help.

Thanks,
D.

**Comment by jruizgit** [comment]
Hi, thanks a lot for the feedback. I'm sorry you came across the old testdynamic sample. I should be done fixing it tomorrow. 

Unfortunately, as the project has evolved, I haven't been able to keep the rule visualization up to date, right now I don't have a good way of visualizing a forward chaining ruleset. I'm planning to remove the admin page feature from the project altogether. 

Thanks,

JR

**Comment by jruizgit** [comment]
OK, I have fixed the testdynamic sample and cleaned up the visuals. Please try http://localhost:5000/testdynamic.html. Once the page comes up, click save then click post. 

Please keep in mind JSON is only an intermediate format. By no means it is not intended to be a rule definition language.

Hope this help,

**Comment by tuxos** [comment]
Hi,
It might be that my comment is not related to the issue. But I could not run the python test successfully. I am getting the following error.

``` 
Traceback (most recent call last):
  File "testdynamic.py", line 49, in <module>
    main_app = Application(main_host)
  File "testdynamic.py", line 37, in __init__
    super(Application, self).__init__(host, [Rule('/testdynamic.html', endpoint=self._dynamic_request)])
TypeError: __init__() takes at least 4 arguments (3 given)
```

Thx

**Comment by dkhan11** [comment]
Thanks, it works! I very interesting implementation. I will spend a lot of time on this.

**Comment by jruizgit** [comment]
Hi, thanks much for verifying. @tuxos, I have opened a separate issue to keep track of the python problem.
