### ISSUE TITLE
Question on defining facts and flow structure

### ISSUE THREAD

**Issue by ksheurs** [jruizgit/rules#101]
Hi @jruizgit - thanks so much for your work on this! It's very well documented and the architecture seems easy to bring into an existing project.

I'm still new to and learning about rete, but this seems like a system we'll need to adopt. I've been able to get a number of your examples up and running, but I could use some help in understanding how to lay out different facts in our system. In particular, when there might be many different types of facts (vs just a single stream of transaction events, for example).

A simple example that aligns with my project is an Amazon warehouse. There are boxes to be shipped and places they need to be stored in the warehouse as they move through process.

- Boxes might have facts like dimensions, weight, fragile or not, temperature requirements, shipping date, etc.
- The warehouse stations would have facts like current capacity/usage, location, cold room or not, perhaps shipping date ranges for boxes within it, etc.

Could I have multiple fact types like this that are both evaluated in my rules? Example, if the current box being processed requires a cold room and the cold room has capacity, move it there next to boxes with the same shipping date.

Any clarification on this use-case and flow structure to be used would be a big help. Thank you again!

**Comment by ikus060** [comment]
To manage multiple kinds of fact, you need a fact property named "object" to check the object type and use it in your @when_any() condition. e.g.: @when_any(m.object = 'box')

As for your use case, I'm not so sure RETE is a fit for you. RETE is more useful to react on things. I would need more details about your use case. e.g.: Do you try to optimize the location ? Do you try to maximize the space, reduce the number of boxes to be moved ? If so, linear optimization might be a better fit for you.
Btw, I made the same mistake awhile back trying to use RETE for the wrong use cases. I've wasted 3 months on it trying to tweak it to solve my problem. While, once I knew about Linear Programming, it took me 2 weeks to get it working.

**Comment by ksheurs** [comment]
Thanks @ikus060 for the reply! Good to know about "object".

Interesting. I will look into linear optimization, but happy to explain more on my use case and why I was thinking RETE.

At this stage in our process, we aren't really looking to optimize. We're more so looking to make a set of decisions for the given boxes that we have on hand for the day. Eventually in the future, I think earlier steps in our process (that lead us into this stage) will be optimized. For example, the boxes that we deal with each day will be easier to make decisions on due to earlier optimizations. Some more facts:

- We have box types A, B, C
- Boxes can be in stages 1, 2, or 3 based on a date property
- If available, boxes should be moved to certain locations when advancing stage (we have limited # of locations)
- Box A's like being located next to other Box A's. If no spots next to A, B is fine, but not C.
- Boxes should ideally be next to other boxes with the same shipping date.
- Certain boxes are large and might take up 2 spots.

Any other input on this would be much appreciated. My thought re: RETE is a lot of these rules/decisions will be affecting others and the larger state of the process.

**Comment by ikus060** [comment]
If optimization is not your first goal, RETE might be a match for you...

For this use case: Box A's like being located next to other Box A's. If no spots next to A, B is fine, but not C.
When a new spot is available for a Box. What are you planing to do ? You want to dispatch someone to move a box to fill the spot ? You need to find the best box to fill the spot ?

How is the software interacting with the real world ? Whats are your actors ? Someone scanning the boxes, when, how, why ? Who/what is moving the box ?

**Comment by ksheurs** [comment]
Great questions @ikus060.

At the start of the process we'd have our set of boxes that need to go somewhere and we'd know which spots are currently open. My thought is we'd have these boxes/spots fully described as facts and then rules to best position them. I figured it would be less "when a new spot is available" and more just evaluating all the boxes and best filling them in the spots.

For now, yes - the output would be instructions or a task list for someone to move the boxes. They would then mark the action complete in a simple UI or scanner. Eventually the result of all of this could trigger automation.

**Comment by jruizgit** [comment]
Hi ksheurs and ikus060, thanks a lot for posting the questions and comments. Few more comments: 

* Yes, as ikus006 mentions, you can model different types of facts by using a property in your object: `@when_any(m.t ==  'box'`. In contrast with other rules engines, durable_rules  type system is JSON. That is, durable_rules is agnostic of the language specific types. 
* RETE helps when your system needs to remember a set of preconditions to infer an action. In RDBMS terms, think of RETE as a reverse query, which incrementally resolves a join as soon as enough data is available. 
* Rules are declarative, they define the 'what' (not the 'how') of your system. First intuition: model boxes and locations as facts. Use rules to define the relation between boxes and locations.

**Comment by ksheurs** [comment]
Thanks @jruizgit. Will give this a try today and tomorrow. I'll report back if any questions come up before closing.

**Comment by ksheurs** [comment]
In a ruby example, is there a way to enable better logging or exceptions? As I'm testing things, it be good to see some output of processing and if the server is in a loop, etc. I'm currently running scripts solely via `ruby myscript.rb` (not the API).

Separately, this may be a confusing question, but in trying to understand how these rules are executed... is there a concept of completion of execution (or do things just continually run until all rules are no longer satisfied). In statechart's I see usage of `delete` which maybe seems related, but curious for other flows, as well.

**Comment by ksheurs** [comment]
Per the question above, I'm trying to capture the completed/finished state like so (doesn't seem to exactly be working, though):

```ruby
when_all c.box = (m.type == "box"), all(+m.position_id) do
  puts "Complete!"
end
```

**Comment by jruizgit** [comment]
Hi ksheurs, yes you can log exceptions by looking at the exception property is the state context. For example:

```ruby
require "durable"

Durable.ruleset :flow do
  when_all m.action == "start" do
    raise "Unhandled Exception!"
  end
  
  # when the exception property exists
  when_all +s.exception do
    puts "#{s.exception}"
    s.exception = nil
  end

  when_start do
    post :flow, { :action => "start" }
  end
end

Durable.run_all
```

**Comment by jruizgit** [comment]
Regarding your second question, rules continue running until no rules are satisfied. You can define the execution lifecycle by using a state property in an object. You can also use a state_chart. 

The rule you pasted above, if type and position are part of the same object, you might want to write it like this:
```ruby
when_all c.box = ((m.type == "box") & (+m.position_id)) do
  puts "Complete!"
end
```
If you are trying to reason about two different facts, you might want to write the rule like this:
```ruby
when_all (c.box = (m.type == "box"), +m.position_id) do
  puts "Complete!"
end
```

**Comment by ksheurs** [comment]
Thanks Jesus - both responses are very helpful! Is it possible handling of `nil` is not working as expected in the Ruby implementation? The below `+position_id` seems to fire for `nil` values:

```ruby
Durable.ruleset :nilcheck do
  when_all c.box = ((m.type == "box") & (+m.position_id)) do
    puts "Fires for nil?"
  end

  when_start do
    post :nilcheck, { type: "box", position_id: nil }
    post :nilcheck, { type: "box", position_id: nil }
  end
end

Durable.run_all
```

**Comment by jruizgit** [comment]
The `+` operator test for the existence of a field. A field with `nil` value does exist. You might need to do something like this:

```ruby
Durable.ruleset :nilcheck do
  when_all c.box = ((m.type == "box") & ((+m.position_id) & (m.position_id != nil))) do
    puts "Shouldn't fire for nil"
  end

  when_start do
    post :nilcheck, { type: "box", position_id: nil }
    post :nilcheck, { type: "box", position_id: nil }
  end
end
```

**Comment by ksheurs** [comment]
Got it - thanks! I'm sure I'll have some more questions, but I'll close this issue out. Thank you again.
