### ISSUE TITLE
Multiple facts / permutation

### ISSUE THREAD

**Issue by ksheurs** [jruizgit/rules#103]
I have a rule that is trying to get 2 related facts. It seems for every resulting pair, I get facts matching themselves (f1->f1, f2->f2), the facts i want (f1->f2), and then the permutation (f2->f1).

I've reduced the self matching by ensuring fact1 identifier != fact2 identifier, but is there a recommended approach to avoiding the 3rd permutation case.

**Comment by ksheurs** [comment]
One idea is using `cap(1)` and then using de-duping logic in the consequent around the `for f in m` loop, but I'm not sure this is a good approach. It seems better to reserve this kind of logic for the antecedent.

**Comment by jruizgit** [comment]
Hi, thanks for asking the question. Yes, it is best to express the relation in the antecedent. The engine generates an id for every fact, you can write a rule that includes this clause: `f1.id != f2.id`. You don't need to generate the id.

**Comment by ksheurs** [comment]
Thanks Jesus. Will `f1.id != f2.id` only avoid the f1/f1 and f2/f2 cases? I think I'd still get the f1/f2 and f2/f1 results. If helpful, I can put together a small example.

**Comment by ksheurs** [comment]
```ruby
# output:
# f2 / f1
# f1 / f2

# desired output:
# f1 / f2

Durable.ruleset :duplicates do
  when_all c.f1 = (m.t == "fact"),
           c.f2 = (m.t == "fact") & (m.id != f1.id) do

    puts "#{f1.value} / #{f2.value}"
  end

  when_start do
    assert :duplicates, { :t => "fact", :value => "f1" }
    assert :duplicates, { :t => "fact", :value => "f2" }
  end
end

Durable.run_all
```

**Comment by ksheurs** [comment]
Was able to resolve this with the use of `none()`.

**Comment by jruizgit** [comment]
One thing I forgot to ask: I assume events are not suitable for your scenario (post instead of assert). Events are retracted before dispatch and can only be observed once:

```ruby
Durable.ruleset :duplicates do
  when_all c.f1 = (m.t == "box"),
           c.f2 = (m.t == "box") & (m.id != f1.id) do

    puts "#{f1.value} / #{f2.value}"
  end

  when_start do
    post :duplicates, { :t => "box", :value => "f1" }
    post :duplicates, { :t => "box", :value => "f2" }
  end
end


Durable.run_all
```
