### ISSUE TITLE
Standing up Durable as it's own service

### ISSUE THREAD

**Issue by ksheurs** [jruizgit/rules#105]
What is the best method for standing Durable up as it's own server / service? My testing to date has been through `when_start`-based assertions, but I'd like to run the rules as a server and begin sending assertions over the API. Testing the results of my implementation has just been through `puts` logging, but how should I be thinking about getting a single response or a series of responses from this server?

We're on AWS and the service that's sending API calls to Durable will be Rails or Elixir. Ideally results are made available to this service, as well.

Lastly, I currently have many facts I assert within `when_start`. Is it possible to batch post these over the API? The flow of my statechart is dependent on all the facts that are initially asserted.

**Comment by jruizgit** [comment]
Hi, yes durable_rules as a service in AWS (EC2) works just fine. You would need to assert and retract facts via http from your Rails or Elixir service. 

Yes, you can assert a batch of facts in the when_start method:

```ruby
    def assert_facts(ruleset_name, *facts)
      ...
    end
```

**Comment by ksheurs** [comment]
Thanks @jruizgit. If I need to assert facts via HTTP, I couldn't use `when_start` then, right?

Maybe I can use events to control the flow? 1) Post event to hold 2) Post all facts 3) Post event to begin?

**Comment by ksheurs** [comment]
Went with my first state waiting for a posted "start" event. Seems to work well! Closing.
