### ISSUE TITLE
Reduce the number of warning messages

### ISSUE THREAD

**Issue by chinhls** [jruizgit/rules#107]
Hi @jruizgit .
1. I'm trying the example code as below to warn when pressure greater than 100. I'm set count to 3 but it's still many messages so i want set the warning messages by time. After three times continuously and in a half of an hour it warn one time. How can i do this? 

```
var d = require('durable');

d.ruleset('water', function () {
    whenAll: m.pressure > 100
    count:3
    run: console.log('warning message');
});

d.runAll();
```

2. How can i enable/disable a rule at run time?
Thanks

**Comment by jruizgit** [comment]
Hi, thanks for posting the question. You might find these samples useful (the second one might be what you need):

https://github.com/jruizgit/rules/blob/master/docs/js/reference.md#timers

Please let me know what you think.

**Comment by chinhls** [comment]
Hi thanks for your repsponse. I try this case and it work for me!

```var d = require('durable');
d.ruleset('water', function () {
    whenAll: m.state == 'start'
    run: {
        console.log('time out');
        startTimer('MyTimer', 1, true);
    }
    whenAll: {
        m.pressure > 100
        timeout('MyTimer')
    }
    cap: 100
    run: {
        var d = new Date();
        var timestr = d.getHours() + ':' + d.getMinutes() + ':' + d.getSeconds();
        console.log(m.length + ' events ' + timestr);
        resetTimer('MyTimer');
        startTimer('MyTimer', 1800, true);
    }
    whenStart: {
        post('timer', { state: 'start' });
    }
});
d.runAll();
```


But I can't see the timer setting in rule's definition via Rest API: 
_http://localhost:5000/water/definition_
Because i'm using JSON object to register a new rule like this: 

``` json
{
	"water": {
		"start": {
			"all": [{
				"m": {
					"$gt": {
						"value": 10
					}
				}
			}],
			"run": "hook"
		}
	}
}
```

How do I define time setting here?

**Comment by jruizgit** [comment]
Hi, thanks for asking the question. `startTimer` just as `post` and `assert` are not declarative. That is, they can only be defined within the body of an action. 

In your example above, I assume the name "hook" is resolved into an action. Depending on how you resolve the action, you could declare the timeout as part of the action name "hook:1".

**Comment by chinhls** [comment]
Finaly i find out the way to do this. Thank you so much
