### ISSUE TITLE
Question: Test events in python

### ISSUE THREAD

**Issue by slitayem** [jruizgit/rules#11]
Hi,

According to the events example in [testpy/testevents.py](https://github.com/jruizgit/rules/blob/master/testpy/testevents.py), the events can also be asserted with `assert_event`. And the ruleset can be defined as a dictionary.

My question is how can I define the ruleset action(s) method(s). In the example, the action is executed with `complete_action` call https://github.com/jruizgit/rules/blob/master/testpy/testevents.py#L59
but `result[2]` is a long int value. It is not clear what is the action method in that case. And where should it be defined.

Thanks.

**Comment by jruizgit** [comment]
Hi, thanks for posting the question. testevents.py and its .rb and .js equivalents are intended for testing the raw C library. The C library only evaluates a rule and can result in queuing the parameter closure to pass to an action. The higher level language library owns executing the action. In order to correlate the action, result[1] is a dictionary with a single key. The key name corresponds to the name of the rule which lead to queuing such a closure. It is up to the language implementation to resolve the rule name to a function (please see how engine.py does it). 

```python
'ship': {
        'all': [ 
            {'m': {'$and': [
                {'country': 'US'},
                {'seller': 'bookstore'},
                {'currency': 'US'},
                {'$lte': {'amount': 1000}},
            ]}}
        ]
    }
```

Asserting a positive event on the rule above, will produce in result[1] (see 'ship' and 'ship'):

`{u'ship': {u'm': {u'sid': u'first', u'id': 1, u'name': u'John Smith', u'address': u'1111 NE 22, Seattle, Wa'}}}`

**Comment by tuxos** [comment]
Hi Jesus,

Thanks for the quick answer and for the very interesting framework. 
What are the values in result[2] and result[1].

```
rules.complete_action(handle, result[2], result[0])
``` 
Also could you please point me to the method resolving the rule name to a function.
Thanks.
Saloua

**Comment by jruizgit** [comment]
Hi Saloua, answering your questions:

**Resolving Actions**
In engine.py Ruleset init, you will notice how the 'run' object in each rule dictionary is stored away in the _actions variable.

```python
def __init__(self, name, host, ruleset_definition, state_cache_size):
    self._actions = {}
    for rule_name, rule in ruleset_definition.iteritems():
        action = rule['run']
        del rule['run']
        #other details removed for clarity
        elif (hasattr(action, '__call__')):
            self._actions[rule_name] = Promise(action)
``` 
The Ruleset dispatch method resolves the action based on the closure returned by start_action:
``` python
    result = rules.start_action(self._handle)
    if result: 
        state = json.loads(result[0])
        result_container = {'message': json.loads(result[1])}
        action_handle = result[2]
        action_binding = result[3]
        #other details removed for clarity
        for action_name, message in result_container['message'].iteritems():
            break
        #other details removed for clarity 
        self._actions[action_name].run(c, action_callback)
```
**About result[2] and result[3]**  
These are just handles used for correlating the state and connection to be used when completing or abandoning the action.  
**A note on result[0]**  
The first result from start_action is the rule context. You can write rules against the rule context and you can change the rule context during action execution. Starting an action means "leasing" a rule context. No other process will be able to see the rule context while it is leased to a given process. This allows for distributing action execution among compute hosts in a "competing consumers" fashion. Also please note you can bind the same ruleset to different redis servers. Rule context will be sharded among the redis servers based on 'sid'. This allows for datastore scale.  

Hope this helps,

**Comment by jruizgit** [comment]
I'm closing this issue. Please let me know if you have any other questions.

**Comment by slitayem** [comment]
@jruizgit 
Thanks that was helpful. Sorry I could not comment last days.
Saloua
