### ISSUE TITLE
Could not create ruleset

### ISSUE THREAD

**Issue by ksheurs** [jruizgit/rules#112]
I notice if I have 2 rules that are very similar (but perhaps an additional logical operator/check or two), I receive the following:

`Could not create ruleset, error code: 8 (Exception)`

Is there a specific case I should be avoiding here? It'd be nice to have several rules that are similar, but are checking for different fact variations.

**Comment by jruizgit** [comment]
Hi, thanks for asking the question. Would you mind pasting your use case? 

Most likely there is a bug in the Ruleset parsing code. This is the error code:

```c
#define ERR_RULE_BETA_LIMIT_EXCEEDED 8
```

**Comment by ksheurs** [comment]
Ah ok. Yes at is turns out, even if I define the most simplest of rule (vs one that is very similar to another), I see this same exception. I wonder if there is indeed a limit I'm hitting.

You can download the use case here: https://gist.github.com/ksheurs/a642fb97aa9a0a6a207974f1303217e1.

Run `ruby app.rb` to reproduce the error. Notice Line 166. If you remove that rule, it will properly start up.

I'm hitting a blocker at this point since I can't seem to add any more rules. Any help would be much appreciated!

**Comment by jruizgit** [comment]
Hi, I have uploaded a fix for this issue. Please use versions: ruby 0.34.40, python 0.33.118, node.js 0.36.77.

**Comment by ksheurs** [comment]
Excellent - thank you!
