### ISSUE TITLE
Floating-Point Condition

### ISSUE THREAD

**Issue by chinhls** [jruizgit/rules#115]
Hi @jruizgit 
I create an ruleset as below: 
```
var d = require('durable');
d.ruleset('a1', function () {
    whenAll: m.amount > 1.0 && m.amount < 5.0
    run: console.log('a1 approved ' + m.subject + ' ' + m.amount)

    whenStart: {
        post('a1', { id: 1, sid: 1, subject: 'go', amount: 3.3 });
    }
});
d.runAll();
```
But it seems not working.It is possible to compare float value?
Thanks !

**Comment by jruizgit** [comment]
Hi, thanks for reporting this issue. Yes, comparing floating point should be possible. Let me debug your scenario and I will report back in a couple of days.

**Comment by jruizgit** [comment]
In the case above 1.0 and 5.0 got marshaled to the C extension as integers. There was a bug when comparing a message with a double and a rule with integer properties.

I have fixed the bug and uploaded a new npm version. Please use durable@0.36.78.

**Comment by chinhls** [comment]
Excellent work! I was testing and it worked. Thank you for your quick fix.
