### ISSUE TITLE
testdynamic doesn't work in Python 

### ISSUE THREAD

**Issue by jruizgit** [jruizgit/rules#12]
Following up on issue reported and fixed for js...

**Comment by tuxos** [comment]
Thanks for opening the issue according to my comment in #10.

**Comment by jruizgit** [comment]
I have pushed the fix for testdynamic. From the rules directory try: python testpy/testdynamic.html. In your browser go to http://localhost:5000/testdynamic.html. Click 'save' first, then click 'post', change the 'id' to 2 and click 'post' again. You should see how the states progress in the right panel.

**Comment by tuxos** [comment]
Thx for the answer but I see that in the last commit, the file `testdynamic.html` was removed.
And when I run `python testpy/testdynamic.py` then I go to `http://localhost:5000/testdynamic.html` I have the following error

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 184, in execute
    write(data)
  File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 142, in write
    assert headers_set, 'write() before start_response'
AssertionError: write() before start_response
```

**Comment by jruizgit** [comment]
OK, I have pushed the admin.html, durableVisual.js and testdynamic.html files required. Please let me know if it doesn't work.

Thanks,

JR

**Comment by jruizgit** [comment]
Hi, I'm going to close this issue. Please feel free to reopen if you find any other problems.

**Comment by slitayem** [comment]
Hi Jesus,

Actually with the latest changes I am getting an error message window when I clic on save.

![screen shot 2016-04-25 at 09 51 10](https://cloud.githubusercontent.com/assets/3774492/14777166/b147c3d0-0acb-11e6-92b1-46bf5f42b4a6.png)

Here is the console error message.
```
XMLHttpRequest cannot load http://localhost:5000/first. Response to preflight request doesn't pass 
access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. 
Origin 'http://127.0.0.1:5000' is therefore not allowed access.
```

Thanks again for the interesting framework and also for the quick answers.
Best.
