### ISSUE TITLE
Completion of evaluation, Global accessible context

### ISSUE THREAD

**Issue by melvinkcx** [jruizgit/rules#122]
Hi, I'm trying to move from pyknow to your framework. During my course of moving to durable_rules, I've met a few issues. 

1. Is there anyway to know when all evaluations are performed? Or is there a callback when all evaluations are done?

2. Is there any object or context that is accessible from all action definition (def block in ruleset) and the Host object? 

Thanks in advance. 
Melvin

**Comment by jruizgit** [comment]
Hi, thanks for posting the questions. 

For #1, there is no easy way of knowing when all evaluations have been performed, actions are run asynchronously. When scaling out, actions can be run in any number of hosts.   

For #2, yes you can use the patch_state function in the host object. When an action is executed the state is passed in the `s` property. You can also write rules against such state. 

```python
with ruleset('timer'):
    # will trigger when MyTimer expires
    @when_any(all(s.count == 0),
              all(s.count < 5, timeout('MyTimer')))
    def pulse(c):
        c.s.count += 1
```

**Comment by melvinkcx** [comment]
Thanks for your prompt response. Regarding the first question, my current possible solution is to assume evaluation is done after a certain period of time. Do you have any suggestion to implement similar mechanism?
