### ISSUE TITLE
Rule definition

### ISSUE THREAD

**Issue by melvinkcx** [jruizgit/rules#123]
Hi, I realized there is a register_rulesets() in the Host object. What is the format of defining a rule as the parameter in register_rulesets()? Says that I would like to allow the definition of rules dynamically using JSON.

Thanks, 
Melvin

**Comment by jruizgit** [comment]
Yes, you can define rulesets dynamically. I have not documented the format as I was changing it often. At this point it is stable. I will document it within the next few weeks. This is an example on how to use it:

https://github.com/jruizgit/rules/blob/master/testpy/testdynamic.py

**Comment by 2433kevin** [comment]
Hi jruizgit,

Is there any example on how I can use this dynamic ruleset definition.

**Comment by Spiruel** [comment]
I too am interested in an example of dynamic ruleset definition from JSON. Please do let me know if something exists!
