### ISSUE TITLE
Regular expression for email not functioning

### ISSUE THREAD

**Issue by prade** [jruizgit/rules#131]
1 from durable.lang import *                                                                                                                        
  2                                                                                  
  3 with ruleset('match'):                                                           
  4     @when_all(m.url.matches('^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$')) 
  5     def approved(c):                                                             
  6         print ('match url ->{0}'.format(c.m.url))                                
  7                                                                                  
  8     @when_start                                                                  
  9     def start(host):                                                             
 10         host.post('match', { 'url': 'a@ag.com' })                                
 11         host.post('match', { 'url': 'a' })                                       
 12         host.post('match', { 'url': 'fdasf@g.com' })                             
 13         host.post('match', { 'url': '//rules'})                                  
 14         host.post('match', { 'url': 'x@h.com' })                                 
 15                                                                                  
 16 run_all() 

This condition doesn't get validated.

**Comment by jruizgit** [comment]
Hi, thanks for reporting this issue. Let me debug the scenario. I will report back with my findings.

**Comment by prade** [comment]
Thanks for the response, I have taken a note of the way to use durable pattern matching.
