### ISSUE TITLE
Dynamic JSON object rules documentation

### ISSUE THREAD

**Issue by iddolazar** [jruizgit/rules#134]
Hi,
I am trying to work dynamically saving my rules to db.
I can see in other issues the documentation does not exist and that you refer to the testevents.js file.

I tried using it but got stuck with 2 things:
1. I couldn't find any sample using Timers based rule. Is it possible with JSON object? can you share the syntax of the JSON for "whenAny" and "whenAll"?
2. I am not able implementing $not rule. I have a rule that works just fine for positive outcome:

```
    var val = 'a1|a2|a3';
    var rules = {
        check_data: {
            check_data: {
                all: [{first: {$mt: {data: val}}}],
                "run": function (data) {
                    console.log(data.first);
                    // fire_event(data);
                }
            }
        }
    };

    var d = require('durable/libjs/durableEngine');
    var h = d.host();
    h.registerRulesets(null, rules);
    var a = d.application(h);
    a.run();

    var out = h.post('check_data',{"data":"a1"});
```

tring to change the rule to:

`      all: [{first$not: {$mt: {data: val}}}]
`
When sending "a1" gives an outcome of 0 (surprisingly) without triggering the fire event - as supposed (i guess)
When sending "a5" [not within the val param regex] gives an outcome of 201 (surprisingly) without triggering the fire event - why is that? What am I doing wrong?

p.s
As you can see in the code I use 
`        check_data: {
            check_data: {
`
to overcome an issue I found that calling registerRulesets with array set the name of the ruleset to the index of the item inside the array ["0","1",....], NOT the name on the key of the item....

Thanks.
Iddo

**Comment by jruizgit** [comment]
Hi Iddo, thanks for posting the question. durable_rules uses JSON as the intermediate format for all rules. That is, all rules can be expressed in JSON. I haven't documented the JSON format, but one thing you can do is un-comment line 1861 in durable.js file (in your node_modules directory). Write your rules using the node.js format, the JSON equivalent will be dumped to the console. 

The case of timers:
```javascript
ruleset('timer', function() {
    whenAny: {
        whenAll: s.count == 0
        // will trigger when MyTimer expires
        whenAll: {
            s.count < 5 
            timeout('MyTimer')
        }
    }
    run: {
        s.count += 1;
        // MyTimer will expire in 5 seconds
        startTimer('MyTimer', 5);
        console.log('Pusle ->' + new Date());
    }

    whenAll: {
        m.cancel == true
    }
    run: {
        cancelTimer('MyTimer');
        console.log('canceled timer');
    }

    whenStart: {
        patchState('timer', { count: 0 }); 
    }
});
```  

The JSON format:  
```javascript
{
  "r_0": {
    "any": [
      {
        "m_0$all": [
          {
            "m_0.m": {
              "$and": [
                {
                  "count": 0
                },
                {
                  "$s": 1
                }
              ]
            }
          }
        ]
      },
      {
        "m_1$all": [
          {
            "m_1.m_0": {
              "$and": [
                {
                  "$lt": {
                    "count": 5
                  }
                },
                {
                  "$s": 1
                }
              ]
            }
          },
          {
            "m_1.m_1": {
              "$t": "MyTimer"
            }
          }
        ]
      }
    ]
  },
  "r_1": {
    "all": [
      {
        "m": {
          "cancel": true
        }
      }
    ]
  }
}
```

The $not operator (none in node.js), means absence of data. In the case above I think you were expecting the semantics to be 'did not match', but that is not exactly how it works. This example is a better illustration on how the operator works (the rule will trigger only if there is no 'balance' event):

```javascript
d.ruleset('risk2', function() {
    whenAll: {
        first = m.t == 'deposit'
        none(m.t == 'balance')
        third = m.t == 'withrawal'
        fourth = m.t == 'chargeback'
    }
    run: console.log('fraud detected ' + first.t + ' ' + third.t + ' ' + fourth.t);

    whenStart: {
        post('risk2', {t: 'deposit'});
        post('risk2', {t: 'withrawal'});
        post('risk2', {t: 'chargeback'});
    }
});
```

The 'does not match' operator for pattern matching has not been implemented yet.

**Comment by jruizgit** [comment]
One more note: testdynamic.js shows the cleanest way for storing rules in a db. You can override the loadRuleset and saveRuleset methods on the host object as follows:

```javascript
var redis = require('redis');
var d = require('durableEngine');

var host = d.host();
var app = d.application(host);
var db = redis.createClient();

host.loadRuleset = function(rulesetName, complete) {
    db.hget('rulesets', rulesetName, function(err, result) {
        if (err) {
            complete(err);
        } else {
            complete(null, JSON.parse(result));
        }
    });
};

host.saveRuleset = function(rulesetName, rulesetDefinition, complete) {
    db.hset('rulesets', rulesetName, JSON.stringify(rulesetDefinition), complete);
};

app.run();
```
