### ISSUE TITLE
Redis 4.0.6 Issue?

### ISSUE THREAD

**Issue by iddolazar** [jruizgit/rules#135]
I am using the latest Redis version 4.0.6 and get an error:

> ERR Error running script (call to f_445a715b8b2cc8394ed6f020cbaac190a5468109): @user_script:125: @user_script: 125: Lua redis() command arguments must be strings or integers 

I see that in the past [https://github.com/jruizgit/rules/issues/51] you said that this error is because of incompatibility issue with redis.

Is it the same now?
should i use only a specific version of redis that is compatible? if so... what is it?

Thanks!

UPDATE:
not sure why but I got the error because I was posting a fact with a property of type object where i stores my application's rule_id - for example:
{ **rule: {id: xxxx}**, value: 5, value2: 10 }
after changing the fact to:
{ **rule_id: xxxx**, value: 5, value2: 10 }
the issue was resolved

**Comment by jruizgit** [comment]
Hi, thanks for reporting this issue. There was a bug when posting events or asserting facts with a nested object with a property named "id". I have pushed a fix and uploaded a new version to npm (0.36.81 for node.js).
