### ISSUE TITLE
Possible to increase BETA_LIST_LENGTH limit?

### ISSUE THREAD

**Issue by ksheurs** [jruizgit/rules#140]
I'm starting to hit the `BETA_LIST_LENGTH` of 64. Is this a hard limit or is it possible to increase this?

```shell
/usr/local/lib/ruby/gems/2.4.0/gems/durable_rules-0.34.44/librb/engine.rb:438:in `create_ruleset': Could not create ruleset, error code: 8 (Exception)
	from /usr/local/lib/ruby/gems/2.4.0/gems/durable_rules-0.34.44/librb/engine.rb:438:in `initialize'
	from /usr/local/lib/ruby/gems/2.4.0/gems/durable_rules-0.34.44/librb/engine.rb:761:in `initialize'
	from /usr/local/lib/ruby/gems/2.4.0/gems/durable_rules-0.34.44/librb/engine.rb:555:in `new'
	from /usr/local/lib/ruby/gems/2.4.0/gems/durable_rules-0.34.44/librb/engine.rb:555:in `block in create_rulesets'
	from /usr/local/lib/ruby/gems/2.4.0/gems/durable_rules-0.34.44/librb/engine.rb:550:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/durable_rules-0.34.44/librb/engine.rb:550:in `create_rulesets'
	from /usr/local/lib/ruby/gems/2.4.0/gems/durable_rules-0.34.44/librb/engine.rb:1205:in `register_rulesets'
	from /usr/local/lib/ruby/gems/2.4.0/gems/durable_rules-0.34.44/librb/engine.rb:1111:in `initialize'
	from /usr/local/lib/ruby/gems/2.4.0/gems/durable_rules-0.34.44/librb/durable.rb:13:in `new'
	from /usr/local/lib/ruby/gems/2.4.0/gems/durable_rules-0.34.44/librb/durable.rb:13:in `create_host'
	from /usr/local/lib/ruby/gems/2.4.0/gems/durable_rules-0.34.44/librb/durable.rb:22:in `run_all'
```

**Comment by jruizgit** [comment]
Hi, thanks for asking the question. Yes, it is possible to increase the size. Because I defined it as a constant, it will affect the memory footprint of smaller rulesets. I could make it configurable, although the setting might be difficult to reason about. Please give me a couple of days to measure the potential impact of the change.

Out of curiosity, what kind of ruleset is hitting this limit? 64 beta nodes seems a little extreme.

**Comment by ksheurs** [comment]
Thank you @jruizgit. Yea increasing that limit for the interim can help us, but I think generally we are starting to need a different tool for the job (we're probably not using the rules engine in the way it's most ideal for). We have a pretty complex matching problem based on various preferences and mixing of these preferences. It's becoming hard to represent all of this in single prioritized list of operations.

If you're still curious to learn more, happy to discuss elsewhere!

**Comment by ksheurs** [comment]
Hi @jruizgit, if I was to fork and increase that value myself, are there any specific steps I need to take re: building/compiling? Thanks.

**Comment by jruizgit** [comment]
Hi, I have increased the beta list limit and updated the Ruby, python and node.js versions. I'm definitely interested in learning more about your scenario. Please feel free to shoot me an email.

**Comment by ksheurs** [comment]
Great thanks, Jesus! Will shoot you an email.
