### ISSUE TITLE
Is this library similar to Django-Viewflows?

### ISSUE THREAD

**Issue by prafulbagai** [jruizgit/rules#141]

**Comment by jruizgit** [comment]
Hi, thanks for posting the question. I took a quick look at Viewflow (I had not seen it before). Yes, durable_rules is similar to Viewflow. Both provide durable continuations, but they have different purposes. Viewflow is a workflow engine, durable_rules is a real time event processing engine. Contrasting both libraries:

1. Viewflow is very nicely integrated with the django MVC model, durable_rules is not.
2. Viewflow's programming model relies on a cascading API, durable_rules programming model is based on annotations.
3. Viewflow executes all branch expressions in the Web tier, durable_rules in the Web tier and the redis backend.
4. durable_rules relies on a forward inference engine for making decisions. This allows you to handle complex event patterns. Viewflow is a workflow engine with full support for BPMN.
5. Viewflow's type system is Python's, developers are required to define a data model. durable_rules type system is JSON, developers are not required to define a data model.

**Comment by prafulbagai** [comment]
Thanks @jruizgit for the response. It was good to know the comparisons between the two. I've created another issue to better understand an API related use-case.

Closing this thread.
