### ISSUE TITLE
Qn: Loading rules from external JSON file in NodeJS

### ISSUE THREAD

**Issue by aravindnc-olt** [jruizgit/rules#143]
Is there any option to load the rules from a JSON file. ?

**Comment by jruizgit** [comment]
Hi, thank you for posting the question. Yes, there is an option from JSON files in node.js. It is an advanced scenario, there are two things to consider:

1. Actions cannot be expressed in JSON, so you need to provide a way to resolve action names
2. If you are scaling out several rules servers, you need to store the rules in a repository

The following example shows how that is accomplished:

https://github.com/jruizgit/rules/blob/master/testjs/testdynamic.js

Does this help?

**Comment by aravindnc-olt** [comment]
Thank you very much for the response.

Let me tell you about a sample scenario,

We are building a sample transaction system for multiple clients, so each client will have their own rules for approving and denying a transaction. 

Like, say if the amount is between 0$ and 1000$ they will approve the transaction and if the amount is more than 1000$ they will deny it. And for each client the limit varies.

So is it possible to implement similar kind of scenario? We are planning to create a wrapper in NodeJS and communicate with the durables engine. External communications will be via REST API. 

So we will get the request params like amount, clientId etc via API and we need to process it using durables engine and send back the response.

Waiting for your thoughts on this.

**Comment by jruizgit** [comment]
Hi, thanks for describing your scenario. durable_rules is useful if you have complex rules which require remembering state. For example, in the case you describe: if a transaction has two states authorize and settle, and the criteria to settle depends on the outcome of authorize. For stateless comparison of JSON values, durable_rules might be an overkill. 

Yes, you can host durable_rules in node.js. You can route the request from your API to your ruleset or you can have durable_rules in a separate tier.

**Comment by aravindnc-olt** [comment]
I'm closing this for now and will get back if I need any help from your side.
Thanks a lot.
