### ISSUE TITLE
Creating a rule via. API

### ISSUE THREAD

**Issue by aravindnc-olt** [jruizgit/rules#146]
I'm trying to setup a standalone server with rules engine which I can add/delete/execute rules via REST API.

Below is the problem,
I would like to create a rule using API leveraging **/{rule-name}/definition** endpoint. 

RequestBody: 
`{`
`    "start": {`
`        "trigger": {`
`            "all":[{`
`                "m": {"$lt":{"amount":1000}}`
`            }],`
`            "to": "step2",`
`            "run": "amount less than 1000"`
`        }`
`    },`
`    "step1": {`
`        "trigger": {`
`            "all":[{`
`                "m": {"$gt":{"amount":1000}}`
`            }],`
`            "to": "step3",`
`            "run": "amount greater than 1000"`
`        }`
`    },`
`    "step2":{},`
`    "step3":{}`
`}`

Everything is working fine, but my problem is I would like to get a custom value/data as API response for Step 2 and Step 3. So can you tell me how to do so ? I've checked testDynamic.js and it didn't help.

Thanks in Advance.

**Comment by jruizgit** [comment]
Hi, thanks for posting the question. Do you want to get the outcome based on the state machine state? How is your client interacting with the API? Is it posting and event and retrieving state?

**Comment by aravindnc-olt** [comment]
Thanks for the response, I've got the state from /event/sid API. So I'm closing this.
