### ISSUE TITLE
Handling multiple redis instances

### ISSUE THREAD

**Issue by aravindnc** [jruizgit/rules#147]
@jruizgit Suppose I have a large system of rules and I have multiple Redis instances. So my question is that how can I manage the SID? So is it possible to use a load balancer in between or any other methods?

Example:
What if the create event API call redis-server-1 initially and call redis-server-2 for checking the state? 

Thanks in Advance.

**Comment by jruizgit** [comment]
Hi, thanks for posting the question. In the run_all function you can include several redis instances (the function takes an array). 

```python
run_all([{'host': 'host_name', 'port': port, 'password': 'password'}])
```

The rules engine maintains a table relating SID to redis instances. It assigns SIDs to redis instances in a round-robin fashion. I haven't developed this fully. That is, there is no mechanism for repartitioning and there SID->redis instance table is kept in one instance (single point of failure).

**Comment by aravindnc-olt** [comment]
@jruizgit Just to make it clear, so if there are multiple redis instances, then as you said the SID's will be assigned to different redis instances, and the SID-redis mapping table will be available only in a single redis instance. And that is why you call it as single point of failure right ?

**Comment by jruizgit** [comment]
Yes, that is correct: if the redis instance with the SID-redis mapping goes down, durable_rules won't be able to find the instances anymore. The way around that: you can cluster each redis instance separately.

Alternatively I was thinking of implementing a consistent hashing algorithm for mapping SIDs to redis instances. Plus adding the API to move SID state and re-partition when adding more redis instances.

**Comment by aravindnc** [comment]
@jruizgit Understood. Thank you. 
Closing this.
