### ISSUE TITLE
Accessing host through npm package

### ISSUE THREAD

**Issue by enriched** [jruizgit/rules#15]
What is the best way to get at the host object when using the npm package?  I notice that when using run I could grab it if I give it a start callback, is that the best way to do it, or is there another way while still using the runAll method?

**Comment by enriched** [comment]
Or I suppose that I can grab the engine using require('durable/libjs/durableEngine') and create a host from the object that comes out of that.  But will that work, or do I need to get one that has been initialized with all of the rules?

**Comment by jruizgit** [comment]
Hi Rich, thank you for asking. You will need to pass the rulesets is you decide to use the host in durableEngine. What scenario do you have in mind? 

Thanks,

JR

**Comment by enriched** [comment]
I am working on using durable within a service running on a docker container.  And I am planning on using it to manage strategies for user communication.  The service that I am putting it in already has Thrift and AMQP for communication with other services, and I think that I want to shield the logic for inserting events into the inference engine within the service.

I am also writing all of this in typescript so I am doing some work on typings and a fluent builder (typescript doesn't like when you use 'with').  If you want any of that stuff let me know and I can pull request it.

**Comment by enriched** [comment]
Also, along the lines of getting rulesets, can I pull those out and store them?

**Comment by jruizgit** [comment]
Hi Rich, thanks much for providing the context. Please take a look at the test testjs/testDynamic.js. It might have some of the things you are looking for. 

I'm planning to push a change to cleanup Host creation so it is easier to address scenarios that don't expose an http API. 

I'm happy to review pull request. I curious to learn what you have done with typescript.

Thanks,

**Comment by enriched** [comment]
Sounds great!  Look forward to your changes and I'll make a pull request for the .d.ts file.  For right now I am just initializing a static member so that it is available later.
```ts
export class DurableHost<M extends EventBase, S extends StateBase> {
  private static _host: Host<any,any>;
  static init(host: Host<any, any>) {
    this._host = host;
  }
  public get host() { return DurableHost._host; }

  private rulesetName: string;
  private get rulesetName() { return this.rulesetName; }

  constructor(rulesetName: string) {
    this.rulesetName = rulesetName;
  }

  public post(event: M) {
    return this.host.post(this.rulesetName, event);
  }

  public assert(fact: M) {
    return this.host.assert(this.rulesetName, fact);
  }

  public patchState(contextState: S) {
    return this.host.patchState(this.rulesetName, contextState);
  }
}
```

**Comment by jruizgit** [comment]
Hi Rich, I assume you are rolling out your rules abstraction, which ultimately will generate the JSON definition. The host class definition makes sense. 

If you want to reuse the abstraction in the durable module, I have added an function to create the host alone (instead of runAll), over that you can add your API implementation.

```javascript
host = createHost(); // optional [database object array]
```

Also I have added another function you might find useful. If you have access to the redis instance you can queue a events for rulesets from other hosts (without the ruleset definition).

```javascript
q = d.createQueue('rules'); // optional [database object array]
q.post({id: 1, sid: 2, t: 'deposit'});
q.assert({id: 4, sid: 2, t: 'balance'});
q.retract({id: 4, sid: 2, t: 'balance'});
q.close();
```

**Comment by jruizgit** [comment]
One update on this. I fixed a few problems with the durable.js library, so it can be used now in 'strict' mode. I also added a TypeScript wrapper. The tooling for TypeScript (I used Sublime Text) is very helpful.

This is how I wrote a simple rule:
```javascript
import * as d from 'durable';

d.ruleset('a1')
    .whenAll(d.c['first'] = d.m['amount'].gt(100),
             d.c['second'] = d.m['location'].neq(d.c['first']['location']), 
             (c) => {
                console.log('fraud1 detected ' + c['first']['location'] + ' ' + c['second']['location']);
             })
    .whenStart(function(host) {
        host.post('a1', { id: 1, sid: 1, amount: 200, location: 'US' });
        host.post('a1', { id: 2, sid: 1, amount: 200, location: 'CA' });
    });
d.runAll();
```  

A statechart:
```javascript
import * as d from 'durable';

d.statechart('a2')
    .state('input')
        .to('denied').whenAll(d.m['subject'].eq('approve').and(d.m['amount'].gt(1000)), (c) => {
            console.log('a2 denied from: ' + c.s['sid']);
        })
        .to('pending').whenAll(d.m['subject'].eq('approve').and(d.m['amount'].lte(1000)), (c) => {
            console.log('a2 request approval from: ' + c.s['sid']);
        })
        .end()
    .state('pending')
        .to('pending').whenAll(d.m['subject'].eq('approved'), (c) => {
            console.log('a2 second request approval from: ' + c.s['sid']);
            c.s['status'] = 'approved';
        })
        .to('approved').whenAll(d.s['status'].eq('approved'), (c) => {
            console.log('a2 approved from: ' + c.s['sid']);
        })
        .to('denied').whenAll(d.m['subject'].eq('denied'), (c) => {
            console.log('a2 denied from: ' + c.s['sid']);
        })
        .end()
    .state('denied').end()
    .state('approved').end()
    .whenStart((host) => {
        host.post('a2', { id: 1, sid: 1, subject: 'approve', amount: 100 });
        host.post('a2', { id: 2, sid: 1, subject: 'approved' });
        host.post('a2', { id: 3, sid: 2, subject: 'approve', amount: 100 });
        host.post('a2', { id: 4, sid: 2, subject: 'denied' });
        host.post('a2', { id: 5, sid: 3, subject: 'approve', amount: 10000 });
    });

d.runAll();
```  

And a flowchart:
```javascript
import * as d from 'durable';

d.flowchart('a3')
    .stage('input')
        .to('request').whenAll(d.m['subject'].eq('approve').and(d.m['amount'].lte(1000)))
        .to('deny').whenAll(d.m['subject'].eq('approve').and(d.m['amount'].gt(1000)))
        .end()
    .stage('request')
        .run((c) => {
            console.log('a3 request approval from: ' + c.s['sid']);
            if (c.s['status'])
                c.s['status'] = 'approved';
            else
                c.s['status'] = 'pending';
        })
        .to('approve').whenAll(d.s['status'].eq('approved'))
        .to('deny').whenAll(d.m['subject'].eq('denied'))
        .to('request').whenAll(d.m['subject'].eq('approved'))
        .end()
    .stage('approve')
        .run((c) => {
            console.log('a3 approved from: ' + c.s['sid']);
        })
        .end()
    .stage('deny')
        .run((c) => {
            console.log('a3 denied from: ' + c.s['sid']);
        })
        .end()
    .whenStart((host) => {
        host.post('a3', { id: 1, sid: 1, subject: 'approve', amount: 100 });
        host.post('a3', { id: 2, sid: 1, subject: 'approved' });
        host.post('a3', { id: 3, sid: 2, subject: 'approve', amount: 100 });
        host.post('a3', { id: 4, sid: 2, subject: 'denied' });
        host.post('a3', { id: 5, sid: 3, subject: 'approve', amount: 10000 });
    });

d.runAll();
```  

I don't love it though. The phrases are too long because of the fluent (cascading) interface. I wish:

1. I could overload operators  
2. I could use decorators on any function (not just class members)  
3. I could delimit states, stages and rules using contexts instead of function calls  
4. TypeScript recognized '.' notation when indexers are defined (in addition to the [string] notation)

**Comment by enriched** [comment]
## Typings
Thank you for adding those typescript typings, if you want to check on what I wrote I dropped it in a gist [here](https://gist.github.com/enriched/189539b38eab840a05b4b74690b7fc8a).  Looking at your typings the only comment that I might have is that you can use optional parameters for things like:
```ts
    runAll: {
        ();
        (dbs: [database | string]);
        (dbs: [database | string], port: number);
        (dbs: [database | string], port: number, basePath: string);
        (dbs: [database | string], port: number, basePath: string, run: (host: IHost, app: any) => void);
        (dbs: [database | string], port: number, basePath: string, run: (host: IHost, app: any) => void, stateCacheSize: number);
    };
```
could be shortened to:
```ts
    runAll: {
        (dbs?: [database | string], port?: number, basePath?: string, run?: (host: IHost, app: any) => void, stateCacheSize?: number);
    };
```
But it looks like a lot of your function signatures are fairly complex so they might not be able to be expressed as a progressive series of optional parameters.  You could perhaps use a union type like:
```ts
type DecoratorOrExpression = decorator | expression;
```
although that might also make it more rather than less confusing.

## Syntax
On the subject of expressing rules in javascript without with.  Would it be possible to express the json that is being generated as a typescript interface and then simply feed that json into the rules engine? If we also made a json-schema we could do validation on it as well as have completion and validation on editors that implement json-schema recognition.  I did a little writeup on json-schema, interfaces and TypeScript [here](http://blog.enriched.io/using-json-schema/)

**Comment by jruizgit** [comment]
Hi Rich, thanks for the feedback. I have simplified the wrapper definition for runAll, createHost, createQueue. 

Let me study your gist API definition. 

Using JSON is interesting, in fact that was my original intention, inspired by the Mongo API. As the number of features in the project grew, the abstraction became more complex. This is how a simple rule definition would look like:

```javascript
    {
        suspect: {
            count: 2,
            all: [
                {first: {t: 'deposit'}},
                {second: {$and: [
                    {t: 'withrawal'},
                    {ip: {first: 'ip'}}, 
                ]}},
                {third: {$and: [
                    {t: 'balance'},
                    {ip: {first: 'ip'}}, 
                    {ip: {second: 'ip' }}, 
                ]}}
            ],
            run: (c) => { console.log('rule fired by ' + s.sid) }
        }
    }
```

**Comment by jruizgit** [comment]
Quick update on this. I followed your suggestion regarding JSON (thanks a lot for the insight). The JSON pasted above is the intermediate format understood by the C implementation. It would be very hard to maintain hundreds of rules in such format. I implemented a hybrid: Rulesets, Statecharts and Flowcharts are framed using JSON and expression are written using a cascading API. I have written (and published to npm) the TypeScript wrapper. 

**Ruleset**  

```typescript
import * as d from 'durable';
let m = d.m, s = d.s, c = d.c;

d.ruleset('a1_1', {
    whenAll: [c['first'] = m['amount'].gt(100),
              c['second'] = m['location'].neq(c['first']['location'])],
    run: (c) => {
        console.log('fraud1 detected ' + c['first']['location'] + ' ' + c['second']['location']);
    }
});
```

**Statechart**    

```typescript
import * as d from 'durable';
let m = d.m, s = d.s, c = d.c;

d.statechart('a2_2', {
    input: [{
        to: 'denied',
        whenAll: m['subject'].eq('approve').and(m['amount'].gt(1000)),
        run: (c) => {
            console.log('a2_2 denied from: ' + c.s['sid']);
        }
    }, {
        to: 'pending', 
        whenAll: m['subject'].eq('approve').and(m['amount'].lte(1000)),
        run: (c) => {
            console.log('a2_2 request approval from: ' + c.s['sid']);
        }
    }],
    pending: [{
        to: 'pending',
        whenAll: m['subject'].eq('approved'),
        run: (c) => {
            console.log('a2_2 second request approval from: ' + c.s['sid']);
            c.s['status'] = 'approved';
        }
    }, {
        to: 'approved',
        whenAll: s['status'].eq('approved'),
        run: (c) => {
            console.log('a2_2 approved from: ' + c.s['sid']);
        }
    }, {
        to: 'denied',
        whenAll: m['subject'].eq('denied'),
        run: (c) => {
            console.log('a2_2 denied from: ' + c.s['sid']);
        }
    }],
    denied: {},
    approved: {},
});
```
**Flowchart**
```typescript
import * as d from 'durable';
let m = d.m, s = d.s, c = d.c;

d.flowchart('a3_1', {
    input: {
        request: { whenAll: m['subject'].eq('approve').and(m['amount'].lte(1000)) },
        deny: { whenAll: m['subject'].eq('approve').and(m['amount'].gt(1000)) }
    }, 
    request: {
        run: (c) => {
            console.log('a3_1 request approval from: ' + c.s['sid']);
            if (c.s['status'])
                c.s['status'] = 'approved';
            else
                c.s['status'] = 'pending';
        },
        approve: { whenAll: s['status'].eq('approved') },
        deny: { whenAll: m['subject'].eq('denied') },
        request: { whenAll: m['subject'].eq('approved') }
    },
    approve: {
        run: (c) => {
            console.log('a3_1 approved from: ' + c.s['sid']);
        }
    },
    deny: {
        run: (c) => {
            console.log('a3_1 denied from: ' + c.s['sid']);
        }
    }
});
```

**Comment by enriched** [comment]
Love the new wrapper!  I'm just switching my stuff over to it.  Question about timeouts though, right now they are in IDurableBase as timeout(duration: number)  is that supposed to be a timeout(identifier: string)?  Just trying to figure out how to listen for timeouts.

**Comment by enriched** [comment]
Also, is startTimer missing from IHost?

**Comment by jruizgit** [comment]
The timeout function definition was incorrect. I just fixed it (and npm publish). The timer sample looks like:

```typescript
import * as d from 'durable';
let m = d.m, s = d.s, c = d.c, timeout = d.timeout;

d.flowchart('test', {
    start: {
        action: { whenAll: m['command'].eq('start') }
    },
    action: {
        run: (c) => {
            c.s['count'] = (c.s['count'] ? c.s['count'] + 1 : 1);
            c.post({ id: 'p_' + c.s['count'], sid: c.s['sid'], command: 'await' });
        },
        await: { whenAll: m['command'].eq('await') }
    },
    await: {
        run: (c) => {
            c.startTimer('timeout', 1, 't_' + c.s['count']);
        },
        action: { whenAll: timeout('timeout') }
    },
    whenStart: (host) => {
        for (let i = 0; i < 10; i++) {
            host.post('test', { id: 10, sid: i, command: 'start' });
        }  
    }
});

d.runAll();

**Comment by enriched** [comment]
Thanks for all the help with getting this to work in typescript!
