### ISSUE TITLE
Query: What is the equivalent of post_batch when posting with curl.

### ISSUE THREAD

**Issue by 2433kevin** [jruizgit/rules#164]
Hi,
In `@when_start` with the help of  `host.post_batch` one can post json arrays as shown in the example (https://github.com/jruizgit/rules/blob/master/docs/py/reference.md#action-batches). 
If I would like to post json array using curl what should be given in the url?

**Comment by jruizgit** [comment]
Hi, thanks for posting the question. The http interface does not support posting a batch of events. It is not hard to implement. I will get this done in the next couple of days.

**Comment by 2433kevin** [comment]
Thank you!

**Comment by ShrilakshmiH** [comment]
Hello,

I'm also looking at similar feature where I can post to durable rules from outside. I'm using Python library 'request' to post events. As I have a large set of events the plan is to post in a batch instead posting all the events in a loop. Is there any other way to do this?

**Comment by jruizgit** [comment]
Hi, I have added support for this case. All you need to do is post an array of objects. Please use: version 0.33.126 for Python, 0.34.51 for Ruby and 0.36.86 for node.js.

**Comment by 2433kevin** [comment]
Thanks a ton @jruizgit :) I have posted another query [#166]( https://github.com/jruizgit/rules/issues/166 ).
Could you please answer that?
