### ISSUE TITLE
How to get the index of the element in array for which the rule matched?

### ISSUE THREAD

**Issue by nsecchi-carecloud** [jruizgit/rules#167]
Hey Jesus, We want to use durable rules engine to go over our formData and validate fields. I am currently using the state to store all of my form data.

My idea is to go over the data inside the form and create validation errors as events when the engine finds something wrong. Everything works reasonably good until I want to specify, in my event which was the element, inside an array, for which a certain rule has failed:

```
  whenAll: {
    s.dirty == true
    s.charges_data.anyItem(item.code == '2' && (~item.modifier1 || item.modifier1 != '3'))
  }
  run: {
    s.dirty = false
    post({ field: 'charges_data[SomeItem].modifier1', error : "Missing 3 modifier"})
  }
```
Data would come through like this:
```
{  
  "charges_data":[  
    {  
      "code":"2",
      "modifier1": "3"
    },
    {  
      "code":"2"
    },
  ],
  "dirty":true,
  "iteratorIndex":0
}
```
I tried creating an iterator, we can discuss that approach, but it lead me to a dead end.

Is this something the engine can do? Any help would be appreciated! Cheers!

**Comment by nsecchi-carecloud** [comment]
I realized this is not the right approach, so I'm closing the issue!

**Comment by prav1234567** [comment]
Hey,
 please let me know what is the right approach.

Sorry for the trouble and Thank you.
