### ISSUE TITLE
Allow timeout more than once per sid

### ISSUE THREAD

**Issue by enriched** [jruizgit/rules#17]
I don't know how difficult this is, but would it be possible to have timeouts fire multiple times for a sid?

I want to be able to kick a sid out of a flowchart stage if it has been in the stage for longer than the timeout.  I don't know if there is another way of doing this that is recommended.

**Comment by jruizgit** [comment]
Hi Rich, yes it is possible to have timeouts fire multiple times. You need to pass a different id each time you call startTimer. For example

```javascript
    whenAll(or(m.count.eq(0), timeout('myTimer')), function (c) {
        c.s.count += 1;
        c.startTimer('myTimer', 1, c.s.count);
    });
```

**Comment by enriched** [comment]
Thanks!  I am trying this out right now.  What determines when these are evicted from the cache?  I tried out running 400 sid with 1 second timeouts through a 3 stage flowchart where it alternated between an awaiting state and a action state.  It did really well!  But then after about 2 or 3 thousand cycles it died with an error message coming from redis.  

I intend to look into it a bit more, but is there anything off the top of your head that would cause this?

**Comment by enriched** [comment]
I worked on making a simple case with it, and am testing using the following:
```
var d = require('durable');
var uuid = require('node-uuid');


var sidCount = 400;
var counters = new Array(400).fill(0);
var side = Math.ceil(Math.sqrt(sidCount));
function printCounters() {
  for(var i = 0; i < side; i++) {
    var start = i * side;
    process.stdout.write('|' + counters.slice(start, start + side -1).join(' ') + '|\n');
  }
}

with(d.flowchart('test')) {
  with(stage('start')) {
    to('action').whenAll(m.command.eq('start'));
  }

  with(stage('action')) {
    run(function(c) {
      counters[c.s.sid]++;
      console.log('Fired action for sid[' + c.s.sid + ']');
      printCounters();
      c.post({id: uuid.v4(), sid: c.s.sid, command: 'await'});
    });
    to('await').whenAll(m.command.eq('await'));
  }

  with(stage('await')) {
    run(function(c) {
      c.startTimer('timeout', 1, uuid.v4());
    });
    to('action').whenAll(timeout('timeout'));
  }

  whenStart(function (host) {
    for(var i = 0; i < sidCount; i++) {
      host.post('test', {id: uuid.v4(), sid: i, command: 'start'});
    }
  })
}

d.runAll();
```

**Comment by enriched** [comment]
Still have that script running, what I have notice so far:
* When it started it was running about 1 second to show output for the 0th sid.  After abouty an hour it is now taking about 3 seconds.
* The counters are diverging by a fair amount.  I don't know if adding additional workers would fix that.

Am I just experiencing an accumulation of events that my node process is not fast enough to handle? Redis says that it is using 1.23G of memory (from the INFO command).

Here is a frame of the current output:
```
Tue May 17 2016 13:36:05 GMT-0700 (PDT): Fired action for sid[0]
|2690 2686 2401 2248 2117 2063 2032 1995 1945 1861 2683 2587 2559 2538 2519 2492 2470 2451 2436 2420 2400 2382 2368 2352 2333 2315 2305 2292 2273 2262 2247|
|2222 2201 2188 2177 2160 2148 2137 2125 2115 2107 2102 2095 2090 2084 2077 2074 2069 2068 2063 2059 2055 2053 2050 2047 2043 2042 2037 2035 2032 2030 2025|
|2017 2013 2009 2007 2002 1999 1995 1991 1986 1981 1978 1976 1973 1967 1959 1951 1944 1936 1931 1922 1914 1904 1894 1885 1874 1869 1861 1845 1833 1823 1814|
|1799 1790 1780 1771 2681 2656 2621 2605 2602 2602 2600 2596 2593 2590 2585 2584 2582 2578 2576 2572 2568 2567 2565 2560 2558 2555 2552 2549 2547 2547 2545|
|2542 2539 2537 2535 2535 2531 2528 2525 2525 2525 2525 2521 2515 2513 2510 2506 2503 2501 2499 2495 2493 2493 2489 2488 2487 2482 2481 2480 2478 2477 2474|
|2469 2468 2466 2464 2464 2461 2460 1537 2455 2452 2450 2449 2447 2446 2446 2445 2445 2444 2442 2439 2436 2433 2431 2429 2428 2427 2427 2426 2425 2423 2419|
|2413 2411 2408 2408 2408 2408 2407 2405 2400 2399 2397 2396 2392 2391 2389 2386 2385 2384 2380 2379 2378 2377 2377 2374 2373 2371 2368 2368 2368 2367 2367|
|2365 2363 2362 2361 2360 2357 2348 2346 2345 2343 2343 2342 2342 2339 2339 2336 2331 2331 2328 2327 2324 2322 2319 2318 2316 2315 2312 2311 2311 2311 2311|
|2309 2309 2309 2308 2304 2302 2302 2301 2300 2299 2299 2297 2296 2292 2291 2289 2286 2284 2283 2281 2280 2278 2274 2273 2273 2270 2268 2266 2266 2265 2265|
|2264 2262 2261 2260 2260 2260 2259 2256 2253 2253 2251 2250 2247 2245 2245 2242 2240 2237 2237 2235 2235 2233 2230 2229 2229 2228 2228 2226 2226 2224 2222|
|2221 2219 2130 2215 2212 2209 2208 2205 2203 2201 2199 2199 2199 2196 2193 2192 2192 2191 2190 2189 2188 2186 2185 2184 2182 2181 2181 1935 2180 2180 2174|
|2171 2170 2168 2168 2168 2167 2162 2161 2157 2156 2155 2154 2153 2152 2151 2150 2149 2149 2147 2145 2145 2145 2144 2144 2143 2143 2141 2138 2133 2131 2130|
|2130 2130 2127 2127 2126 2126 2124 2124 2124 2122 2119 2119 2119 2118 2118 2117 2114 2114 2114 2114 2113 2113 2113 2111 2109 2109 2106 2106 2105 2105 2104|
|2104 2104 2104 2103 2102 2102 2101 2101 2100 2098 2098 2097 2097 2097 2094 2094 2094 2093 2092 2092 2092 2091 2090 2090 2089 2088 2087 2086 2086 2085 1252|
|2084 2084 2084 2084 2084 2082 2082 2082 2079 2077 2077 2077 2076 2076 2076 2076 2074 2074 2074 1307 2074 2074 2074 2074 2074 2074 2073 2073 2071 2071 2070|
|2069 2068 2068 2068 2068 2068 2068 2068 2068 2068 2067 2066 2065 2065 2065 2065 2064 2064 2063 2063 2063 2062 2062 2061 2061 2060 1927 2060 2060 2060 2059|
|2059 2058 2058 2057 2057 2056 2055 2055 2054 2054 2054 2054 2054 2054 2053 2053 2053 2053 2053 2053 2053 2052 2052 2052 2052 2051 2050 2050 2050 2050 2050|
|2049 2049 2049 2048 2048 2047 2046 2046 2046 2045 2044 2043 2043 2043 2043 2043 2043 2043 2042 2042 2042 2042 2042 2042 2042 2042 2041 2041 2040 2040 2040|
|2038 2038 2038 2037 2036 2036 2036 2036 2036 1516 2036 2036 2035 2035 2035 2035 2034 2034 2034 2033 2032 2032 2032 2032 2032 2032 2032 2032 2032 2032 2031|
|2031 2031 2028 2028 2028 2028 2028 2028 2027 2026 2026 2025 2024 2024 2024 2023 2023 2021 2021 2021 2021 2020 2020 2019 2019 2019 2018 2018 2018 2018 2018|
|2016 2016 2016 2015 2015 2015 2013 2013 2013 2013 2012 2012 2011 2011 2011 2011 2010 2010 2009 2009 2009 2009 2009 2008 2008 2008 2008 2008 2008 2007 2006|
|2005 2005 2005 2004 2004 2003 2003 2003 2002 2002 2002 2002 2001 2000 2000 2000 1999 1999 1999 1998 1998 1997 1995 1995 1995 1995 1995 1995 1995 1995 1994|
|1993 1993 1992 1992 1992 1991 1991 1990 1990 1990 1989 1987 1987 1987 1986 1986 1986 1984 1984 1984 1984 1982 1982 1982 1981 1981 1980 1980 1980 1980 1980|
|1980 1980 1978 1978 1978 1977 1977 1977 1977 1977 1977 1977 1977 1977 1975 1974 1974 1974 1974 1974 1974 1974 1974 1974 1973 1972 1971 1971 1970 1970 1969|
|1967 1967 1967 1967 1131 1964 1962 1961 1961 1960 1959 1959 1957 1955 1954 1954 1954 1954 1954 1953 1953 1952 1949 1948 1948 1948 1948 1947 1947 1947 1946|
|1944 1944 1944 1944 1944 1944 1943 1939 1937 1937 1936 1934 1933 1933 1933 1932 1932 1932 1931 1931 1931 1931 1930 1930 1929 1929 1929 1926 1926 1925 1922|
|1919 1918 1917 1916 1916 1916 1916 1915 1913 1912 1910 1910 1909 1907 1907 1907 1906 1905 1903 1902 1900 1899 1898 1897 1896 1895 1895 1894 1894 1894 1891|
|1890 1890 1890 1888 1886 1886 1885 1883 1883 1881 1879 1877 1876 1876 1875 1875 1874 1874 1874 1872 1872 1872 1872 1872 1870 1869 1867 1867 1865 1865 1864|
|1863 1862 1862 1861 1861 1859 1857 1857 1854 1854 1851 1848 1847 1845 1845 1845 1845 1841 1839 1839 1839 1838 1836 1836 1832 1830 1828 1828 1827 1827 1826|
|1824 1823 1823 1823 1822 1821 1821 1821 1817 1816 1815 1814 1813 1813 1810 1810 1810 1808 1807 1807 1807 1807 1805 1805 1804 1804 1803 1803 1803 1803 1802|
|1798 1796 1796 1796 1796 1795 1795 1794 1794 1793 1789 1789 1786 1786 1785 1785 1784 1783 1781 1780 1779 1777 1777 1777 1776 1774 1773 1773 1773 1772 1771|
|1765 1765 1764 1760 1759 1758 1757 1756 2678 2675 2674 2669 2668 2666 2662 2661 2661 2657 2652 2650 2647 2642 2638 2634 1206 2630 2627 2622 2618 2611 2610|
```

**Comment by jruizgit** [comment]
Hi Rich, thanks for providing all the details on the scenario. I didn't have the opportunity to debug it today.  I have a theory though: The internal ruleset dispatch loop is not able to keep up with the events spread over the large number of sids. I'm guessing if you keep the sid count at 100, timers will not fall behind.

**Comment by enriched** [comment]
Thanks for the input!  Would this also probably be fixed if I had multiple node instances running for handling the ruleset?  I guess I am a little confused about what is happening on redis and what is happening locally.  I need to set aside some time to dig a little deeper and understand the interaction there.

**Comment by jruizgit** [comment]
Hi Rich, just wanted to give you a quick update. I have been debugging your scenario. I found a couple of bugs I will be fixing:

1. The inference event cleanup routine is not kicking in, so the inference event list grows on every timeout, the inference evaluation time degrades and as a consequence it takes longer to fire the flowchart actions.
2. There is a sig 11 in the LRU cache implementation in the client, if you try to increase the number of sids beyond 1024, the client process will crash.

This slightly simpler ruleset doesn't trigger the cleanup problem, you can try it while I fix the problems above:

```javascript
  var sidCount = 1024;
  var counters = new Array(sidCount).fill(0);
  var side = Math.ceil(Math.sqrt(sidCount));
  function printCounters() {
    for(var i = 0; i < side; i++) {
      var start = i * side;
      process.stdout.write('|' + counters.slice(start, start + side - 1).join(' ') + '|\n');
    }
  }

  with(d.ruleset('test')) {
    whenAll(m.command.eq('start').or(timeout('timeout')), function(c) {
        c.s.count = (c.s.count ? c.s.count + 1: 1);
        counters[c.s.sid] = c.s.count;
        if(c.s.sid === 0) {
          console.log(Date() + ': Fired action for sid[' + c.s.sid + ']');
          printCounters();
        }
        c.startTimer('timeout', 1, 't_' + c.s.count);
    });
    whenStart(function (host) {
      for(var i = 0; i < sidCount; i++) {
        host.post('test', {id: sidCount, sid: i, command: 'start'});
      }
    });
  }   

  d.runAll();
```

In your scenario as you add more SIDs, you will reach a point where the system won't be able to evaluate all the events under 1 second. The first gate will be redis, you can scale redis by adding more instances (passing several db objects in the runAll function). The second gate will be the number of client processes, you can scale the clients by using the 'cluster' module.

**Comment by jruizgit** [comment]
One more update. I have fixed the problem with the cleanup routine and the segmentation fault when using more than 1024 sids (I uploaded the new package to npm). 

The following script is stable:

```javascript
  var sidCount = 1024;
  var counters = new Array(sidCount).fill(0);
  var side = Math.ceil(Math.sqrt(sidCount));
  function printCounters() {
    for(var i = 0; i < side; i++) {
      var start = i * side;
      process.stdout.write('|' + counters.slice(start, start + side - 1).join(' ') + '|\n');
    }
  }

  with(d.flowchart('test')) {
    with(stage('start')) {
      to('action').whenAll(m.command.eq('start'));
    }

    with(stage('action')) {
      run(function(c) {
        c.s.count = (c.s.count ? c.s.count + 1: 1);
        counters[c.s.sid] = c.s.count;
        if(c.s.sid === 0) {
          console.log(Date() + ': Fired action for sid[' + c.s.sid + ']');
          printCounters();
        }
        c.post({id: 'p_' + c.s.count, sid: c.s.sid, command: 'await'});
      });
      to('await').whenAll(m.command.eq('await'));
    }

    with(stage('await')) {
      run(function(c) {
        c.startTimer('timeout', 1, 't_' + c.s.count);
      });
      to('action').whenAll(timeout('timeout'));
    }

    whenStart(function (host) {
      for(var i = 0; i < sidCount; i++) {
        host.post('test', {id: sidCount, sid: i, command: 'start'});
      }
    })
  }

  d.runAll();
```  
Also to test the limits I tried the following script (16 processes and 8 redis instances):  
```javascript
var d = require('durable');
var cluster = require('cluster');
if (cluster.isMaster) {
     for (var j = 0; j < 16; j++) {
         cluster.fork();
     }

     cluster.on("exit", function (worker, code, signal) {
         cluster.fork();
     });
} else {

    var sidCount = 11000;
    function printCounters(host) {
        var avg = 0;
        for (var i = 0; i < sidCount; i++) {
          avg += host.getState('test', i).count;
        } 
        
        avg /= sidCount;
        console.log('average : ' + avg);
        
        var stdv = 0;
        for (var i = 0; i < sidCount; i++) {
          stdv += Math.pow(host.getState('test', i).count - avg, 2);
        }

        stdv /= sidCount;
        stdv = Math.sqrt(stdv);
        console.log('standard deviation : ' + stdv);
    }

    with(d.ruleset('test')) {
        whenAll(m.command.eq('start').or(timeout('timeout')), function(c) {
            if (c.m.command === 'start') {
                c.s.count = 0;
            } else {
                c.s.count += 1;
                if (c.s.sid === 0 && c.s.count % 20 === 0) {
                  console.log(Date());
                  setImmediate(printCounters, c.getHost());
                }
            }
            c.startTimer('timeout', 1, 't_' + c.s.count);
        });
        whenStart(function (host) {
          for(var i = 0; i < sidCount; i++) {
            host.post('test', {id: sidCount, sid: i, command: 'start'});
          }
        });
    }   

    d.runAll(['/tmp/redis0.sock', 
              '/tmp/redis1.sock', 
              '/tmp/redis2.sock', 
              '/tmp/redis3.sock', 
              '/tmp/redis4.sock', 
              '/tmp/redis5.sock',
              '/tmp/redis6.sock', 
              '/tmp/redis7.sock'], null, null, null, 12000);
}
``` 
The test fires 11000 timers every second. The test ran without increasing the standard deviation and keeping the average stable. The four cores in my IMac I7 were above 85% utilization. When I change the sid number to 12000, on every iteration, the standard deviation starts increasing and the average becomes lower than expected. Which means the test produces more work than what the system can handle.

**Comment by enriched** [comment]
As a general question, do you think that rules will be able to handle a lot of long running timeouts well?  Or would you recommend that I use another scheduling service for long timeouts and have that feed an event back in to rules?

**Comment by jruizgit** [comment]
Hi Rich, given the system can scale horizontally by adding more hosts (redis or ruleset hosts) the answer is yes. 

But, honestly that is not a great answer. Let's say you define "a lot" as  1 million concurrent timeout actions every second (remember, scale is gated by the number of concurrent actions triggered, not by the number of timers in flight). Assuming the system can scale linearly, based on our observations in this conversation, you would need 100 hosts to handle such load (I haven't tested it though).

Would that be a reasonable use of resources?
What would be your resource usage when using another scheduling service?

**Comment by enriched** [comment]
Is there a good way for me to see the statistics on a redis instance that I have running?  I currently have an instance running in Azure on their C1 Tier (1GB memory, 100 Mb/s).  I have about 1000 ongoing flowchart entities sitting in a "await" stage with a 24 hour long timeout.  Redis is behaving fairly well right now, but when I originally tried to connect it to their smallest instance that we had some other stuff being cached in, it didn't behave well.  I think that bandwidth was an issue, but I am not sure.  I'm attaching the graphs that I currently have for the C1 instance that I have running right now.

As far as resource usage with other scheduling services, it seems like [Kue](https://github.com/Automattic/kue) is a bit heavier and we have an in hose scheduler that is using postgres that hasn't seen much stress testing yet.  I would expect that the postgres scheduler would be able to handle more long running schedules, but not as much throughput.
![screen shot 2016-06-07 at 11 55 15 am](https://cloud.githubusercontent.com/assets/12580387/15870884/d1a18402-2ca6-11e6-8544-202ba45d9b3d.png)
![screen shot 2016-06-07 at 11 55 29 am](https://cloud.githubusercontent.com/assets/12580387/15870883/d1a0767a-2ca6-11e6-8cdc-78a35e16843a.png)

**Comment by enriched** [comment]
Little update about this.  I have two docker containers with the same ruleset connecting to the Redis instance and one of them just went down.  Got the errors:

2016-06-07T20:08:57.249149800Z [Error: Could not assert timers, error code: 302] 
2016-06-07T20:08:57.251940500Z [Error: Could not assert timers, error code: 302] 
2016-06-07T20:08:57.253486500Z [Error: Could not assert timers, error code: 302] 
2016-06-07T20:08:57.254587800Z [Error: Could not assert timers, error code: 302] 
2016-06-07T20:08:57.255675300Z [Error: Could not assert timers, error code: 302] 
2016-06-07T20:08:57.257010200Z [Error: Could not assert timers, error code: 302] 
2016-06-07T20:08:57.258166700Z [Error: Could not assert timers, error code: 302] 
2016-06-07T20:08:57.258987500Z [Error: Could not assert timers, error code: 302] 
2016-06-07T20:08:57.261968000Z [Error: Could not assert timers, error code: 302] 
2016-06-07T20:08:57.263517500Z [Error: Could not assert timers, error code: 302] 
2016-06-07T20:08:57.264441200Z Exiting Error: Could not start action, error code: 302 
2016-06-07T20:08:57.272240200Z getReply err 1, 11, Resource temporarily unavailable 
2016-06-07T20:08:57.272260000Z peekTimers err string NOAUTH Authentication required. 
2016-06-07T20:08:57.272266000Z peekTimers err string NOAUTH Authentication required. 
2016-06-07T20:08:57.272271200Z peekTimers err string NOAUTH Authentication required. 
2016-06-07T20:08:57.272276000Z peekTimers err string NOAUTH Authentication required. 
2016-06-07T20:08:57.272281000Z peekTimers err string NOAUTH Authentication required. 
2016-06-07T20:08:57.272286000Z peekTimers err string NOAUTH Authentication required. 
2016-06-07T20:08:57.272291200Z peekTimers err string NOAUTH Authentication required. 
2016-06-07T20:08:57.272296200Z peekTimers err string NOAUTH Authentication required. 
2016-06-07T20:08:57.272301100Z peekTimers err string NOAUTH Authentication required. 
2016-06-07T20:08:57.272305700Z peekTimers err string NOAUTH Authentication required. 
2016-06-07T20:08:57.272310600Z peekAction err string NOAUTH Authentication required. 
2016-06-07T20:08:57.280235300Z 

After the node went down the redis statistics did what I think you would expect them to.  All of the resource (except memory and key count) usage dropped by 50%.

**Comment by jruizgit** [comment]
Hi Rich, thanks for reporting the error. 

The process failed fast due to redis connection failure. Are you running in Windows or Linux? Linux will try to recover the connection, if the attempt fails the process will shut down.

**Comment by enriched** [comment]
The Image is based on the node:5 docker image which is based on the debian:jessie image.  Should I expect that the container will need to restart when disconnects happen?

**Comment by jruizgit** [comment]
Hi Rich, getting back to you on this. Yes, in case of failure you need to restart the process. Looking at the graphs, it seems the rulesEngine poll timeout is too aggressive. I'll work on a back off strategy so the load on redis is minimal when there are no scheduled actions.

**Comment by enriched** [comment]
Thanks for all the help!

**Comment by jruizgit** [comment]
Hi Rich, I forgot to mention: last week I pushed a change to reduce the client load on the redis server. The client now will poll periodically for actions to execute (250 ms). Once an action is executed it will keep taking actions in a tight loop until no actions are available. In addition to significantly reducing the load, connection errors should happen less frequently.
