### ISSUE TITLE
Query: Running multiple rulesets in different clients working against the same Redis Server

### ISSUE THREAD

**Issue by sandeeps2** [jruizgit/rules#172]
Is it possible to run multiple rule set clients against a single redis server? 

To test this how do I run

node test1.js --> on local port 5000 (default)
node test2.js (port=6000) --> run on a different port. How to do this? I am new to node.js

Both test1 and test2 are pointing to the same redis server.

Thanks in advance

**Comment by sandeeps2** [comment]
Thanks for your response. I was not looking to run multiple replicas of the same rule set client but clients with different rule sets.

metrics.js

`var d = require('durable');

d.ruleset('metrics', function() {
  // antecedent
  whenAll: m.value > 100
  // consequent
  run: console.log('Value exceeded threshold ' + m.value)
  // Run rule on startup
  whenStart: post('metrics', { value: 150 })
});

d.runAll();
`
logs.js
`var d = require('durable');

d.ruleset('logs', function() {
  // antecedent
  whenAll: m.message == 'NullPointerException'
  // consequent
  run: console.log('Found error condition ' + m.message)
  // Run rule on startup
  whenStart: post('logs', { message: 'NullPointerException' })
});

d.runAll();
`
If I run `node metrics.js` and `node logs.js` I get the following error while the redis server is up, I get the following error.

Error: listen EADDRINUSE :::5000
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at Server.listen (net.js:1476:7)
    at Function.app.listen (/home/sanshriv/durable_rules/examples/node_modules/express/lib/application.js:533:24)
    at Function.that.run (/home/sanshriv/durable_rules/examples/node_modules/durable/libjs/durableEngine.js:1573:25)
    at Object.runAll (/home/sanshriv/durable_rules/examples/node_modules/durable/libjs/durable.js:1885:17)
    at Object.<anonymous> (/home/sanshriv/durable_rules/examples/metrics.js:12:3)
    at Module._compile (module.js:643:30)

**Comment by sandeeps2** [comment]
I can get a client to run on a different port as follows:

d.runAll([{host:'127.0.0.1', port:6379, password: ''}], 6000);

I did verify 2 clients with different rule sets work fine running against the same redis instance.

Follow up question:

What are the best practices and guidelines for running a large number of rule sets? Is there a documentation for deployment strategies?

A) Multiple worker processes using the cluster module that you pointed in your reply.
How does this work? Is each worker process stateless and which client instance is invoked when a rule fires?
B) Partitioning of the rule sets among multiple processes each handling a subset of the rules
C) Hybrid of A) & B)

**Comment by jruizgit** [comment]
Answering you follow up questions:

A) Each worker process is stateless, the first idle process will be used when a rule fires.
B) You would need to separate the rules in different rulesets.  

In other words, if you need do distribute the work among several processes, all the processes need to have the entire ruleset definition.

**Comment by sandeeps2** [comment]
Thanks for the clarification.
