### ISSUE TITLE
Nested arrays not working as expected in some cases

### ISSUE THREAD

**Issue by hea-lab** [jruizgit/rules#177]
Hi Jesus,

The code below does not work, but it does if I remove the condition (m.field == 1).

I guess something is wrong in the isMatch/isMatchArray functions, could you kindly check?

```
`   whenAll: {
        m.field == 1 && m.payments.anyItem(item.anyItem(item > 100))
    }
    run: console.log('fraud detected ' + JSON.stringify(m.payments))

    whenStart: {
        post('risk', { field: 1, payments: [ [ 200, 20, 30 ], [ 30, 40, 50 ], [ 10, 20 ] ]});    
    }
});
```

`

**Comment by jruizgit** [comment]
Thanks for reporting the issue. I have fixed the bug and published a new version to npm, pypi and gem. Please use node.js version 0.36.88, python version 0.33.129 and ruby version 0.34.53.

**Comment by hea-lab** [comment]
Thanks for your fix, it works properly with the example. Unfortunately, I noticed some regressions with other rules. Find hereafter an example which reproduces the issue.

`       whenAll: m.array.anyItem(~item.field1 && item.field2 == 2)
	run: console.log({event: m});
	whenStart: {
		post('test', { array: [{field2: 1}]});    
	}`

**Comment by jruizgit** [comment]
Thanks for providing the use case. I have pushed a fix. Please use node.js version 0.36.89, python version 0.33.130 and ruby version 0.34.54.

**Comment by hea-lab** [comment]
it works fine
