### ISSUE TITLE
Auditing sids

### ISSUE THREAD

**Issue by enriched** [jruizgit/rules#18]
Hey Jesus!

I am looking for a way to audit my sids. Essentially the sids that I use correlate to ids in a database row, and I want to make sure that everything that currently exists in the cache belongs there. For example, if I didn't use deleteState at a termination node of a flowchart, or if I ended up migrating the rule definition and something got left in an abandoned state.  Also, I probably want to write some cli stuff for debugging what is currently going on.  What is the best way to do that?

**Comment by jruizgit** [comment]
Hi Rich, there is no API readily available for you to do that. If you connect to the redis server using redis-cli, you can do `hgetall rulesetname!s`, which will display all available sids and their state. I'll implement a client API to do this so I can shield users from any future format changes in redis state.

**Comment by enriched** [comment]
Sounds great, it will be a hacky script, but it will give me a way to resolve stuck sids 🙈
