### ISSUE TITLE
batch of events with different sid

### ISSUE THREAD

**Issue by hea-lab** [jruizgit/rules#183]
I have a question regarding to the current design. It seems we cannot for now use different sessions Id in the same batch of events. 
Is it a limitation of the current design or did you decide to handle only a batch of events pertaining to the same session for some specific reasons?

**Comment by jruizgit** [comment]
Hi, thanks for asking the question. The current implementation resolves the connection belonging to a session id only once when processing a batch. Handling different session ids is feasible. I'm thinking the simplest approach might be to separate the batches in the scripting layer (node, python, ruby).
