### ISSUE TITLE
Missing attribute and undefined variable errror in get_ruleset_state 

### ISSUE THREAD

**Issue by tonythomas01** [jruizgit/rules#195]
https://github.com/jruizgit/rules/blob/master/libpy/durable/engine.py#L976

```
    def get_ruleset_state(self, ruleset_name):
        return self.get_ruleset(ruleset_name).get_ruleset_state(sid)
``` 
2 issues: 
1. `Ruleset` do not have `get_ruleset_state` 
2. `sid` is not defined.

**Comment by jruizgit** [comment]
Hi, thanks for reporting this issue. The method is not referenced anywhere in the code. It is a leftover from an old version. I have removed it to avoid confusion.
