### ISSUE TITLE
Allow access to traceback from exceptions thrown 

### ISSUE THREAD

**Issue by tonythomas01** [jruizgit/rules#199]
https://github.com/jruizgit/rules/blob/master/docs/py/reference.md#unhandled-exceptions talks about this nice decorator 
```
    # when the exception property exists
    @when_all(+s.exception)
``` 
is there a way to get the full traceback from the exception for logging and debugging purpose ?

**Comment by jruizgit** [comment]
Hi, thanks for posting the question. Right now, there is no out of the box way for doing that. 

It is actually not hard. Line 336, Engine.py
```python
            try:
                self._func(c) 
            except BaseException as error:
                c.s.exception = 'exception caught {0}'.format(str(error))
```

I would need to do something like this:
```python
            try:
                self._func(c) 
            except BaseException as error:
                t, v, tb = sys.exc_info()
                c.s.exception = 'exception caught {0}, traceback {1}'.format(str(error), traceback.format_tb(tb))
```

**Comment by tonythomas01** [comment]
Thank you. I think this would be perfect. If you want me to upload a patch on this, I can do that.

**Comment by tonythomas01** [comment]
Closing the issue! Thanks.
