### ISSUE TITLE
didn't know how to start any example in Python

### ISSUE THREAD

**Issue by AsmaZgo** [jruizgit/rules#20]
Whenever i run python examples in folder testpy (python test*.py) i get this error:
 in __init__
rules.error: Could not create connection, error code: 301

**Comment by jruizgit** [comment]
Hi, thanks a lot for posting the question. By default the rules engine assumes there is a redis instance listening on localhost port 6379. 

You can install a local redis instance:

https://github.com/jruizgit/rules/blob/master/docs/py/reference.md#local-setup

If you already have a redis instance, you can configure your ruleset to use it by passing host_name and port to the run_all function:

`run_all([{'host': 'host_name', 'port': port, 'password': 'password'}])`

**Comment by jruizgit** [comment]
Closing this issue. No action item left.
