### ISSUE TITLE
Definition of sid and id

### ISSUE THREAD

**Issue by r0goyal** [jruizgit/rules#21]
Hi,

While going through documentation, I could not figure out what is the significance of **id** and **sid**. Can you please explain what these parameters mean and how they are used internally ?

**Comment by jruizgit** [comment]
Hi, thanks for posting the question. 

A sid identifies an inference session. Inference context and state are keyed  by sid. For instance if action A depends on Message B and Message C and Message C is observed, the fact that message C has been oseeved is stored in a HashSet keyed by sid.

An id uniquely identifies a Message. It ensures the idempotency of post, assert and retract operations.

Hope this helps,

**Comment by r0goyal** [comment]
@jruizgit Thanks a lot Jesus. This is really helpful.
