### ISSUE TITLE
infinite loop 

### ISSUE THREAD

**Issue by alonbg** [jruizgit/rules#222]
The following snippet is an infinite loop.

```python
from durable.lang import *

with ruleset('state-test'):

    @when_all(+m.o)
    def infinite(c):
        c.s.o = c.m.o
        print(c.s.o)

    @when_start
    def start(host):
        host.post('state-test', { "a": 1, "o": 2 })

run_all()
```

**Comment by jruizgit** [comment]
Hi, thanks for asking the question. Any update to the context state is asserted as an event, that is why the rule keeps firing when `c.s.o` is changed. The following code does not run infinitely:

```python
with ruleset('state-test'):

    @when_all(+m.o)
    def infinite(c):
        c.s.o1 = c.m.o
        print(c.s.o1)

    @when_start
    def start(host):
        host.post('state-test', { "a": 1, "o": 2 })

run_all()
```

**Comment by alonbg** [comment]
Thank you for answering
@jruizgit , Do you think it would be worth updating the docs on this particular behaviour  ?
Do you need help with this ?
