### ISSUE TITLE
how state's SID work 

### ISSUE THREAD

**Issue by alonbg** [jruizgit/rules#225]
Hi @jruizgit 
I would like to confirm my understanding of how to work with SID:
1. SID in event/fact is compared implicitly and assures that only  events/facts with the same SID will take part in the rule. This also applies to state modification (i.e. the state is modified and checked in the SID scope.

2. event/SID or fact/SID represents fact/event of an object `SID` then state/SID
Can be used to keep the object state - like an accumulator.

3. For example, when I change the state in a `run` of a rule matched in SID scope then `s.acc += 1` is also scoped ? i.e. that is assuming in the current context `SID = 123` and `acc = 2` then in reality `{ "SID": 123, "acc": 3 }` will be posted  ?

4. A state is also durable ?

**Comment by jruizgit** [comment]
Hi, thanks for asking the question. Your understanding is correct. State is also durable. In the v0 version it has special handling. In the v2 version, it is just another fact that is modified after each dispatch.

**Comment by alonbg** [comment]
Thank you. closing issue.

**Comment by JonnyWaffles** [comment]
Bump to add sid to the documentation https://github.com/jruizgit/rules/blob/master/docs/py/reference.md.
