### ISSUE TITLE
JSON's property limit reached

### ISSUE THREAD

**Issue by alonbg** [jruizgit/rules#228]
Hi @jruizgit 

I increased
 ``` c
 #define MAX_OBJECT_PROPERTIES 255 // 128
``` 
in `state.h` and all is well again. 
Is that safe ? Any precautions should be considered ?

Thank you

**Comment by jruizgit** [comment]
Hi, thanks for asking the question. Yes it is OK to increase the number of properties. You should not see any functional regression.
