### ISSUE TITLE
which 'id' is available

### ISSUE THREAD

**Issue by ZoliveGit** [jruizgit/rules#23]
Hi, I try Durable Rules in python, I write a python script to make POST request
```
import requests
import json

url = 'http://127.0.0.1:5000/test/1'
payload = {'id':1, 'subject':'World'}
headers = {'content-type': 'application/json'}
r = requests.post(url, data=json.dumps(payload), headers=headers)
print('ok' if r.status_code == 200 else 'Nok')
```
I use the "Example 1" script, it's work well (I got the "Hello World") but just 1 time, i see that the 'id' must be unique for each request.

So if I use separte scripts who make the same request how can i know which 'id' was not used before ?

Thanks for your reply,

Sorry for my english (i'm french)

**Comment by jruizgit** [comment]
Hi, thank you for posting the question. The post http API is idempotent (complying with http API definition best practices). That is, the API will return the same response for the same request. While this enables replay in at-least-once processing scenarios, it requires the caller to keep track of the ids used. 

Would you mind describing your scenario?

Thanks,

**Comment by ZoliveGit** [comment]
Thank's for your reply,

Yes i can keep track of the id because i will just use one client who send request to 'durable rules'. But, if i use more than one client, i have to centralize the id number for all the clients or maybe reserved id for each client. Because if Client1 send request with 'id'=10, and then Client2 send request with the same 'id'=10, durable rules will execute only the request of Client1 it's true ?

**Comment by jruizgit** [comment]
Yes, that is correct. Only the first request with id=10 will execute. 

Let me work on improving the API, so you don't need to keep track of the id on the caller side. durable_rules keeps a look aside table, there should be no need to keep two.

**Comment by ZoliveGit** [comment]
Ok, thank's for your work
