### ISSUE TITLE
Nested 'none' causes exception (Python)

### ISSUE THREAD

**Issue by valentin-khomutenko** [jruizgit/rules#233]
Hi!
The following code causes an exception. The idea behind it is that I have vulnerabilities with a set of tests for each of them. The function must fire if every test related to particular vulnerability is passed. Is that a bug or technical limitation of Rete Algorithm?

```python
from durable.lang import *

with ruleset('vulners'):
    @when_all(
        c.vulner << m.t == 'vulner',
        none(
            c.test << (m.t == 'test') & (m.vulner == c.vulner.id_),
            none((m.subject == c.test.id_) & (m.predicate=='passed'))
        )
    )
    def vulnerable(c):
        pass

run_all()
```

```python
...
File ".../venv/lib/python3.6/site-packages/durable/lang.py", line 419, in define
    new_definition['r_{0}'.format(index)] = rule.define()
File ".../venv/lib/python3.6/site-packages/durable/lang.py", line 311, in define
    new_expression = {'{0}$not'.format(name): current_expression.define()['none'][0]['m']}
KeyError: 'm'
```

**Comment by alonbg** [comment]
Hi @valentin-khomutenko,
 logically if a fact does not exist , it can't be aliased (i.e. `none ( c.test << ..`)
You might be looking for the following rule:

```python
from durable.lang import *

with ruleset('vulners'):
    @when_all(
        c.vulner << m.t == 'vulner',
        c.test << (m.t == 'test') & (m.vulner == c.vulner.id_),
        none((m.subject == c.test.id_) & (m.predicate == 'passed'))
    )
    def vulnerable(c):
        pass

run_all()
```

**Comment by valentin-khomutenko** [comment]
> Hi @valentin-khomutenko,
> logically if a fact does not exist , it can't be aliased (i.e. `none ( c.test << ..`)
> You might be looking for the following rule:
> 
> ```python
> from durable.lang import *
> 
> with ruleset('vulners'):
>     @when_all(
>         c.vulner << m.t == 'vulner',
>         c.test << (m.t == 'test') & (m.vulner == c.vulner.id_),
>         none((m.subject == c.test.id_) & (m.predicate == 'passed'))
>     )
>     def vulnerable(c):
>         pass
> 
> run_all()
> ```

Hi @alonbg ,
I understand what you mean, aliasing missing fact actually does not make sense. :/
However, the rule you provided does quite the opposite: the function fires if there is at least one test that is not passed while I need to catch the situation when all existing tests related to some vulnerability are passed.

**Comment by alonbg** [comment]
That's 2 or 3 facts you are checking ? ('test', 'vulner' ..)

**Comment by valentin-khomutenko** [comment]
@alonbg
Only 2 at the moment, I wonder if it can be done without adding extra ones.

**Comment by alonbg** [comment]
@valentin-khomutenko You might be able to do without `test_passed`.
initial state:
`t : { 't' : 'test', 'id_': (id), 'vulner': (vulner.id_)`
 .... later on retract and reassert `test`:
`test : { 't' : 'test', 'id_': (id), 'vulner': (vulner.id_), 'predicate': 'passed'/'failed'`
```python
from durable.lang import *

with ruleset('vulners'):
    @when_all(
        c.vulner << m.t == 'vulner',
       none((m.t == 'test') & (m.vulner == c.vulner.id_) &  (m.predicate == 'passed'))
     )       
     def vulnerable(c):
        pass

run_all()
```

**Comment by valentin-khomutenko** [comment]
@alonbg 
This one will work, I guess.
Thank you!
