### ISSUE TITLE
Shutdown system programmatically

### ISSUE THREAD

**Issue by valentin-khomutenko** [jruizgit/rules#235]
Hello,

I wonder if there is a way to shutdown running server programmatically as a reaction to a fact? 

For example:
```python
@when_all(
    m.t == 'all_work_done'
)
def shutdown(c):
   # somehow stop running server
```

**Comment by jruizgit** [comment]
Hi, currently there is no way to stop the server, other than shutting down the process, which would cause an ongoing action to fail. I can see how this feature is necessary for safe updates. I will consider it in the v2 version (currently under development in a different branch).
