### ISSUE TITLE
Different between Facts and Events 

### ISSUE THREAD

**Issue by shinrairis** [jruizgit/rules#24]
First of all, I would like to thank you for your great effort on developing this amazing framework. I am planning to use this in my own project.

I have tried the fraud detection example as below
```python
from durable.lang import *
with ruleset('fraud_detection'):

    @when_all(c.first << m.amount > 100,
              c.second << m.amount > c.first.amount * 2,
              c.third << m.amount > (c.first.amount + c.second.amount) / 2)
    def detected(c): 
        print('fraud detected -> {0} {1}'.format(c.first.amount, c.first.id))
        print('               -> {0} {1}'.format(c.second.amount, c.second.id))
        print('               -> {0} {1}'.format(c.third.amount, c.third.id))

    @when_start
    def start(host):
        sid = 18
        host.post('fraud_detection', {'id': 30, 'sid': sid, 'amount': 120})
        host.post('fraud_detection', {'id': 50, 'sid': sid, 'amount': 1000})

run_all()
```
It works as I expected with the following output
```
fraud detected -> 120 30
               -> 1000 50
               -> 1000 50
```
As far as I know, the difference between facts and events is the life cycle. Each event will only trigger one single action and be retracted automatically after action dispatched, while facts will stay in the same inference set until someone manually retract them. Therefore, I am expecting to see the same result as above even if I assert facts instead of posting events. 

I change the source code to this
```python
from durable.lang import *
with ruleset('fraud_detection'):

    @when_all(c.first << m.amount > 100,
              c.second << m.amount > c.first.amount * 2,
              c.third << m.amount > (c.first.amount + c.second.amount) / 2)
    def detected(c): 
        print('fraud detected -> {0} {1}'.format(c.first.amount, c.first.id))
        print('               -> {0} {1}'.format(c.second.amount, c.second.id))
        print('               -> {0} {1}'.format(c.third.amount, c.third.id))

    @when_start
    def start(host):
        sid = 18
        host.assert_fact('fraud_detection', {'id': 30, 'sid': sid, 'amount': 120})
        host.assert_fact('fraud_detection', {'id': 50, 'sid': sid, 'amount': 1000})

run_all()
```
In this case, there is no output at all. 
Could you please share some light on this case if I misunderstand anything.

**Comment by jruizgit** [comment]
Hi, thanks a lot for your feedback. Yes, your understanding of the difference between events and facts is correct. First glance your scenario should work. Let me test it and I will report back.

**Comment by jruizgit** [comment]
Hi, I just finished debugging your scenario. There was a bug in the code: when the facts asserted resolved into an action, the action queue was not being updated. I just pushed a fix and uploaded new versions of the library to npm, pip and gem.

**Comment by shinrairis** [comment]
Thanks for your quick response.
