### ISSUE TITLE
Exception has occurred: NameError name 'assert_fact' is not defined

### ISSUE THREAD

**Issue by krtzer** [jruizgit/rules#241]
I am trying to run the durable_rules examples in the documentation, but whenever I get to the assert_fact () line I get the following error:

```
Exception has occurred: NameError
name 'assert_fact' is not defined
  File "<path>\durable_rules_examples.py", line 26, in <module>
    assert_fact('animal', { 'subject': 'Kermit', 'predicate': 'eats', 'object': 'flies' })
```

I also get a similar error for the post() example in the documentation. I looked through the durable library files and did not see any signatures that matched these. Is there some service that I am expected to have running? 

One thought I had was that these were provided by the Redis instance, but I didn't see anything about that in the getting started documentation. 

System configuration:
Windows 10
Visual Studio Code
Python 3.6
pip freeze output: durable-rules==0.33.134

**Comment by jruizgit** [comment]
Hi, thanks for posting the question. The example only works with durable_rules version 2.0.x . Would you be able to upgrade to durable_rules 2.0.3?

**Comment by krtzer** [comment]
Hey thank you for the quick response. Yes, upgrading is possible and in the process of trying to upgrade,  I found there was an issue with my system. The path variable was polluted by something using Python 2.7.15. 

Steps: 

1. Open Windows Environment Variable dialog
2. Remove path to Python 2.7.15
3. Close and reopen VS Code
4. Open the terminal tab and verify python version with `python --version`
5. Uninstall durable-rules with `pip uninstall durable-rules`
6. Reinstall durable-rules with `pip install durable-rules`
7. Verify version 2.0.3 was installed:
`Collecting durable-rules
  Downloading https://files.pythonhosted.org/packages/2c/13/49d1fcc6d49e8aa9cf6d5adc2d9be73c7e59a744efef67a72ea7a2bfe2d2/durable_rules-2.0.3.tar.gz (53kB)`
