### ISSUE TITLE
setRuleset in durableEngine refers to rulesetName

### ISSUE THREAD

**Issue by mrehse** [jruizgit/rules#249]
Attempting to use durableEngine in a NodeJS project, and found that loading rules using setRuleset throws a ReferenceError. When calling saveRulesets on line 809, it references rulesetName, which isn't in the method signature or directly defined anywhere that would be accessible to the method.

Was this meant to loop over the ruleset names returned by registerRulesets? Was it considered to be no big deal since saveRuleset is apparently just a hook at the moment? Have I missed something important when creating my implementation?

**Comment by jruizgit** [comment]
Hi, thanks for reporting this issue. I have pushed a fix. Please use version 2.0.8. The following code works now as expected:

```javascript
d.getHost().setRulesets({ risk: {
    suspect: {
        run: function(c) { console.log('fraud'); },
        all: [
            {first: {t: 'purchase'}},
            {second: {$neq: {location: {first: 'location'}}}}
        ],
    }
}}, function(err){});

d.post('risk', {t: 'purchase', location: 'US'});
d.post('risk', {t: 'purchase', location: 'CA'});
```

**Comment by mrehse** [comment]
Thanks! Works as expected.
