### ISSUE TITLE
How do you run the server to use/test the JSON format?

### ISSUE THREAD

**Issue by sureshvv** [jruizgit/rules#259]
I looked at the JSON documentation but could not understand how to run the server that will process the rules.

**Comment by sureshvv** [comment]
Please feel free to answer on stackoverflow where I have created a new tag - durable-rules.

**Comment by jruizgit** [comment]
Hi, thanks for asking the question. The JSON doc is outdated. durable_rules V2, no longer starts an http server. You can provide a JSON document as follows:

```python
from durable.lang import *

def callback(c):
	print('risk7 fraud detected')

get_host().set_rulesets({ 'risk7': {
    'suspect': {
        'run': callback,
        'all': [
            {'first': {'t': 'purchase'}},
            {'second': {'$neq': {'location': {'first': 'location'}}}}
        ],
    }
}})

post('risk7', {'t': 'purchase', 'location': 'US'});
post('risk7', {'t': 'purchase', 'location': 'CA'});
```
