### ISSUE TITLE
node-gyp build fails after updating to node version 6.3.1

### ISSUE THREAD

**Issue by Thylossus** [jruizgit/rules#26]
Hi,

I've recently updated my node version to 6.3.1 and now I cannot build durable_rules anymore. Before the update I had no issues.

* node v6.3.1
* npm v3.10.6
* node-gyp v3.4.0

I think the main issue is this:

```
..\src\rulesjs\rules.cc(1031): error C2872: 'Proxy': ambiguous symbol [C:\Users\myuser\Downloads\node_modules\durable\build\rulesjs.vcxproj]
  ..\src\rulesjs\rules.cc(9): note: could be 'Proxy'
  c:\users\myuser\.node-gyp\6.3.1\include\node\v8.h(3396): note: or       'v8::Proxy' (compiling source file ..\src\rulesjs\rules.cc)
```

I assume that this a naming conflict. My old node version (5.0.0) did not support [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) class, but node 6.3.1 does.

The naming conflict arises at https://github.com/jruizgit/rules/blob/master/src/rulesjs/rules.cc#L9 where your `Proxy` class is defined also using the `v8` namespace.

Based on your [package.json](https://github.com/jruizgit/rules/blob/master/package.json#L12), I guess node 6.x.x is not supported yet. However, I would greatly appreciate being able to use node version 6.x.x as I need the [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) class.

Remark:
To verify my assumption regarding the issue's cause, I cloned your repository, renamed `Proxy` in https://github.com/jruizgit/rules/blob/master/src/rulesjs/rules.cc, and ran `npm install` which includes the node-gyp build. The node-gyp build then worked like a charm.

Best regards,

Tobias

**Comment by jruizgit** [comment]
Hi, thanks a lot for reporting this. I will work on integrating and testing the new version of node.

**Comment by Thylossus** [comment]
Great, thank you very much.

**Comment by jruizgit** [comment]
Hi, I have fixed the name collision and published a new package to npm. I left engine.node in the package.json file as "4.4.x", as this is still the recommended version form nodejs.org and the field is just advisory.

Thanks a lot for reporting the issue.

**Comment by Thylossus** [comment]
Hi, thank you for fixing this. Installing the dependency works great again.
Keeping the recommended node version at 4.4.x is absolutely reasonable as it is the LTS version.
