### ISSUE TITLE
Ruby - Rule and Timer Dispatcher Questions / Issues ?

### ISSUE THREAD

**Issue by balawa** [jruizgit/rules#27]
Hi:

First of all, I would like to thank you for this very good piece of software.
I have been looking over the last couple of days at your Ruby implementation of the Engine.

While comparing the code to the Python and JS implementation, there is a significant difference in the management of the Rule & Timer dispatchers.

In both JS and Python, it seems you have create 2 threads that Poll every 250ms including the ability to dispatch immediately, While in Ruby it seems that there is only 1 timer thread created that poll every 10ms and dispatch Timer at every 5 iterations while dispatching Rule at all other 4 occasions.

Is there any reason, why you have not use the same principle as Python/JS and create 2 Threads with 250ms poll interval because as I read the previous discussion too high poll interval could stall the engine if each rule action take some time.

**Comment by jruizgit** [comment]
Hi, thanks a lot for posting the question. Yes, in the case of Python/JS, the timer implementation will backoff when no action is available. I have not finished the Ruby implementation. There is no technical blocker. 

I'll post back on this issue as soon as I finish it.

**Comment by balawa** [comment]
Thank ! And I am happy to look into it as well.
Do you maintain a list of the features implemented between the different platform ? This could help other contributors maintain part of the code or giving you an hand testing/upgrading functionalities.

**Comment by jruizgit** [comment]
Hi, thanks for looking into this. Just send me a pull request when ready. I recommend you to use the Python implementation as reference. Python's an Ruby's threading models are similar.

I'm planning to open an issue for each item I have in my TODO list. I will pretend the title with TODO. Would this work for you?

For Ruby to be in sync with Python and node, there are only a couple of things: 1. Timer back off 2. Dynamic rule test.

**Comment by balawa** [comment]
Perfect !

**Comment by jruizgit** [comment]
Hi, I have merged the pull request and uploaded a new version to the gem repository. Thanks a lot for your contribution.

**Comment by balawa** [comment]
you are welcome.
