### ISSUE TITLE
Nested event properties

### ISSUE THREAD

**Issue by Thylossus** [jruizgit/rules#28]
Hi,

is it possible to define conditions for nested properties of an event? For example:

**Event:**
```json
{
  "id": "some id",
  "sid": "some sid",
  "content": {
    "id": "some external id",
    "sid": "some external sid",
    "value": 10
  }
}
```

**Rule:**
```javascript
{
    whenAll: m.content.value.lt(20),
    run: function (c) {
        console.log(`Value of ${c.m.content.id} is less than 20.`);
    }
}
```

The rule throws a runtime error because `m.content.value` is undefined. This is probably caused by the proxy. I could not find an example with nested properties. Hence, I assume that it is not supported.

I can work around this issue by flattening the JSON object before posting it to the rule engine, but before I do this I wanted to verify whether it is necessary to do so or if there is a more elegant solution built into durable_rules.

Best regards,

Tobias

**Comment by jruizgit** [comment]
Hi Tobias, the underpinnings for enabling queries on nested objects are implemented. I have not surfaced the functionality through the language abstractions. I will add this to the queue of items to complete.

Thanks for posting the question.

**Comment by Thylossus** [comment]
This is great news! Thank you for always replying so fast.

**Comment by jruizgit** [comment]
Hi Tobias, reporting back on this. Nested event queries are supported now. 

https://github.com/jruizgit/rules/issues/32

The changes were a little involved: Internally the engine flattens the JSON object creating nested names. The events need to be reconstructed when dispatching them to actions.

**Comment by Thylossus** [comment]
Hi Jesus, thank you for implementing this feature. Superb job. I'm closing this issue.
