### ISSUE TITLE
Infinite loop with sid only rule

### ISSUE THREAD

**Issue by hea-lab** [jruizgit/rules#288]
When trying to write the most simple rule, I found an issue with the following:

```
d.ruleset('test', function() {
        whenAll: +m.sid
        run: console.log("ok", JSON.stringify(m))
});
d.post('test',{sid: 8});
```
The associated action is fired forever.

we also have a infinite loop with the following code

```
d.ruleset('test', function() {
        whenAll: ~m.sid
        run: console.log("ok", JSON.stringify(m))
});
d.post('test',{});
```

**Comment by jruizgit** [comment]
Hi thanks for posting the question. Every time the rule engine executes an action successfully, it re-asserts the context state as a fact (such that you can write rules on the context state). The new fact will have a `sid` property. I'm surprised about the second case though, in theory it should never fire.

**Comment by hea-lab** [comment]
Thanks for your answer and I missed the context state reassertion. So it makes sense.
And also my bad for the second example, please don't consider it.
