### ISSUE TITLE
Can I maintain event sequence based on a given timestamp?

### ISSUE THREAD

**Issue by shinrairis** [jruizgit/rules#29]
Hi,

I would like to know that is it possible that durable_rules processes events in the same sequence as they are posted from the client if I have only one local client which can attach an strictly incremental timestamp to each event.

I try to approach this with the following code, but no luck.

``` python
from durable.lang import *

gid = 0

with ruleset('fraud_detection'):
    @when_all(m.time == gid + 1)
    def detected(c):
        global gid
        gid = gid + 1
        print ('purchase from {0}'.format(c.m.location))

    @when_start
    def start(host):
        host.post('fraud_detection', {'id': 1, 'sid': 10, 't': 'purchase', 'location': 'US', 'time': 1})
        host.post('fraud_detection', {'id': 2, 'sid': 10, 't': 'purchase', 'location': 'CA', 'time': 3})
         host.post('fraud_detection', {'id': 3, 'sid': 10, 't': 'purchase', 'location': 'TW', 'time': 2})

run_all()
```

I am expecting the result would be

```
purchase from US 
purchase from TW 
purchase from CA
```

However, the actual result is

```
purchase from US
```

I really appreciate any help you can provide.
Thanks

**Comment by jruizgit** [comment]
Yes, if you can guarantee the monotonic sequence increase in the client I can think of a couple of ways:

1. Assert facts, write a rule to define the relation between two facts, retract the oldest fact when an action is triggered. 
2. Post events, use the ruleset context to store the latest observed id, write a rule to define the relation between id and context state.

Hope this helps. It sounds like fun. I'll play with this as soon as I get a chance.

**Comment by shinrairis** [comment]
Hi,

Thanks for your quick reply.
I have been trying this for the entire morning, but I am not quite sure how to define the relation between id and context state with event posting. 
I have stored the latest observed id in context state and write a rule to trigger action only if the event id equals the latest observed id plus 1

```python
from durable.lang import *
 
 with ruleset('fraud_detection'):
     @when_all(m.time == c.s.latest_id + 1)
     def detected(c):
         print ('purchase from {0}'.format(c.m.location))
         c.s.latest_id = c.s.latest_id + 1
 
     @when_start
     def start(host):
         host.patch_state('fraud_detection', {'sid': 10, 'latest_id': 0})
         host.post('fraud_detection', {'id': 1, 'sid': 10, 't': 'purchase', 'location': 'US', 'time': 1})
         host.post('fraud_detection', {'id': 2, 'sid': 10, 't': 'purchase', 'location': 'CA', 'time': 3})
         host.post('fraud_detection', {'id': 3, 'sid': 10, 't': 'purchase', 'location': 'TW', 'time': 2})

 run_all()
```
Also, I am wondering if it is possible for a client to assert facts by sending requests to URL like "http://127.0.0.1/fraud_detection/10". For what I have learned from the source code, it seems like a client can only post events and patch states via HTTP POST and PATCH.

Thanks again for your help.

**Comment by jruizgit** [comment]
You are pretty close. These couple of rules worked for me:

```python
from durable.lang import *

with ruleset('fraud_detection'):
    @when_all(c.first << +s.last,
              c.second << m.time == c.first.last + 1)
    def detected(c):
        c.s.last = c.second.time
        print('fraud_detection: {0}'.format(c.second.location))

    @when_start
    def start(host):
        host.patch_state('fraud_detection', {'sid': 10, 'last': 0})
        host.post('fraud_detection', {'id': 1, 'sid': 10, 't': 'purchase', 'location': 'US', 'time': 1})
        host.post('fraud_detection', {'id': 2, 'sid': 10, 't': 'purchase', 'location': 'CA', 'time': 3})
        host.post('fraud_detection', {'id': 3, 'sid': 10, 't': 'purchase', 'location': 'TW', 'time': 2})

with ruleset('fraud_detection2'):
    @when_all(c.first << +m.time,
              c.second << m.time == c.first.time + 1)
    def detected(c):
        print('fraud_detection2: {0}, {1}'.format(c.first.location, c.second.location))
        c.retract_fact(c.first)

    @when_start
    def start(host):
        host.assert_fact('fraud_detection2', {'id': 1, 'sid': 10, 't': 'purchase', 'location': 'US', 'time': 1})
        host.assert_fact('fraud_detection2', {'id': 2, 'sid': 10, 't': 'purchase', 'location': 'CA', 'time': 3})
        host.assert_fact('fraud_detection2', {'id': 3, 'sid': 10, 't': 'purchase', 'location': 'TW', 'time': 2})

run_all()
```

The reason why the rule you attached doesn't quite work is because the state rvalue is not loaded in the client for every rule evaluation. It will eventually expire and be reloaded.

**Comment by shinrairis** [comment]
Thanks for your quick reply.

I wrote these rules to test your solution to see if it works and fits my use case.
However, it does not work as excepted.

```python
import redis
from durable.lang import *

with ruleset('test'):
	@when_all(c.first << +s.last,
			  c.second << (m.id == c.first.last + 1) & (m.action == 'open'))
	def open(c):
		c.s.last = c.second.id
		print('open path {0} action = {1}'.format(c.second.path, c.second.action))

	@when_all(c.first << +s.last,
			  c.second << (m.id == c.first.last + 1) & ((m.action == 'read') | (m.action == 'write')))
	def access(c):
		c.s.last = c.second.id
		print('access path {0} action = {1}'.format(c.second.path, c.second.action))


	@when_start
	def start_test(host):
		host.patch_state('test', {'sid': 1, 'last': 0})
		host.post('test', {'id': 3, 'sid': 1, 'action': 'open', 'path':'test3'})
		host.post('test', {'id': 2, 'sid': 1, 'action': 'open', 'path':'test2'})
		host.post('test', {'id': 1, 'sid': 1, 'action': 'open', 'path':'test1'})

if __name__ == "__main__":
	redis.StrictRedis().flushall()
	run_all()
```
The actual outputs are 
```
access path test1 action = open
open path test2 action = open
open path test3 action = open
```
As you can see, the event(id = 1, action = "open") triggers the "access" rule which should only be triggered by events with action = "read" or "write".

If I rewrite the "access" rule into two different rules, it works as expected.
```python
@when_all(c.first << +s.last,
		  c.second << (m.id == c.first.last + 1) & (m.action == 'write'))
def daware_access(c):
	c.s.last = c.second.id
	print('access path {0} action = {1}'.format(c.second.path, c.second.action))

@when_all(c.first << +s.last,
		  c.second << (m.id == c.first.last + 1) & (m.action == 'read'))
def daware_access(c):
	c.s.last = c.second.id
	print('access path {0} action = {1}'.format(c.second.path, c.second.action))
```
The output would be like the following which is correct.
```
open path test1 action = open
open path test2 action = open
open path test3 action = open
```

**Comment by jruizgit** [comment]
Hi, thanks for reporting the problem. There seems to be a bug in the construction of the tree for the expression: `(m.id == c.first.last + 1) & ((m.action == 'read') | (m.action == 'write'))`. The alpha node filtering is not being applied, so all messages match. Let me debug a little more and I will post my findings back.

**Comment by jruizgit** [comment]
Quick update: I have a fix ready for this problem. I just need to finish adding more tests.

**Comment by jruizgit** [comment]
Hi, reporting back on this issue. I have fixed the code an published a new build to npm, gem and pypi.

The alpha tree for nested 'or' was not being constructed correctly. To ensure the modularity of the constructs in the 'or' case there is a single forward node joining all the branches.
