### ISSUE TITLE
NameError: name 'ruleset' is not defined

### ISSUE THREAD

**Issue by jwheat** [jruizgit/rules#290]
I have an odd issue, that I couldn't find anyone else has, I'm guessing it may be some windows issue (of course).  

After `pip install durable_rules`, copying and pasting the hello world example, I'm getting the following error

```
Traceback (most recent call last):
  File "rules.py", line 1, in <module>
    from durable.lang import *
  File "C:\Users\Jonathan\AppData\Local\Programs\Python\Python36\lib\site-packages\durable\lang.py", line 1, in <module>
    from . import engine
  File "C:\Users\Jonathan\AppData\Local\Programs\Python\Python36\lib\site-packages\durable\engine.py", line 3, in <module>
    import rules
  File "D:\Code\Playground\Rules\rules.py", line 2, in <module>
    with ruleset('test'):
NameError: name 'ruleset' is not defined
```

Did I miss something or is there more I have to install / configure?

I'm on Windows 10 with Python 3.6.7
I've verified that durable_rules is installed (for my own sanity): with `pip list`
and see `durable-rules            2.0.15`

Any ideas what I may have done wrong?

**Comment by bereal** [comment]
Same here, Python 3.7.3, Ubuntu, `durable-rules 2.0.15`.

**Comment by jruizgit** [comment]
Thanks for reporting this issue. The rules engine C external module was called rules (which conflicts with other modules named rules). I have renamed the external module to durable_rules_engine, so it doesn't collide. Please use version 2.0.16

**Comment by jwheat** [comment]
renaming like @bereal mentioned worked
Then I updated like @jruizgit said, and I renamed the file back to rules.py and it worked.
Thanks
