### ISSUE TITLE
Loading multiple rulesets from a JSON file does not work (via set_rulesets())

### ISSUE THREAD

**Issue by ruslanolkhovsky** [jruizgit/rules#294]
Hello,

While uploading the rules from JSON file using the set_rulesets() method I have found that it works fine for one ruleset. However, using several rulesets in one JSON file does not work, the engine uploads just the first one, and the others are ignored.  

The jSON format is like this:

{
  "ruleset1": {
  ...
  }, 
  "ruleset2": {
  ...
  }
}

The method to load:
get_host().set_rulesets(json)

I am wondering if I am using the correct formatting. Or maybe we can use the set_rulsets(json) several times... I tried that option too, no success. Please, advise.

Thank you!
Ruslan

**Comment by jruizgit** [comment]
Hi Ruslan, I see you closed this issue. Just curious, did you get the scenario to work?

**Comment by ruslanolkhovsky** [comment]
Hi Jesus,

Thanks for asking. Yes, I managed to load several rulesets from a JSON file using the approach with Redis described here https://github.com/jruizgit/rules/issues/148. 
Now I am fighting to make the flow to trigger an action... it runs the first trigger, calls the run method and then stops, does not continues to the "to" steps. Must be wrong formatting or smth else.

Best,
Ruslan

**Comment by ruslanolkhovsky** [comment]
Here is the ruleset:

{
  "example$flow": {
    "start": {
      "to": {
        "set1": {
          "all": [
            {
              "m": {
                "param": 1
              }
            }
          ]
        }
      }
    },
    "set1": {
      "run": "set1_method",
      "to": {
        "set2": {
          "all": [
            {
              "m": {
                "$neq": {
                  "id": 0
                }
              }
            }
          ]
        }
      }
    },
    "set2": {
      "run": "set2_method",
      "to": "set3"
    },
    "set3": {
      "run": "set3_method",
      "to": {}
    }
  }
}

As for me, it looks fine. 

It is called by regular:

post('example', m)

The set1_method works fine, then by the condition (id != 0) it should follow to the set 2 and then to the set 3... but it does not. Any advice is very much appreciated.

Thank you

**Comment by ruslanolkhovsky** [comment]
Solved by running several iterations of the post method until the status received is None.
