### ISSUE TITLE
Custom parameters to the run method

### ISSUE THREAD

**Issue by ruslanolkhovsky** [jruizgit/rules#296]
Hello. Is there any way to pass parameters or custom arguments to the run methods? Is it possible to specify such custom parameters in the conditions in JSON? 

The run methods have one arguments - c object, which has the data of the c.m and the c.s. 
It would great to have an option to pass custom parameters based on the conditions in json, smth like the following (see "params" for the method "run")

"r01": {
  "run": "method1",
  "params": {
    "param1": 1,
    "param2": 2
  },
  "to": {
    "r02": {
      "all": [
        {
          "m": {
            "$and": [
              {
                "type": 1
              },
              {
                "number": 0
              }
            ]
          }
        }
      ]
    }
  }

Please, advice. Thank you.

**Comment by jruizgit** [comment]
Hi, thanks for asking the question. Passing custom parameters is not supported. The facts/events that lead to the action execution as well as the context object can be retrieved using the 'c' parameter. For example (assuming you are using python):

```python
with ruleset('risk1'):
    @when_all(c.first << m.t == 'deposit',
              none(m.t == 'balance'),
              c.third << m.t == 'withdrawal',
              c.fourth << m.t == 'chargeback')
    def detected(c):
        print('risk1-> fraud detected {0} {1} {2}'.format(c.first.t, c.third.t, c.fourth.t))
        
post('risk1', { 't': 'deposit' })
post('risk1', { 't': 'withdrawal' })
post('risk1', { 't': 'chargeback' })
```

**Comment by ruslanolkhovsky** [comment]
Hi, thank you for replying. It is a pity the custom parameters are not supported, might be a very useful feature. Do you have any thoughts/recommendations of how the rules can be extended with it?

**Comment by ruslanolkhovsky** [comment]
I have found a simple way to pass parameters to the action methods. Basically, I use the action_name label in the format "method_name|parameter". Then parse the action_name and call the "method_name(c, parameter)". The parameter could be a json base64 encoded. Works fine.

**Comment by dcrespol** [comment]
@ruslanolkhovsky would you mind sharing your workaround on how to pass parameters? Thank you!

**Comment by ruslanolkhovsky** [comment]
Hi @dcrespol 

Sure. The idea is to use the action_name label for both the method name and parameters. You need to redefine the get_action() method of the Host object, and do not forget to pass the parameter to the methods to call.

```
    from durable.lang import *

    from . import actions

    class Host(engine.Host):

        def __init__(self):
            super(Host, self).__init__()


        def get_action(self, action_name):

            def call(c):
                # Parse parameters
                delimiter = '|'

                if delimiter not in action_name:    # methods without parameters
                    action_method = action_name
                    p = None
                else:                               # methods with parameters
                    action_method = action_name.split(delimiter)[0]
                    p = action_name.split(delimiter)[1]

                    # The p is a string, you can use base64 encode/decode here 
                    # to get the params in a form of json like {p1: value1, p2: value2}
                    # or in any other format you prefer

                c.s.label = action_method

                # Get the method to call
                # The actions is a module with methods that you can call
                # 
                # def method1(c, p):
                #     print('method1 with params {}'.format(p))
                #     return 
                # 
                # def method2(c, p):
                #     print('method2 with params {}'.format(p)) 
                #     return 
                # 
         
                run = getattr(actions, action_method)

                # Call the method
                run(c, p)

            return call
```

I hope it helps. Works like a charm for me.

**Comment by dcrespol** [comment]
Thank you, @ruslanolkhovsky. Works for me too!

**Comment by rdevivo74** [comment]
> Hi @dcrespol
> 
> Sure. The idea is to use the action_name label for both the method name and parameters. You need to redefine the get_action() method of the Host object, and do not forget to pass the parameter to the methods to call.
> 
> ```
>     from durable.lang import *
> 
>     from . import actions
> 
>     class Host(engine.Host):
> 
>         def __init__(self):
>             super(Host, self).__init__()
> 
> 
>         def get_action(self, action_name):
> 
>             def call(c):
>                 # Parse parameters
>                 delimiter = '|'
> 
>                 if delimiter not in action_name:    # methods without parameters
>                     action_method = action_name
>                     p = None
>                 else:                               # methods with parameters
>                     action_method = action_name.split(delimiter)[0]
>                     p = action_name.split(delimiter)[1]
> 
>                     # The p is a string, you can use base64 encode/decode here 
>                     # to get the params in a form of json like {p1: value1, p2: value2}
>                     # or in any other format you prefer
> 
>                 c.s.label = action_method
> 
>                 # Get the method to call
>                 # The actions is a module with methods that you can call
>                 # 
>                 # def method1(c, p):
>                 #     print('method1 with params {}'.format(p))
>                 #     return 
>                 # 
>                 # def method2(c, p):
>                 #     print('method2 with params {}'.format(p)) 
>                 #     return 
>                 # 
>          
>                 run = getattr(actions, action_method)
> 
>                 # Call the method
>                 run(c, p)
> 
>             return call
> ```
> 
> I hope it helps. Works like a charm for me.

Thank you very much to both of you! I was on a more complex path.
