### ISSUE TITLE
Missing run_all function on durable.lang

### ISSUE THREAD

**Issue by tonythomas01** [jruizgit/rules#298]
Was `run_all([{'host': host_name, 'port': port}])` removed from the codebase ? I am using `durable-rules==2.0.17` and see that 
```
from durable.lang import *
run_all([{'host': host_name, 'port': port}])
```

raises a NameError: name 'run_all' is not defined. If this is the case, what is the way to run the service at  a different port now ? Also, I could not find this on the latest version of durable.lang file - https://github.com/jruizgit/rules/blob/master/libpy/durable/lang.py

**Comment by jruizgit** [comment]
Hi Tony, durable_rules 2.0.x no longer requires redis. You don't need to call run_all and you can post events and assert facts without using the start method. To provide durability, please follow this example:

https://github.com/jruizgit/rules/blob/master/testpy/testdurable.py

**Comment by tonythomas01** [comment]
Aha. True. Closing this one then. Thank you!
