### ISSUE TITLE
durable_rules lambda aws

### ISSUE THREAD

**Issue by simplynd** [jruizgit/rules#299]
I have similar issue as #78.  

I am trying to build a serverless rule set using python Lambda and Durable_rules.  However it fails upon trying to import with following error. 
"Unable to import module 'lambda_function': No module named 'durable_rules_engine'"

I assume it's because durable_rules_engine is built in C and not available as python package. 
Let me know if you have any details related to this or any suggestion you can provide. 

Thanks

**Comment by jruizgit** [comment]
Yes, the durable_rules_engine is build in C. Let me try your scenario and will report back in a couple of days.

**Comment by simplynd** [comment]
Thanks. Let me provide some more details below. 

What I am doing is I have created a layer where I have durable_rules package. 
(https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html#configuration-layers-path)

My Lambda refers to this layer which allows me to import durable_rules module, but the main module fails to import dependent modules, specifically the rules_engine which is provided as .so file.

**Comment by simplynd** [comment]
Marking it as closed, as I manage to get it working.

**Comment by SumithSB** [comment]
> Marking it as closed, as I manage to get it working.

Hi can you please post the solution here , even I'm facing exactly similar issue and not able to resolve it
