### ISSUE TITLE
issues starting testdynamic.js

### ISSUE THREAD

**Issue by ss7gowda** [jruizgit/rules#311]
Hi,

Trying to get familiar with this framework, but struggling to go through the testjs examples.  Most are working, but I can't seem to get testdynamic.js started.

I'm doing the following:
- git clone
- python setup.py build
- npm install

When I try to run testdynamic.js, I get the following message:

var app = d.application(host);
            ^
TypeError: d.application is not a function

Is there a different procedure I should be following to get this started?

Thanks.

**Comment by jruizgit** [comment]
Hi, I'm sorry testdynamic is obsolete. It is supposed to show how to create a ruleset using JSON. This the simple example:

```javascript
d.getHost().setRulesets({ risk7: {
    suspect: {
        run: function(c) { console.log('risk7: fraud detected'); },
        all: [
            {first: {t: 'purchase'}},
            {second: {$neq: {location: {first: 'location'}}}}
        ],
    }
}}, function(err){});

d.post('risk7', {t: 'purchase', location: 'US'});
d.post('risk7', {t: 'purchase', location: 'CA'});
```

**Comment by ss7gowda** [comment]
Thanks for the response.  Closing ticket.
