### ISSUE TITLE
Simple array rules - (a & b) | (c & d)

### ISSUE THREAD

**Issue by viggyfresh** [jruizgit/rules#316]
Hi there! I was playing around with this library and was trying to get this basic toy example to work with arrays:

```
def toy_example():
    with ruleset("toy-example"):

        @when_any(
            (
                m.observations.anyItem(item.matches("a"))
                & m.observations.anyItem(item.matches("b"))
            ),
            (
                m.observations.anyItem(item.matches("c"))
                & m.observations.anyItem(item.matches("d"))
            ),
        )
        def match(c):
            print("Matched!")

    post("toy-example", {"observations": ["c", "d"]})
```

Per my understanding, `@when_any` will match when _any_ of the antecedents match, and here there are two: "a" & "b" or "c" & "d". Weirdly, if I post an observations list of "a" and "b", it prints "Matched!". If I pass "c" and "d"...no match, but also no error for an unmatched message.

I am likely missing something really obvious...but any help would be appreciated!

**Comment by jruizgit** [comment]
Thanks for posting the issue. I'm debugging this scenario and will report back in a couple of days.

**Comment by jruizgit** [comment]
Thanks again for reporting the issue. I have published a fix. Please use version 2.0.23.

**Comment by viggyfresh** [comment]
thanks a bunch! will close the issue.
