### ISSUE TITLE
Can not npm install durable

### ISSUE THREAD

**Issue by alxfed** [jruizgit/rules#318]
The response is:
<pre>
(jupy) alxfed@fedot:~/alxfed/jupy$ npm install durable

> durable@2.0.29 install /home/alxfed/alxfed/jupy/node_modules/durable
> node-gyp rebuild

make: Entering directory '/home/alxfed/alxfed/jupy/node_modules/durable/build'
  CC(target) Release/obj.target/rules/src/rules/json.o
  CC(target) Release/obj.target/rules/src/rules/rete.o
  CC(target) Release/obj.target/rules/src/rules/events.o
In file included from ../src/rules/events.c:11:0:
../src/rules/events.c: In function ‘reduceOperand’:
../src/rules/rules.h:71:31: warning: this statement may fall through [-Wimplicit-fallthrough=]
 #define CHECK_RESULT(func) do { \
                               ^
../src/rules/events.c:281:13: note: in expansion of macro ‘CHECK_RESULT’
             CHECK_RESULT(getMessageFromFrame(state,
             ^~~~~~~~~~~~
../src/rules/events.c:286:9: note: here
         case JSON_MESSAGE_IDENTIFIER:
         ^~~~
../src/rules/events.c: In function ‘handleDeleteMessage’:
../src/rules/events.c:1061:23: warning: ‘result’ may be used uninitialized in this function [-Wmaybe-uninitialized]
             } else if (result == RULES_OK) {
                       ^
  CC(target) Release/obj.target/rules/src/rules/state.o
../src/rules/state.c: In function ‘storeMessage’:
../src/rules/state.c:783:23: warning: ‘actionType’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         unsigned char actionType;
                       ^~~~~~~~~~
  CC(target) Release/obj.target/rules/src/rules/regex.o
../src/rules/regex.c: In function ‘utf8ToUnicode’:
../src/rules/regex.c:210:13: warning: this statement may fall through [-Wimplicit-fallthrough=]
             ++*first;
             ^~~~~~~~
../src/rules/regex.c:211:9: note: here
         case 2:
         ^~~~
../src/rules/regex.c:214:13: warning: this statement may fall through [-Wimplicit-fallthrough=]
             ++*first;
             ^~~~~~~~
../src/rules/regex.c:215:9: note: here
         case 1:
         ^~~~
../src/rules/regex.c:218:13: warning: this statement may fall through [-Wimplicit-fallthrough=]
             ++*first;
             ^~~~~~~~
../src/rules/regex.c:219:9: note: here
         case 0:
         ^~~~
  AR(target) Release/obj.target/src/rules/rules.a
  COPY Release/rules.a
  CXX(target) Release/obj.target/rulesjs/src/rulesjs/rules.o
../src/rulesjs/rules.cc: In function ‘void jsAssertEvent(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/rulesjs/rules.cc:15:115: error: ‘class v8::Maybe<bool>’ has no member named ‘Check’; did you mean ‘ToChecked’?
 value) array->Set(i->GetCurrentContext(), index, Number::New(i, value)).Check()
                                                                         ^
../src/rulesjs/rules.cc:94:13: note: in expansion of macro ‘ARRAY_SET_NUMBER’
             ARRAY_SET_NUMBER(isolate, array, 0, result);
             ^~~~~~~~~~~~~~~~
../src/rulesjs/rules.cc:15:115: error: ‘class v8::Maybe<bool>’ has no member named ‘Check’; did you mean ‘ToChecked’?
 value) array->Set(i->GetCurrentContext(), index, Number::New(i, value)).Check()
                                                                         ^
../src/rulesjs/rules.cc:95:13: note: in expansion of macro ‘ARRAY_SET_NUMBER’
             ARRAY_SET_NUMBER(isolate, array, 1, stateOffset);
             ^~~~~~~~~~~~~~~~
../src/rulesjs/rules.cc: In function ‘void jsAssertEvents(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/rulesjs/rules.cc:15:115: error: ‘class v8::Maybe<bool>’ has no member named ‘Check’; did you mean ‘ToChecked’?
 value) array->Set(i->GetCurrentContext(), index, Number::New(i, value)).Check()
                                                                         ^
../src/rulesjs/rules.cc:122:13: note: in expansion of macro ‘ARRAY_SET_NUMBER’
             ARRAY_SET_NUMBER(isolate, array, 0, result);
             ^~~~~~~~~~~~~~~~
../src/rulesjs/rules.cc:15:115: error: ‘class v8::Maybe<bool>’ has no member named ‘Check’; did you mean ‘ToChecked’?
 value) array->Set(i->GetCurrentContext(), index, Number::New(i, value)).Check()
                                                                         ^
../src/rulesjs/rules.cc:123:13: note: in expansion of macro ‘ARRAY_SET_NUMBER’
             ARRAY_SET_NUMBER(isolate, array, 1, stateOffset);
             ^~~~~~~~~~~~~~~~
../src/rulesjs/rules.cc: In function ‘void jsAssertFact(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/rulesjs/rules.cc:15:115: error: ‘class v8::Maybe<bool>’ has no member named ‘Check’; did you mean ‘ToChecked’?
 value) array->Set(i->GetCurrentContext(), index, Number::New(i, value)).Check()
                                                                         ^
../src/rulesjs/rules.cc:150:13: note: in expansion of macro ‘ARRAY_SET_NUMBER’
             ARRAY_SET_NUMBER(isolate, array, 0, result);
             ^~~~~~~~~~~~~~~~
../src/rulesjs/rules.cc:15:115: error: ‘class v8::Maybe<bool>’ has no member named ‘Check’; did you mean ‘ToChecked’?
 value) array->Set(i->GetCurrentContext(), index, Number::New(i, value)).Check()
                                                                         ^
../src/rulesjs/rules.cc:151:13: note: in expansion of macro ‘ARRAY_SET_NUMBER’
             ARRAY_SET_NUMBER(isolate, array, 1, stateOffset);
             ^~~~~~~~~~~~~~~~
../src/rulesjs/rules.cc: In function ‘void jsAssertFacts(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/rulesjs/rules.cc:15:115: error: ‘class v8::Maybe<bool>’ has no member named ‘Check’; did you mean ‘ToChecked’?
 value) array->Set(i->GetCurrentContext(), index, Number::New(i, value)).Check()
                                                                         ^
../src/rulesjs/rules.cc:178:13: note: in expansion of macro ‘ARRAY_SET_NUMBER’
             ARRAY_SET_NUMBER(isolate, array, 0, result);
             ^~~~~~~~~~~~~~~~
../src/rulesjs/rules.cc:15:115: error: ‘class v8::Maybe<bool>’ has no member named ‘Check’; did you mean ‘ToChecked’?
 value) array->Set(i->GetCurrentContext(), index, Number::New(i, value)).Check()
                                                                         ^
../src/rulesjs/rules.cc:179:13: note: in expansion of macro ‘ARRAY_SET_NUMBER’
             ARRAY_SET_NUMBER(isolate, array, 1, stateOffset);
             ^~~~~~~~~~~~~~~~
../src/rulesjs/rules.cc: In function ‘void jsRetractFact(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/rulesjs/rules.cc:15:115: error: ‘class v8::Maybe<bool>’ has no member named ‘Check’; did you mean ‘ToChecked’?
 value) array->Set(i->GetCurrentContext(), index, Number::New(i, value)).Check()
                                                                         ^
../src/rulesjs/rules.cc:206:13: note: in expansion of macro ‘ARRAY_SET_NUMBER’
             ARRAY_SET_NUMBER(isolate, array, 0, result);
             ^~~~~~~~~~~~~~~~
../src/rulesjs/rules.cc:15:115: error: ‘class v8::Maybe<bool>’ has no member named ‘Check’; did you mean ‘ToChecked’?
 value) array->Set(i->GetCurrentContext(), index, Number::New(i, value)).Check()
                                                                         ^
../src/rulesjs/rules.cc:207:13: note: in expansion of macro ‘ARRAY_SET_NUMBER’
             ARRAY_SET_NUMBER(isolate, array, 1, stateOffset);
             ^~~~~~~~~~~~~~~~
../src/rulesjs/rules.cc: In function ‘void jsRetractFacts(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/rulesjs/rules.cc:15:115: error: ‘class v8::Maybe<bool>’ has no member named ‘Check’; did you mean ‘ToChecked’?
 value) array->Set(i->GetCurrentContext(), index, Number::New(i, value)).Check()
                                                                         ^
../src/rulesjs/rules.cc:234:13: note: in expansion of macro ‘ARRAY_SET_NUMBER’
             ARRAY_SET_NUMBER(isolate, array, 0, result);
             ^~~~~~~~~~~~~~~~
../src/rulesjs/rules.cc:15:115: error: ‘class v8::Maybe<bool>’ has no member named ‘Check’; did you mean ‘ToChecked’?
 value) array->Set(i->GetCurrentContext(), index, Number::New(i, value)).Check()
                                                                         ^
../src/rulesjs/rules.cc:235:13: note: in expansion of macro ‘ARRAY_SET_NUMBER’
             ARRAY_SET_NUMBER(isolate, array, 1, stateOffset);
             ^~~~~~~~~~~~~~~~
../src/rulesjs/rules.cc: In function ‘void jsUpdateState(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/rulesjs/rules.cc:15:115: error: ‘class v8::Maybe<bool>’ has no member named ‘Check’; did you mean ‘ToChecked’?
 value) array->Set(i->GetCurrentContext(), index, Number::New(i, value)).Check()
                                                                         ^
../src/rulesjs/rules.cc:262:13: note: in expansion of macro ‘ARRAY_SET_NUMBER’
             ARRAY_SET_NUMBER(isolate, array, 0, result);
             ^~~~~~~~~~~~~~~~
../src/rulesjs/rules.cc:15:115: error: ‘class v8::Maybe<bool>’ has no member named ‘Check’; did you mean ‘ToChecked’?
 value) array->Set(i->GetCurrentContext(), index, Number::New(i, value)).Check()
                                                                         ^
../src/rulesjs/rules.cc:263:13: note: in expansion of macro ‘ARRAY_SET_NUMBER’
             ARRAY_SET_NUMBER(isolate, array, 1, stateOffset);
             ^~~~~~~~~~~~~~~~
../src/rulesjs/rules.cc: In function ‘void jsStartAction(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/rulesjs/rules.cc:17:168: error: ‘class v8::Maybe<bool>’ has no member named ‘Check’; did you mean ‘ToChecked’?
 ng::NewFromUtf8(i, value, v8::NewStringType::kNormal).ToLocalChecked()).Check()
                                                                         ^
../src/rulesjs/rules.cc:293:13: note: in expansion of macro ‘ARRAY_SET_STRING’
             ARRAY_SET_STRING(isolate, array, 0, session);
             ^~~~~~~~~~~~~~~~
../src/rulesjs/rules.cc:17:168: error: ‘class v8::Maybe<bool>’ has no member named ‘Check’; did you mean ‘ToChecked’?
 ng::NewFromUtf8(i, value, v8::NewStringType::kNormal).ToLocalChecked()).Check()
                                                                         ^
../src/rulesjs/rules.cc:294:13: note: in expansion of macro ‘ARRAY_SET_STRING’
             ARRAY_SET_STRING(isolate, array, 1, messages);
             ^~~~~~~~~~~~~~~~
../src/rulesjs/rules.cc:15:115: error: ‘class v8::Maybe<bool>’ has no member named ‘Check’; did you mean ‘ToChecked’?
 value) array->Set(i->GetCurrentContext(), index, Number::New(i, value)).Check()
                                                                         ^
../src/rulesjs/rules.cc:295:13: note: in expansion of macro ‘ARRAY_SET_NUMBER’
             ARRAY_SET_NUMBER(isolate, array, 2, stateOffset);
             ^~~~~~~~~~~~~~~~
../src/rulesjs/rules.cc: In function ‘void jsStartActionForState(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/rulesjs/rules.cc:17:168: error: ‘class v8::Maybe<bool>’ has no member named ‘Check’; did you mean ‘ToChecked’?
 ng::NewFromUtf8(i, value, v8::NewStringType::kNormal).ToLocalChecked()).Check()
                                                                         ^
../src/rulesjs/rules.cc:324:13: note: in expansion of macro ‘ARRAY_SET_STRING’
             ARRAY_SET_STRING(isolate, array, 0, session);
             ^~~~~~~~~~~~~~~~
../src/rulesjs/rules.cc:17:168: error: ‘class v8::Maybe<bool>’ has no member named ‘Check’; did you mean ‘ToChecked’?
 ng::NewFromUtf8(i, value, v8::NewStringType::kNormal).ToLocalChecked()).Check()
                                                                         ^
../src/rulesjs/rules.cc:325:13: note: in expansion of macro ‘ARRAY_SET_STRING’
             ARRAY_SET_STRING(isolate, array, 1, messages);
             ^~~~~~~~~~~~~~~~
../src/rulesjs/rules.cc: In function ‘void init(v8::Local<v8::Object>)’:
../src/rulesjs/rules.cc:21:241: error: ‘class v8::Maybe<bool>’ has no member named ‘Check’; did you mean ‘ToChecked’?
 te::New(i, func)->GetFunction(i->GetCurrentContext()).ToLocalChecked()).Check()
                                                                         ^
../src/rulesjs/rules.cc:825:5: note: in expansion of macro ‘DEFINE_FUNCTION’
     DEFINE_FUNCTION(exports, isolate, "createRuleset", jsCreateRuleset);
     ^~~~~~~~~~~~~~~
../src/rulesjs/rules.cc:21:241: error: ‘class v8::Maybe<bool>’ has no member named ‘Check’; did you mean ‘ToChecked’?
 te::New(i, func)->GetFunction(i->GetCurrentContext()).ToLocalChecked()).Check()
                                                                         ^
../src/rulesjs/rules.cc:827:5: note: in expansion of macro ‘DEFINE_FUNCTION’
     DEFINE_FUNCTION(exports, isolate, "deleteRuleset", jsDeleteRuleset);
     ^~~~~~~~~~~~~~~
../src/rulesjs/rules.cc:21:241: error: ‘class v8::Maybe<bool>’ has no member named ‘Check’; did you mean ‘ToChecked’?
 te::New(i, func)->GetFunction(i->GetCurrentContext()).ToLocalChecked()).Check()
                                                                         ^
../src/rulesjs/rules.cc:829:5: note: in expansion of macro ‘DEFINE_FUNCTION’
     DEFINE_FUNCTION(exports, isolate, "assertEvent", jsAssertEvent);
     ^~~~~~~~~~~~~~~
../src/rulesjs/rules.cc:21:241: error: ‘class v8::Maybe<bool>’ has no member named ‘Check’; did you mean ‘ToChecked’?
 te::New(i, func)->GetFunction(i->GetCurrentContext()).ToLocalChecked()).Check()
                                                                         ^
../src/rulesjs/rules.cc:831:5: note: in expansion of macro ‘DEFINE_FUNCTION’
     DEFINE_FUNCTION(exports, isolate, "assertEvents", jsAssertEvents);
     ^~~~~~~~~~~~~~~
../src/rulesjs/rules.cc:21:241: error: ‘class v8::Maybe<bool>’ has no member named ‘Check’; did you mean ‘ToChecked’?
 te::New(i, func)->GetFunction(i->GetCurrentContext()).ToLocalChecked()).Check()
                                                                         ^
../src/rulesjs/rules.cc:833:5: note: in expansion of macro ‘DEFINE_FUNCTION’
     DEFINE_FUNCTION(exports, isolate, "assertFact", jsAssertFact);
     ^~~~~~~~~~~~~~~
../src/rulesjs/rules.cc:21:241: error: ‘class v8::Maybe<bool>’ has no member named ‘Check’; did you mean ‘ToChecked’?
 te::New(i, func)->GetFunction(i->GetCurrentContext()).ToLocalChecked()).Check()
                                                                         ^
../src/rulesjs/rules.cc:835:5: note: in expansion of macro ‘DEFINE_FUNCTION’
     DEFINE_FUNCTION(exports, isolate, "assertFacts", jsAssertFacts);
     ^~~~~~~~~~~~~~~
../src/rulesjs/rules.cc:21:241: error: ‘class v8::Maybe<bool>’ has no member named ‘Check’; did you mean ‘ToChecked’?
 te::New(i, func)->GetFunction(i->GetCurrentContext()).ToLocalChecked()).Check()
                                                                         ^
../src/rulesjs/rules.cc:837:5: note: in expansion of macro ‘DEFINE_FUNCTION’
     DEFINE_FUNCTION(exports, isolate, "retractFact", jsRetractFact);
     ^~~~~~~~~~~~~~~
../src/rulesjs/rules.cc:21:241: error: ‘class v8::Maybe<bool>’ has no member named ‘Check’; did you mean ‘ToChecked’?
 te::New(i, func)->GetFunction(i->GetCurrentContext()).ToLocalChecked()).Check()
                                                                         ^
../src/rulesjs/rules.cc:839:5: note: in expansion of macro ‘DEFINE_FUNCTION’
     DEFINE_FUNCTION(exports, isolate, "retractFacts", jsRetractFacts);
     ^~~~~~~~~~~~~~~
../src/rulesjs/rules.cc:21:241: error: ‘class v8::Maybe<bool>’ has no member named ‘Check’; did you mean ‘ToChecked’?
 te::New(i, func)->GetFunction(i->GetCurrentContext()).ToLocalChecked()).Check()
                                                                         ^
../src/rulesjs/rules.cc:841:5: note: in expansion of macro ‘DEFINE_FUNCTION’
     DEFINE_FUNCTION(exports, isolate, "assertTimers", jsAssertTimers);
     ^~~~~~~~~~~~~~~
../src/rulesjs/rules.cc:21:241: error: ‘class v8::Maybe<bool>’ has no member named ‘Check’; did you mean ‘ToChecked’?
 te::New(i, func)->GetFunction(i->GetCurrentContext()).ToLocalChecked()).Check()
                                                                         ^
../src/rulesjs/rules.cc:843:5: note: in expansion of macro ‘DEFINE_FUNCTION’
     DEFINE_FUNCTION(exports, isolate, "updateState", jsUpdateState);
     ^~~~~~~~~~~~~~~
../src/rulesjs/rules.cc:21:241: error: ‘class v8::Maybe<bool>’ has no member named ‘Check’; did you mean ‘ToChecked’?
 te::New(i, func)->GetFunction(i->GetCurrentContext()).ToLocalChecked()).Check()
                                                                         ^
../src/rulesjs/rules.cc:845:5: note: in expansion of macro ‘DEFINE_FUNCTION’
     DEFINE_FUNCTION(exports, isolate, "startAction", jsStartAction);
     ^~~~~~~~~~~~~~~
../src/rulesjs/rules.cc:21:241: error: ‘class v8::Maybe<bool>’ has no member named ‘Check’; did you mean ‘ToChecked’?
 te::New(i, func)->GetFunction(i->GetCurrentContext()).ToLocalChecked()).Check()
                                                                         ^
../src/rulesjs/rules.cc:847:5: note: in expansion of macro ‘DEFINE_FUNCTION’
     DEFINE_FUNCTION(exports, isolate, "startActionForState", jsStartActionForState);
     ^~~~~~~~~~~~~~~
../src/rulesjs/rules.cc:21:241: error: ‘class v8::Maybe<bool>’ has no member named ‘Check’; did you mean ‘ToChecked’?
 te::New(i, func)->GetFunction(i->GetCurrentContext()).ToLocalChecked()).Check()
                                                                         ^
../src/rulesjs/rules.cc:849:5: note: in expansion of macro ‘DEFINE_FUNCTION’
     DEFINE_FUNCTION(exports, isolate, "completeAndStartAction", jsCompleteAndStartAction);
     ^~~~~~~~~~~~~~~
../src/rulesjs/rules.cc:21:241: error: ‘class v8::Maybe<bool>’ has no member named ‘Check’; did you mean ‘ToChecked’?
 te::New(i, func)->GetFunction(i->GetCurrentContext()).ToLocalChecked()).Check()
                                                                         ^
../src/rulesjs/rules.cc:851:5: note: in expansion of macro ‘DEFINE_FUNCTION’
     DEFINE_FUNCTION(exports, isolate, "abandonAction", jsAbandonAction);
     ^~~~~~~~~~~~~~~
../src/rulesjs/rules.cc:21:241: error: ‘class v8::Maybe<bool>’ has no member named ‘Check’; did you mean ‘ToChecked’?
 te::New(i, func)->GetFunction(i->GetCurrentContext()).ToLocalChecked()).Check()
                                                                         ^
../src/rulesjs/rules.cc:853:5: note: in expansion of macro ‘DEFINE_FUNCTION’
     DEFINE_FUNCTION(exports, isolate, "startTimer", jsStartTimer);
     ^~~~~~~~~~~~~~~
../src/rulesjs/rules.cc:21:241: error: ‘class v8::Maybe<bool>’ has no member named ‘Check’; did you mean ‘ToChecked’?
 te::New(i, func)->GetFunction(i->GetCurrentContext()).ToLocalChecked()).Check()
                                                                         ^
../src/rulesjs/rules.cc:855:5: note: in expansion of macro ‘DEFINE_FUNCTION’
     DEFINE_FUNCTION(exports, isolate, "cancelTimer", jsCancelTimer);
     ^~~~~~~~~~~~~~~
../src/rulesjs/rules.cc:21:241: error: ‘class v8::Maybe<bool>’ has no member named ‘Check’; did you mean ‘ToChecked’?
 te::New(i, func)->GetFunction(i->GetCurrentContext()).ToLocalChecked()).Check()
                                                                         ^
../src/rulesjs/rules.cc:857:5: note: in expansion of macro ‘DEFINE_FUNCTION’
     DEFINE_FUNCTION(exports, isolate, "getState", jsGetState);
     ^~~~~~~~~~~~~~~
../src/rulesjs/rules.cc:21:241: error: ‘class v8::Maybe<bool>’ has no member named ‘Check’; did you mean ‘ToChecked’?
 te::New(i, func)->GetFunction(i->GetCurrentContext()).ToLocalChecked()).Check()
                                                                         ^
../src/rulesjs/rules.cc:859:5: note: in expansion of macro ‘DEFINE_FUNCTION’
     DEFINE_FUNCTION(exports, isolate, "deleteState", jsDeleteState);
     ^~~~~~~~~~~~~~~
../src/rulesjs/rules.cc:21:241: error: ‘class v8::Maybe<bool>’ has no member named ‘Check’; did you mean ‘ToChecked’?
 te::New(i, func)->GetFunction(i->GetCurrentContext()).ToLocalChecked()).Check()
                                                                         ^
../src/rulesjs/rules.cc:861:5: note: in expansion of macro ‘DEFINE_FUNCTION’
     DEFINE_FUNCTION(exports, isolate, "renewActionLease", jsRenewActionLease);
     ^~~~~~~~~~~~~~~
../src/rulesjs/rules.cc:21:241: error: ‘class v8::Maybe<bool>’ has no member named ‘Check’; did you mean ‘ToChecked’?
 te::New(i, func)->GetFunction(i->GetCurrentContext()).ToLocalChecked()).Check()
                                                                         ^
../src/rulesjs/rules.cc:863:5: note: in expansion of macro ‘DEFINE_FUNCTION’
     DEFINE_FUNCTION(exports, isolate, "getEvents", jsGetEvents);
     ^~~~~~~~~~~~~~~
../src/rulesjs/rules.cc:21:241: error: ‘class v8::Maybe<bool>’ has no member named ‘Check’; did you mean ‘ToChecked’?
 te::New(i, func)->GetFunction(i->GetCurrentContext()).ToLocalChecked()).Check()
                                                                         ^
../src/rulesjs/rules.cc:865:5: note: in expansion of macro ‘DEFINE_FUNCTION’
     DEFINE_FUNCTION(exports, isolate, "getFacts", jsGetFacts);
     ^~~~~~~~~~~~~~~
../src/rulesjs/rules.cc:21:241: error: ‘class v8::Maybe<bool>’ has no member named ‘Check’; did you mean ‘ToChecked’?
 te::New(i, func)->GetFunction(i->GetCurrentContext()).ToLocalChecked()).Check()
                                                                         ^
../src/rulesjs/rules.cc:867:5: note: in expansion of macro ‘DEFINE_FUNCTION’
     DEFINE_FUNCTION(exports, isolate, "setStoreMessageCallback", jsSetStoreMessageCallback);
     ^~~~~~~~~~~~~~~
../src/rulesjs/rules.cc:21:241: error: ‘class v8::Maybe<bool>’ has no member named ‘Check’; did you mean ‘ToChecked’?
 te::New(i, func)->GetFunction(i->GetCurrentContext()).ToLocalChecked()).Check()
                                                                         ^
../src/rulesjs/rules.cc:869:5: note: in expansion of macro ‘DEFINE_FUNCTION’
     DEFINE_FUNCTION(exports, isolate, "setDeleteMessageCallback", jsSetDeleteMessageCallback);
     ^~~~~~~~~~~~~~~
../src/rulesjs/rules.cc:21:241: error: ‘class v8::Maybe<bool>’ has no member named ‘Check’; did you mean ‘ToChecked’?
 te::New(i, func)->GetFunction(i->GetCurrentContext()).ToLocalChecked()).Check()
                                                                         ^
../src/rulesjs/rules.cc:871:5: note: in expansion of macro ‘DEFINE_FUNCTION’
     DEFINE_FUNCTION(exports, isolate, "setQueueMessageCallback", jsSetQueueMessageCallback);
     ^~~~~~~~~~~~~~~
../src/rulesjs/rules.cc:21:241: error: ‘class v8::Maybe<bool>’ has no member named ‘Check’; did you mean ‘ToChecked’?
 te::New(i, func)->GetFunction(i->GetCurrentContext()).ToLocalChecked()).Check()
                                                                         ^
../src/rulesjs/rules.cc:873:5: note: in expansion of macro ‘DEFINE_FUNCTION’
     DEFINE_FUNCTION(exports, isolate, "setGetQueuedMessagesCallback", jsSetGetQueuedMessagesCallback);
     ^~~~~~~~~~~~~~~
../src/rulesjs/rules.cc:21:241: error: ‘class v8::Maybe<bool>’ has no member named ‘Check’; did you mean ‘ToChecked’?
 te::New(i, func)->GetFunction(i->GetCurrentContext()).ToLocalChecked()).Check()
                                                                         ^
../src/rulesjs/rules.cc:875:5: note: in expansion of macro ‘DEFINE_FUNCTION’
     DEFINE_FUNCTION(exports, isolate, "completeGetQueuedMessages", jsCompleteGetQueuedMessages);
     ^~~~~~~~~~~~~~~
../src/rulesjs/rules.cc:21:241: error: ‘class v8::Maybe<bool>’ has no member named ‘Check’; did you mean ‘ToChecked’?
 te::New(i, func)->GetFunction(i->GetCurrentContext()).ToLocalChecked()).Check()
                                                                         ^
../src/rulesjs/rules.cc:877:5: note: in expansion of macro ‘DEFINE_FUNCTION’
     DEFINE_FUNCTION(exports, isolate, "setGetIdleStateCallback", jsSetGetIdleStateCallback);
     ^~~~~~~~~~~~~~~
../src/rulesjs/rules.cc:21:241: error: ‘class v8::Maybe<bool>’ has no member named ‘Check’; did you mean ‘ToChecked’?
 te::New(i, func)->GetFunction(i->GetCurrentContext()).ToLocalChecked()).Check()
                                                                         ^
../src/rulesjs/rules.cc:879:5: note: in expansion of macro ‘DEFINE_FUNCTION’
     DEFINE_FUNCTION(exports, isolate, "completeGetIdleState", jsCompleteGetIdleState);
     ^~~~~~~~~~~~~~~
rulesjs.target.mk:112: recipe for target 'Release/obj.target/rulesjs/src/rulesjs/rules.o' failed
make: *** [Release/obj.target/rulesjs/src/rulesjs/rules.o] Error 1
make: Leaving directory '/home/alxfed/alxfed/jupy/node_modules/durable/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/alxfed/miniconda3/envs/jupy/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 4.15.0-1076-oem
gyp ERR! command "/home/alxfed/miniconda3/envs/jupy/bin/node" "/home/alxfed/miniconda3/envs/jupy/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/alxfed/alxfed/jupy/node_modules/durable
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! durable@2.0.29 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the durable@2.0.29 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alxfed/.npm/_logs/2020-03-22T12_55_58_165Z-debug.log

</pre>
Do you need a log file?
Also:
<pre>
(jupy) alxfed@fedot:~/alxfed/jupy$ node --version
v10.13.0
(jupy) alxfed@fedot:~/alxfed/jupy$ npm --version
6.4.1
</pre>

**Comment by jruizgit** [comment]
Hi, thanks for reporting this issue. What platform are you using?

**Comment by MStumpp** [comment]
Had the same problem. Just update to latest node (v12.16.1 in my case).

**Comment by alxfed** [comment]
Ubuntu 18.04

**Comment by alxfed** [comment]
On an updated version of node 12.16.1
<pre>
(base) alxfed@fedot:~/alxfed/jupy$ node --version
v12.16.1
(base) alxfed@fedot:~/alxfed/jupy$ npm install durable

> durable@2.0.29 install /home/alxfed/alxfed/jupy/node_modules/durable
> node-gyp rebuild

make: Entering directory '/home/alxfed/alxfed/jupy/node_modules/durable/build'
  CC(target) Release/obj.target/rules/src/rules/json.o
  CC(target) Release/obj.target/rules/src/rules/rete.o
  CC(target) Release/obj.target/rules/src/rules/events.o
In file included from ../src/rules/events.c:11:0:
../src/rules/events.c: In function ‘reduceOperand’:
../src/rules/rules.h:71:31: warning: this statement may fall through [-Wimplicit-fallthrough=]
 #define CHECK_RESULT(func) do { \
                               ^
../src/rules/events.c:281:13: note: in expansion of macro ‘CHECK_RESULT’
             CHECK_RESULT(getMessageFromFrame(state,
             ^~~~~~~~~~~~
../src/rules/events.c:286:9: note: here
         case JSON_MESSAGE_IDENTIFIER:
         ^~~~
../src/rules/events.c: In function ‘handleDeleteMessage’:
../src/rules/events.c:1061:23: warning: ‘result’ may be used uninitialized in this function [-Wmaybe-uninitialized]
             } else if (result == RULES_OK) {
                       ^
  CC(target) Release/obj.target/rules/src/rules/state.o
../src/rules/state.c: In function ‘storeMessage’:
../src/rules/state.c:783:23: warning: ‘actionType’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         unsigned char actionType;
                       ^~~~~~~~~~
  CC(target) Release/obj.target/rules/src/rules/regex.o
../src/rules/regex.c: In function ‘utf8ToUnicode’:
../src/rules/regex.c:210:13: warning: this statement may fall through [-Wimplicit-fallthrough=]
             ++*first;
             ^~~~~~~~
../src/rules/regex.c:211:9: note: here
         case 2:
         ^~~~
../src/rules/regex.c:214:13: warning: this statement may fall through [-Wimplicit-fallthrough=]
             ++*first;
             ^~~~~~~~
../src/rules/regex.c:215:9: note: here
         case 1:
         ^~~~
../src/rules/regex.c:218:13: warning: this statement may fall through [-Wimplicit-fallthrough=]
             ++*first;
             ^~~~~~~~
../src/rules/regex.c:219:9: note: here
         case 0:
         ^~~~
  AR(target) Release/obj.target/src/rules/rules.a
  COPY Release/rules.a
  CXX(target) Release/obj.target/rulesjs/src/rulesjs/rules.o
  SOLINK_MODULE(target) Release/obj.target/rulesjs.node
  COPY Release/rulesjs.node
make: Leaving directory '/home/alxfed/alxfed/jupy/node_modules/durable/build'
npm WARN notsup Unsupported engine for durable@2.0.29: wanted: {"node":"12.11.x","npm":"6.11.x"} (current: {"node":"12.16.1","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: durable@2.0.29

+ durable@2.0.29
added 72 packages from 67 contributors and audited 241 packages in 7.414s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
</pre>

No errors, just warnings... BUT... if you try to run the prescribed test example:

<pre>
(jupy) alxfed@fedot:~/alxfed/jupy$ node test.js
/home/alxfed/alxfed/jupy/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: The module '/home/alxfed/alxfed/jupy/node_modules/durable/build/Release/rulesjs.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:717:18)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at bindings (/home/alxfed/alxfed/jupy/node_modules/bindings/bindings.js:112:48)
    at /home/alxfed/alxfed/jupy/node_modules/durable/libjs/durableEngine.js:2:32
    at Object.<anonymous> (/home/alxfed/alxfed/jupy/node_modules/durable/libjs/durableEngine.js:1090:2)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
</pre>

**Comment by alxfed** [comment]
@MStumpp 
Worked (on new stable 12.16.1 with rebuilt 'durable').
But now I have _two_ versions of node on my computer, one (10.x.x) works in Jupyter with a kernel, another one (12.16.1) with this rules engine. :) And they switch by themselves, whenever they please. :) Nice.
Thanks anyway.

**Comment by jruizgit** [comment]
Hi, thanks for asking the question. I just finished testing Ubuntu 18.04 + node 13.11. The tests passed. Node 10.x.x is no longer supported. 

@MStumpp I think the problem you are seeing is different. Would you mind opening another issue and attaching the command line output?

**Comment by MStumpp** [comment]
@jruizgit I saw exactly the same => error: ‘class v8::Maybe’ has no member named ‘Check’; did you mean ‘ToChecked’?
