### ISSUE TITLE
Comparing fact against an array of values

### ISSUE THREAD

**Issue by RG-arulprashanth** [jruizgit/rules#324]
Can we assert a fact property against an array of another fact property as described below

    @when_all(m.wild_animals.anyItem(item.matches(m.animal_type)))
    def wild_animals(c):
        publish('{} is a wild animal'.format(c.m.animal_type))

post({'animal': {'animal_type': 'Tiger', 'wild_animals': ['Tiger', 'Lion']}})
post({'animal': {'animal_type': 'Cat', 'wild_animals': ['Tiger', 'Lion']}})

when I try this am getting an error

defining $m, animal_type
 
I saw in another issue the possibility of using a 'in' keyword, is that an option like
m.animal_type in m.wild_animals

**Comment by jruizgit** [comment]
Hi, thanks for asking the question. The scenario you posted above is supported. The rule should be written as follows:

```python
with ruleset('animal'):
    @when_all(m.wild_animals.anyItem(item == m.animal_type))
    def wild_animals(c):
        print('{0} is a wild animal'.format(c.m.animal_type))

post('animal', {'animal_type': 'Tiger', 'wild_animals': ['Tiger', 'Lion']})
```

What is not supported (yet) is asserting the array as a separate fact. The rule below will fail on creation:

```python
with ruleset('animal'):

    @when_all(c.wild_animals << +m.types,
              c.animal << c.wild_animals.types.anyItem(item == m.animal_type))
    def wild_animals(c):
        print('{0} is a wild animal'.format(c.animal.animal_type))

assert_fact('animal', { 'types': ['Tiger', 'Lion']})
post('animal', {'animal_type': 'Tiger'})
```

**Comment by RG-arulprashanth** [comment]
Thanks for clarifying.
