### ISSUE TITLE
(ruby) Wrong number of arguments passed for Timers

### ISSUE THREAD

**Issue by mrryanjohnston** [jruizgit/rules#343]
Currently, the wrong number of arguments are passed to the Timer lambdas from the Timer gem in `librb/engine.rb`. The Timer gem passes `self` as a second argument.

**Comment by mrryanjohnston** [comment]
Fixed in #342 342

**Comment by jruizgit** [comment]
Hi, thanks for posting the pull request. I have merged the change and published a new version (2.0.28).
