### ISSUE TITLE
If it is possible compare first character of string using python?

### ISSUE THREAD

**Issue by subhasis-dev** [jruizgit/rules#345]
with ruleset('test'):
    # antecedent
    @when_all(m.subject[0] = m.key[0])
    def say_hello(c):
        # consequent
        print('Hi, {0}'.format(c.m.subject))
        
post('test', { 'subject': 'hello World', 'key' : 'hello' })

I want to compare between two values if initial letter is same.

**Comment by jruizgit** [comment]
Hi, thanks for asking the question. The rules engine supports a regular expression dialect. For example:

```python
    @when_all(m.subject.matches('hello.*'))
    def starts_with(c):
        print ('string starts with hello -> {0}'.format(c.m.subject))
```
