### ISSUE TITLE
What does the function  'retract_fact' mean? Why is it often used with 'none(+m.x)', Is it specially used to trigger 'none(+m.x)'?

### ISSUE THREAD

**Issue by YXWisaboy** [jruizgit/rules#368]
Because I didn't see the relevant content in the document, I'd like to ask. I'm using the python version.  Look forward to hearing from you.

**Comment by sureshvv** [comment]
retract_fact is like removing the fact from future consideration. Remember all facts stick around indefinitely.

none(...) means no event matching condition So when a fact is retracted, the none(...) condition can succeed.

.Where did you see it used with none(+m.x)?
