### ISSUE TITLE
Issue with any rule

### ISSUE THREAD

**Issue by balawa** [jruizgit/rules#37]
Hi:

I am having difficulties with the current scenarios and I am not sure why.

The rule is simple and taking from the test examples.
##### 

Durable.ruleset :a5 do
  when_all any(m.subject == "jumbo", m.subject == "approve"),
           any(m.amount == 10000, m.amount == 100) do
    puts "a5 action #{s.sid}"
  end
  when_start do
    post :a5, {:id => 3, :sid => 2, :subject => "jumbo"}
    post :a5, {:id => 4, :sid => 2, :amount => 10000}
    post :a5, {:id => 1, :sid => 1, :subject => "approve"}
    post :a5, {:id => 2, :sid => 1, :amount => 100}
  end
end

Durable.run_all
#### 

I would expect the engine to report 2 actions for sid 1 & 2. 

However the engine only report 1 action.
The interesting part is that when I switch the condition in the any block, the engine then report the missing action but not the first one any more.
I do clear the redis key between test.

**Comment by jruizgit** [comment]
Hi, thanks for reporting the problem. Yes the scenario should trigger two actions. I will take a look and report back on my findings.

**Comment by jruizgit** [comment]
Quick update on this: All expressions (like the one in this example) are reduced to the form any(all, all...). There is a regression with the code generated for trees of the shape any(all, all...). Still working on a proper solution.

**Comment by jruizgit** [comment]
I have pushed and published a fix for this issue. There was an issue with the lua script compiled and a problem with name collision when generating the resultset. So, the fix was a little involved. all-any should behave now as expected. Please use  version 0.34.11.
