### ISSUE TITLE
TODO: Context Events mids are generated using rand()

### ISSUE THREAD

**Issue by jruizgit** [jruizgit/rules#38]
Context Events mids are generated using rand(), this is a temporary solution which needs to be improved because it can have unfortunate consequences:
1. There is a probability of mid collision (1 in 1 billion per session)
2. Idempotency broken in case of failure (might generate two events for one save)

**Comment by balawa** [comment]
What about a more complex id generation algorithm.

Something like epoch_timestamp (this will ensure time ordering of the id) + long enough random hex string creating a 16/32 bytes string making the chance of collision to become very very slim. (over 1 billion event per s)
(ruby -> Time.now.to_i.to_s(16) + SecureRandom.hex(12))

**Comment by jruizgit** [comment]
Hi, thanks for the suggestion. I agree a more complex id generation algorithm could significantly reduce the probability of collision. However if a checkpoint fails and the operation has to be retried, we will generate two events. 

Alternatively I was thinking of keeping a table with the context version number, on every checkpoint  we could increase the version number and generate the event mid based on the version. This would guarantee no collision and consistency. The change is more involved and could have significant performance impact.

**Comment by balawa** [comment]
Hi,

The is could be very memory intensive. An alternative solution would be to use a bloomfilter there as you only need to check if the id already happen in the past and let the key expire overtime to avoid overflowing the filter.

The bloomfilter will then no impact performance that much and keep a low memory footprint.

**Comment by jruizgit** [comment]
Hi, just quick update on this issue. I pushed a fix to avoid rand() when generating event ids for checkpoints. I do keep an extra number for every state object. 

To enforce idempotency, the engine keeps track of the event ids already seen (this code has existed for a while). Yes, we need to replace the lookup with a bloom filter as you suggest above.
