### ISSUE TITLE
why post a nested json message in python is failed?

### ISSUE THREAD

**Issue by tanghanerla** [jruizgit/rules#39]
hi, 
   I want to post a nested json to a rule set like this: 
   post("http://localhost:5000/pin_fen/1", params_dic).
   params_dic is a dic which data come from a json string:
  [ {
  "cc_n_all":15,
  "CreditCard":
    [
      {
        "Last4Digit": "9832",
        "Issue Bank": "111",
        "Statement_Date": 18,
        "Payment_Due_Date": 5,
        "CreditAmt": 100000
      },
      {
        "Last4Digit": "9832",
        "Issue Bank": "33333",
        "Statement_Date": 18,
        "Payment_Due_Date": 5,
        "CreditAmt": 100000
      }]
 }](url)

The rule set is : 
 with ruleset('pin_fen'):
    @when_all(pri(1), m.cc_n_all > 0)
    def rule_1(c):
        print('before: c.m: {0}'.format(c.m))
        if c.m.cc_n_all >1 and c.m.cc_n_all<28:
            c.m.cc_n_all_woe = 11.12

Why in the c.m, I can not find the c.m.CreditCard in memory?  Does support post a nested dic such as 
 a list is a dic value or more complex dic value, like: 

```
{
  "ApplyID":"123456",
  "IDCardNum":"452122197905161234",
  "Name":"测试1",
  "cc_n_all":15,
  "cc_n_all_woe":null,
  "CreditCard": {
    "Last4Digit": "9832",
    "Issue Bank": "7777777",
    "Statement_Date": 18,
    "Payment_Due_Date": 5,
    "CreditAmt": 100000,
    "Statement": [
      {
        "Statement_Period": "2016.04.12-2016.05.11",
        "Expense": 982,
        "Payment": 1525.72,
        "LastBalance": -1525.72,
        "Last_Min_Payment": 152.57,
        "Balance": 982,
        "Min_Payment": 98.2,
        "Late_Fee": 0,
        "Statement_Detail": [
          {
            "Last4Digit": "9832",
            "Trans_Date": "2016/4/14",
            "Post_Date": "2016/4/14",
            "Trans_ Type": "777777",
            "Trans_Desc": "7777777777777）"
           
          },
          {
            "Last4Digit": "9832",
            "Trans_Date": "2016/4/20",
            "Post_Date": "2016/4/20",
            "Trans_ Type": "777777777",
            "Trans_Desc": "666666666"
            
          }
        ]
      },
      {
        "Statement_Period": "2016.05.12-2016.06.11",
        "Expense": 64.97,
        "Payment": 995,
        "LastBalance": 982,
        "Last_Min_Payment": 98.2,
        "Balance": 51.97,
        "Min_Payment": 5.2,
      
        "Late_Fee": 4.91,
        "Statement_Detail": [
          {
            "Last4Digit": "9832",
            "Trans_Date": "2016/5/16",
            "Post_Date": "2016/5/16",
            "Trans_ Type": "6666666666",
            "Trans_Desc": "yyyyyyyyyy"
            
          },
          {
            "Last4Digit": "9832",
            "Trans_Date": "2016/6/5",
            "Post_Date": "2016/6/5",
            "Trans_ Type": "yyyyyyy",
            "Trans_Desc": "hhhhhhhhh"       
          }
        ]
      }
    ]
  }
}


```

**Comment by tanghanerla** [comment]
hi,  jruizgit 
  Thanks your great job on this engine and it help me a lot in my work.
   I read https://github.com/jruizgit/rules/issues/32.  When I use Nested object query all are k/v pair , it works .
But when I  want to nest a list in a json. It does not work. like below one: 
How can I  get "CreditCard.Statement[0].Statement_Period" in my example json? 
Does it support nest a list in a json as event object ? 
Thank you very much.

{
  "ApplyID":"123456",
  "IDCardNum":"452122197905161234",
  "Name":"测试1",
  "cc_n_all":15,
  "cc_n_all_woe":null,
  "CreditCard": {
    "Last4Digit": "9832",
    "Issue Bank": "7777777",
    "Statement_Date": 18,
    "Payment_Due_Date": 5,
    "CreditAmt": 100000,
    "Statement": [
      {
        "Statement_Period": "2016.04.12-2016.05.11",
        "Expense": 982,
        "Payment": 1525.72,
        "LastBalance": -1525.72,
        "Last_Min_Payment": 152.57,
        "Balance": 982,
        "Min_Payment": 98.2,
        "Late_Fee": 0,
        "Statement_Detail": [
          {
            "Last4Digit": "9832",
            "Trans_Date": "2016/4/14",
            "Post_Date": "2016/4/14",
            "Trans_ Type": "777777",
            "Trans_Desc": "7777777777777）"

          },
          {
            "Last4Digit": "9832",
            "Trans_Date": "2016/4/20",
            "Post_Date": "2016/4/20",
            "Trans_ Type": "777777777",
            "Trans_Desc": "666666666"

          }
        ]
      },
      {
        "Statement_Period": "2016.05.12-2016.06.11",
        "Expense": 64.97,
        "Payment": 995,
        "LastBalance": 982,
        "Last_Min_Payment": 98.2,
        "Balance": 51.97,
        "Min_Payment": 5.2,

        "Late_Fee": 4.91,
        "Statement_Detail": [
          {
            "Last4Digit": "9832",
            "Trans_Date": "2016/5/16",
            "Post_Date": "2016/5/16",
            "Trans_ Type": "6666666666",
            "Trans_Desc": "yyyyyyyyyy"

          },
          {
            "Last4Digit": "9832",
            "Trans_Date": "2016/6/5",
            "Post_Date": "2016/6/5",
            "Trans_ Type": "yyyyyyy",
            "Trans_Desc": "hhhhhhhhh"       
          }
        ]
      }
    ]
  }
}

**Comment by jruizgit** [comment]
Hi, thanks a lot for reporting the issue, the engine doesn't support queries over json arrays . That said, the array in the event should be preserved. I'll debug and get this fixed in a few days.

Sent from my phone

On Sep 15, 2016, at 11:15 PM, tanghanerla <notifications@github.com<mailto:notifications@github.com>> wrote:


hi, jruizgit
Thanks your great job on this engine and it help me a lot in my work.
I read #32<https://github.com/jruizgit/rules/issues/32>. When I use Nested object query all are k/v pair , it works .
But when I want to nest a list in a json. It does not work. like below one:
How can I get "CreditCard.Statement[0].Statement_Period" in my example json?
Does it support nest a list in a json as event object ?
Thank you very much.

{
"ApplyID":"123456",
"IDCardNum":"452122197905161234",
"Name":"??1",
"cc_n_all":15,
"cc_n_all_woe":null,
"CreditCard": {
"Last4Digit": "9832",
"Issue Bank": "7777777",
"Statement_Date": 18,
"Payment_Due_Date": 5,
"CreditAmt": 100000,
"Statement": [
{
"Statement_Period": "2016.04.12-2016.05.11",
"Expense": 982,
"Payment": 1525.72,
"LastBalance": -1525.72,
"Last_Min_Payment": 152.57,
"Balance": 982,
"Min_Payment": 98.2,
"Late_Fee": 0,
"Statement_Detail": [
{
"Last4Digit": "9832",
"Trans_Date": "2016/4/14",
"Post_Date": "2016/4/14",
"Trans_ Type": "777777",
"Trans_Desc": "7777777777777?"

      },
      {
        "Last4Digit": "9832",
        "Trans_Date": "2016/4/20",
        "Post_Date": "2016/4/20",
        "Trans_ Type": "777777777",
        "Trans_Desc": "666666666"

      }
    ]
  },
  {
    "Statement_Period": "2016.05.12-2016.06.11",
    "Expense": 64.97,
    "Payment": 995,
    "LastBalance": 982,
    "Last_Min_Payment": 98.2,
    "Balance": 51.97,
    "Min_Payment": 5.2,

    "Late_Fee": 4.91,
    "Statement_Detail": [
      {
        "Last4Digit": "9832",
        "Trans_Date": "2016/5/16",
        "Post_Date": "2016/5/16",
        "Trans_ Type": "6666666666",
        "Trans_Desc": "yyyyyyyyyy"

      },
      {
        "Last4Digit": "9832",
        "Trans_Date": "2016/6/5",
        "Post_Date": "2016/6/5",
        "Trans_ Type": "yyyyyyy",
        "Trans_Desc": "hhhhhhhhh"
      }
    ]
  }
]


}
}

-

**Comment by tanghanerla** [comment]
Thanks you very much.

**Comment by jruizgit** [comment]
Quick update: I have pushed and published the fix for this issue. Please use version 0.33.74 or above.

**Comment by tanghanerla** [comment]
Thanks your quick response very much.
