### ISSUE TITLE
 Problem when installing on Ubuntu:  npm ERR! Failed at the durable@0.20.3 install script.

### ISSUE THREAD

**Issue by robotiko** [jruizgit/rules#4]
Hi jruizgit, 

when I try to create the simple demo test on ubuntu (heroku dyno), it fails  in the npm package build due to compiling issues during node-gyp build.
It also looks like all the code updates in repo are not reflected in npm (3 months old).
 
Attached  trace. 

remote:        Installing node modules
remote:        npm WARN engine durable@0.20.3: wanted: {"node":"0.8.x","npm":"1.1.x"} (current: {"node":"v0.10.17","npm":"1.3.26"})
remote:
remote:        > hiredis@0.1.17 install /tmp/build_2aa3e8b6eeba3c027492030ab7e84d1c/node_modules/durable/node_modules/hiredis
remote:        > node-gyp rebuild
remote:
remote:        make: Entering directory `/tmp/build_2aa3e8b6eeba3c027492030ab7e84d1c/node_modules/durable/node_modules/hiredis/build'
remote:          CC(target) Release/obj.target/hiredis/deps/hiredis/hiredis.o
remote:          CC(target) Release/obj.target/hiredis/deps/hiredis/net.o
remote:          CC(target) Release/obj.target/hiredis/deps/hiredis/sds.o
remote:          CC(target) Release/obj.target/hiredis/deps/hiredis/async.o
remote:          AR(target) Release/obj.target/deps/hiredis.a
remote:          COPY Release/hiredis.a
remote:          CXX(target) Release/obj.target/hiredis/src/hiredis.o
remote:          CXX(target) Release/obj.target/hiredis/src/reader.o
remote:          SOLINK_MODULE(target) Release/obj.target/hiredis.node
remote:          SOLINK_MODULE(target) Release/obj.target/hiredis.node: Finished

remote:          COPY Release/hiredis.node
remote:        make: Leaving directory `/tmp/build_2aa3e8b6eeba3c027492030ab7e84d1c/node_modules/durable/node_modules/hiredis/build'
remote:
remote:        > mime@1.3.2 install /tmp/build_2aa3e8b6eeba3c027492030ab7e84d1c/node_modules/durable/node_modules/node-static/node_modules/mime
remote:        > node build/build.js > types.json
remote:
remote:
remote:        > durable@0.20.3 install /tmp/build_2aa3e8b6eeba3c027492030ab7e84d1c/node_modules/durable
remote:        > node-gyp rebuild
remote:
remote:        make: Entering directory `/tmp/build_2aa3e8b6eeba3c027492030ab7e84d1c/node_modules/durable/build'
remote:          CC(target) Release/obj.target/hiredis/deps/hiredis/hiredis.o
remote:          CC(target) Release/obj.target/hiredis/deps/hiredis/net.o
remote:          CC(target) Release/obj.target/hiredis/deps/hiredis/sds.o
remote:          CC(target) Release/obj.target/hiredis/deps/hiredis/async.o
remote:          AR(target) Release/obj.target/deps/hiredis.a
remote:          COPY Release/hiredis.a
remote:          CC(target) Release/obj.target/rules/src/rules/json.o
remote:        ../src/rules/json.c: In function 'getString':
remote:        ../src/rules/json.c:319:20: warning: 'delimiter' may be used uninitialized in this function [-Wmaybe-uninitialized]
remote:                         if (start[0] == delimiter) {
remote:                            ^
remote:        ../src/rules/json.c: In function 'readNextName':
remote:        ../src/rules/json.c:354:20: warning: 'delimiter' may be used uninitialized in this function [-Wmaybe-uninitialized]
remote:                         if (start[0] == delimiter) {
remote:                            ^
remote:        ../src/rules/json.c:339:10: note: 'delimiter' was declared here
remote:             char delimiter;
remote:                  ^
remote:          CC(target) Release/obj.target/rules/src/rules/rete.o
remote:        ../src/rules/rete.c: In function 'storeQuery':
remote:        ../src/rules/rete.c:103:5: error: 'for' loop initial declarations are only allowed in C99 mode
remote:             for (unsigned int i = 0; i < lineCount; ++i) {
remote:             ^
remote:        ../src/rules/rete.c:103:5: note: use option -std=c99 or -std=gnu99 to compile your code
remote:        ../src/rules/rete.c: In function 'createBeta':
remote:        ../src/rules/rete.c:828:13: error: 'for' loop initial declarations are only allowed in C99 mode
remote:                     for (int i = 0; i < lengthDiff -1; ++i) {
remote:                     ^
remote:        ../src/rules/rete.c: In function 'add':
remote:        ../src/rules/rete.c:881:5: error: 'for' loop initial declarations are only allowed in C99 mode
remote:             for (unsigned int i = 0; i < left->nodesLength; ++i) {
remote:             ^
remote:        ../src/rules/rete.c: In function 'multiply':
remote:        ../src/rules/rete.c:896:5: error: 'for' loop initial declarations are only allowed in C99 mode
remote:             for (unsigned int i = 0; i < left->nodesLength; ++i) {
remote:             ^
remote:        ../src/rules/rete.c:898:9: error: 'for' loop initial declarations are only allowed in C99 mode
remote:                 for (unsigned int ii = 0; ii < right->nodesLength; ++ii) {
remote:                 ^
remote:        ../src/rules/rete.c:910:13: error: 'for' loop initial declarations are only allowed in C99 mode
remote:                     for (unsigned int iii = 0; iii < rightAll->namesLength; ++iii) {
remote:                     ^
remote:        ../src/rules/rete.c:919:31: error: redefinition of 'iii'
remote:                     for (unsigned int iii = 0; iii < leftAll->namesLength; ++iii) {
remote:                                       ^
remote:        ../src/rules/rete.c:910:31: note: previous definition of 'iii' was here
remote:                     for (unsigned int iii = 0; iii < rightAll->namesLength; ++iii) {
remote:                                       ^
remote:        ../src/rules/rete.c:919:13: error: 'for' loop initial declarations are only allowed in C99 mode
remote:                     for (unsigned int iii = 0; iii < leftAll->namesLength; ++iii) {
remote:                     ^
remote:        ../src/rules/rete.c:932:27: error: redefinition of 'ii'
remote:                 for (unsigned int ii = 0; ii < leftAll->namesLength; ++ii) {
remote:                                   ^
remote:        ../src/rules/rete.c:898:27: note: previous definition of 'ii' was here
remote:                 for (unsigned int ii = 0; ii < right->nodesLength; ++ii) {
remote:                                   ^
remote:        ../src/rules/rete.c:932:9: error: 'for' loop initial declarations are only allowed in C99 mode
remote:                 for (unsigned int ii = 0; ii < leftAll->namesLength; ++ii) {
remote:                 ^
remote:        ../src/rules/rete.c:939:23: error: redefinition of 'i'
remote:             for (unsigned int i = 0; i < right->nodesLength; ++i) {
remote:                               ^
remote:        ../src/rules/rete.c:896:23: note: previous definition of 'i' washere
remote:             for (unsigned int i = 0; i < left->nodesLength; ++i) {
remote:                               ^
remote:        ../src/rules/rete.c:939:5: error: 'for' loop initial declarations are only allowed in C99 mode
remote:             for (unsigned int i = 0; i < right->nodesLength; ++i) {
remote:             ^
remote:        ../src/rules/rete.c:941:9: error: 'for' loop initial declarations are only allowed in C99 mode
remote:                 for (unsigned int ii = 0; ii < rightAll->namesLength; ++ii) {
remote:                 ^
remote:        ../src/rules/rete.c: In function 'createQueries':
remote:        ../src/rules/rete.c:999:5: error: 'for' loop initial declarations are only allowed in C99 mode
remote:             for (unsigned int i = 0; i < betaPath->namesLength; ++ i) {
remote:             ^
remote:        ../src/rules/rete.c: In function 'fixupQueries':
remote:        ../src/rules/rete.c:1059:5: error: 'for' loop initial declarations are only allowed in C99 mode
remote:             for (unsigned int i = 0; i < query->nodesLength; ++i) {
remote:             ^
remote:        ../src/rules/rete.c:1062:9: error: 'for' loop initial declarations are only allowed in C99 mode
remote:                 for (unsigned int ii = 0; ii < currentAll->namesLength;++ii) {
remote:                 ^
remote:        ../src/rules/rete.c:1068:27: error: redefinition of 'ii'
remote:                 for (unsigned int ii = 0; ii < currentAll->namesLength;++ii) {
remote:                                   ^
remote:        ../src/rules/rete.c:1062:27: note: previous definition of 'ii' was here
remote:                 for (unsigned int ii = 0; ii < currentAll->namesLength;++ii) {
remote:                                   ^
remote:        ../src/rules/rete.c:1068:9: error: 'for' loop initial declarations are only allowed in C99 mode
remote:                 for (unsigned int ii = 0; ii < currentAll->namesLength;++ii) {
remote:                 ^
remote:        ../src/rules/rete.c:1086:23: error: redefinition of 'i'
remote:             for (unsigned int i = 0; i < query->nodesLength; ++i) {
remote:                               ^
remote:        ../src/rules/rete.c:1059:23: note: previous definition of 'i' was here
remote:             for (unsigned int i = 0; i < query->nodesLength; ++i) {
remote:                               ^
remote:        ../src/rules/rete.c:1086:5: error: 'for' loop initial declarations are only allowed in C99 mode
remote:             for (unsigned int i = 0; i < query->nodesLength; ++i) {
remote:             ^
remote:        make: *** [Release/obj.target/rules/src/rules/rete.o] Error 1
remote:        make: Leaving directory `/tmp/build_2aa3e8b6eeba3c027492030ab7e84d1c/node_modules/durable/build'
remote:        gyp ERR! build error
remote:        gyp ERR! stack Error: `make` failed with exit code: 2
remote:        gyp ERR! stack     at ChildProcess.onExit (/tmp/build_2aa3e8b6eeba3c027492030ab7e84d1c/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
remote:        gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
remote:        gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
remote:        gyp ERR! System Linux 3.13.0-40-generic
remote:        gyp ERR! command "node" "/tmp/build_2aa3e8b6eeba3c027492030ab7e84d1c/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
remote:        gyp ERR! cwd /tmp/build_2aa3e8b6eeba3c027492030ab7e84d1c/node_modules/durable
remote:        gyp ERR! node -v v0.10.17
remote:        gyp ERR! node-gyp -v v0.12.2
remote:        gyp ERR! not ok
remote:        npm ERR! durable@0.20.3 install: `node-gyp rebuild`
remote:        npm ERR! Exit status 1
remote:        npm ERR!
remote:        npm ERR! Failed at the durable@0.20.3 install script.

**Comment by jruizgit** [comment]
Hi robotiko, thanks a lot for reporting the issue. I have updated the npm package (use 0.30.6) and fixed all issues with Linux. I just tried deploying to Heroku and it worked (please see jruizgit/cloud). Please give it a try!

**Comment by robotiko** [comment]
Hi jruizgit,
thank you for such a fast response!

Tried and working using the cloud example. 

Thanks
