### ISSUE TITLE
how to deploy  durable_rules server on Gunicorn?

### ISSUE THREAD

**Issue by tanghanerla** [jruizgit/rules#41]
hi,jruizgit 
    Thanks your great job on durable_rules and it helps my project a lot. When I finished my development, I want to deploy it on production env using Gunicorn. 
  In "engine_server.py" : 

> if **name** == '**main**':
>                     run_all(host_name = '127.0.0.1', port = 5600)

start  gunicorn:  

>  gunicorn -c   config/gun.conf  engine_server:app

However, I found it failed when deploy on gunicorn.
How can I  delpoy durable_rules on gunicorn ? 

 Blow is gunicorn log: 

> [2016-09-22 13:48:18 +0000] [589] [INFO] Starting gunicorn 19.6.0
> [2016-09-22 13:48:18 +0000] [589] [DEBUG] Arbiter booted
> [2016-09-22 13:48:18 +0000] [589] [INFO] Listening at: http://0.0.0.0:5600 (589)
> [2016-09-22 13:48:18 +0000] [589] [INFO] Using worker: gevent
> [2016-09-22 13:48:18 +0000] [594] [INFO] Booting worker with pid: 594
> [2016-09-22 13:48:18 +0000] [597] [INFO] Booting worker with pid: 597
> [2016-09-22 13:48:18 +0000] [600] [INFO] Booting worker with pid: 600
> [2016-09-22 13:48:18 +0000] [594] [DEBUG] Exception while loading the application
> Traceback (most recent call last):
>   File "/home/frank/.pyenv/versions/2.7.12/envs/env2712/lib/python2.7/site-packages/gunicorn/arbiter.py", line 557, in spawn_worker
>     worker.init_process()
>   File "/home/frank/.pyenv/versions/2.7.12/envs/env2712/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 190, in init_process
>     super(GeventWorker, self).init_process()
>   File "/home/frank/.pyenv/versions/2.7.12/envs/env2712/lib/python2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
>     self.load_wsgi()
>   File "/home/frank/.pyenv/versions/2.7.12/envs/env2712/lib/python2.7/site-packages/gunicorn/workers/base.py", line 136, in load_wsgi
>     self.wsgi = self.app.wsgi()
>   File "/home/frank/.pyenv/versions/2.7.12/envs/env2712/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
>     self.callable = self.load()
>   File "/home/frank/.pyenv/versions/2.7.12/envs/env2712/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
>     return self.load_wsgiapp()
>   File "/home/frank/.pyenv/versions/2.7.12/envs/env2712/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
>     return util.import_app(self.app_uri)
>   File "/home/frank/.pyenv/versions/2.7.12/envs/env2712/lib/python2.7/site-packages/gunicorn/util.py", line 370, in import_app
>     raise AppImportError("Failed to find application: %r" % module)
> AppImportError: Failed to find application: 'engine_server'
> [2016-09-22 13:48:18 +0000] [594] [INFO] Worker exiting (pid: 594)

**Comment by jruizgit** [comment]
Hi, thanks for posting the question. The following code ran for me:

```python
from durable.lang import *
import durable.interface

with ruleset('nest'):
    @when_all(m.cc_n_all > 0)
    def rule_1(c):
        print('before: c.m: {0}'.format(c.m))

    @when_start
    def start_test(host):
        host.post('nest', { "sid": 1, "id": 1, "cc_n_all":15 })

main_host = create_host()
application = durable.interface.Application(main_host, None, None)
```

Save it into a file called test.py and in the same directory run:  

`gunicorn test:application`
