### ISSUE TITLE
null values in a JSON object  (Javascript)  fact or event component prevents match

### ISSUE THREAD

**Issue by waTeim** [jruizgit/rules#42]
Simply if a fact or an event contains **null** as one of the property values, matching the rule fails.  
### e.g. for

```
const durable = require('durable');
let M = durable.m, S = durable.s, C = durable.c;

whenAll:[M.token.ex()],
   run: function(c) {
     console.log(JSON.stringify(c.m));
   }
```

works

```
c.assert('a0', {id: id, eenvId: eenvId, token: true, tokenVal:somenonnullvalue});
```

doesn't work

```
c.assert('a0', {id: id, eenvId: eenvId, token: true, tokenVal:null });
```

**Comment by jruizgit** [comment]
Hi, thanks a lot for reporting the issue. The null logical operator support had not been implemented. I just did, defining null as a value, which property is to be different from any other value. I have uploaded a new durable_rules version to npm, gem and pypi.

**Comment by waTeim** [comment]
Good deal, however, the problem persists.  The problem is not that null can not be matched, but rather an error condition occurs (silently) when one of the properties of a fact is null; in the example above **tokenVal** is superfluous to the rule `M.token.ex()` but if it exists then the fact is not matched.  I don't have better debugging info as there is no error message or stacktrace.

**Comment by jruizgit** [comment]
Thanks for clarifying. I misunderstood the scenario. I found a bug in the code for context assert and post, as an object with a 'null' property value was not being copied correctly. I have pushed the fix and published a new build. The following code works for me now:

```javascript
const durable = require('../libjs/durable');
let M = durable.m, S = durable.s, C = durable.c;

durable.ruleset('a0', {
        whenAll: [M.token.ex()],
        run: function(c) {
            console.log(JSON.stringify(c.m));
            c.post({id: 2, token: true, tokenVal:null});
        }
    },
    function (host) {
        host.assert('a0', {id: 1, sid: 1, token: true, tokenVal:20});
    }
);

durable.runAll();
```

**Comment by waTeim** [comment]
Indeed this does appear to solve the problem.
