### ISSUE TITLE
Support for node 4.5.x?

### ISSUE THREAD

**Issue by loyaltymethods** [jruizgit/rules#46]
This is an amazingly cool engine. Only worry I have is that we are on node 4.5.0. Any plans on supporting this, or recommendations on how to test it before we jump in?

**Comment by jruizgit** [comment]
Hi, thanks a lot for the feedback. I have tested node 4.5.x, there are no known problems. I have tested 4.6.x as well. I did change and publish the package.json file with 4.6.x as the recommended engine (to be in sync with nodejs.org). 

Please let me know if you have any questions or concerns.
