### ISSUE TITLE
SID ?

### ISSUE THREAD

**Issue by DigiDino** [jruizgit/rules#48]
I am not able to grasp the meaning of SID here, say I have a url --> http://localhost:5000/a0/3
3 becomes the sid and it even replaces the existing sid in the payload. What's the purpose of this sid field ? secondly when I send a payload to  this url, http://localhost:5000/a0, without sid, it's supposed to post a new ruleset, but it just breaks for me. Please clear my doubts as I am totally bugged with the use of sid.

**Comment by jruizgit** [comment]
Hi, thank you for posting the question. A sid identifies an 'inference session', events posted or facts asserted to the same session (using the same sid) will be used to infer an action. Consider the ruleset:

```ruby
Durable.ruleset :test do
  when_all c.first = m.t == "purchase",
                 c.second = m.amount > first.amount,
                 c.third = m.amount > second.amount,
                 c.fourth = m.amount > (first.amount + second.amount + third.amount) / 3 do
    puts "-> " + first.amount.to_s 
    puts "-> " + second.amount.to_s
    puts "-> " + third.amount.to_s 
    puts "-> " + fourth.amount.to_s
  end
  when_start do
    post :test, {:id => 1, :sid => 1, :t => "purchase", :amount => 100}
    post :test, {:id => 2, :sid => 1, :t => "purchase", :amount => 200}
    post :test, {:id => 3, :sid => 1, :t => "purchase", :amount => 300}
    post :test, {:id => 4, :sid => 1, :t => "purchase", :amount => 250}
  end
end
```

Four messages are required to meet the criteria. One for each clause. The rules engine needs to remember the messages, which have met the criteria. A 'sid' identifies the state where the messages are stored.

**Comment by voodoo2345** [comment]
Thank you for your reply and for doing such a fantastic work! 
 it's a big help.
