### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by mjmare** [jruizgit/rules#5]
Intriguing package! Unfortunately getting started is a bit hard.

Although the docs (https://github.com/jruizgit/rules/blob/master/docs/py/reference.md) only tell us to install Redis I presumed a pip install durable was in order.
On PyPi I find 2 packages durable and durable_rules. Both fail to install.
Finally, the section "First App" is almost empty, but for a beginner probably the most relevant.

durable:
```
DEPRECATION: --no-install, --no-download, --build, and --no-clean are deprecated.  See https://github.com/pypa/pip/issues/906.
Downloading/unpacking durable
  Could not find any downloads that satisfy the requirement durable
Cleaning up...
No distributions at all found for durable
Storing debug log for failure in /Users/mjm/.pip/pip.log
```

durable_rules: 
```
DEPRECATION: --no-install, --no-download, --build, and --no-clean are deprecated.  See https://github.com/pypa/pip/issues/906.
Downloading/unpacking durable-rules
  Downloading durable_rules-0.31.16.tar.gz
  Running setup.py (path:/private/var/folders/wd/dw1f3w9x0xv2nm57vcs7z3g00000gn/T/pycharm-packaging0.tmp/durable-rules/setup.py) egg_info for package durable-rules
    
Downloading/unpacking werkzeug (from durable-rules)
Installing collected packages: durable-rules, werkzeug
  Running setup.py install for durable-rules
    building 'rules' extension
    clang -fno-strict-aliasing -fno-common -dynamic -I/usr/local/include -I/usr/local/opt/sqlite/include -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Isrc/rules -I/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/rulespy/rules.c -o build/temp.macosx-10.10-x86_64-2.7/src/rulespy/rules.o
    src/rulespy/rules.c:2:10: fatal error: 'rules.h' file not found
    #include <rules.h>
             ^
    1 error generated.
    error: command 'clang' failed with exit status 1
    Complete output from command /Users/mjm/Dropbox/Devel/Rules/venv/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/wd/dw1f3w9x0xv2nm57vcs7z3g00000gn/T/pycharm-packaging0.tmp/durable-rules/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/wd/dw1f3w9x0xv2nm57vcs7z3g00000gn/T/pip-2LrYKg-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/mjm/Dropbox/Devel/Rules/venv/bin/../include/site/python2.7:
    running install

running build

running build_py

creating build

creating build/lib.macosx-10.10-x86_64-2.7

creating build/lib.macosx-10.10-x86_64-2.7/durable

copying libpy/durable/__init__.py -> build/lib.macosx-10.10-x86_64-2.7/durable

copying libpy/durable/engine.py -> build/lib.macosx-10.10-x86_64-2.7/durable

copying libpy/durable/interface.py -> build/lib.macosx-10.10-x86_64-2.7/durable

copying libpy/durable/lang.py -> build/lib.macosx-10.10-x86_64-2.7/durable

running build_ext

building 'rules' extension

creating build/temp.macosx-10.10-x86_64-2.7

creating build/temp.macosx-10.10-x86_64-2.7/src

creating build/temp.macosx-10.10-x86_64-2.7/src/rulespy

clang -fno-strict-aliasing -fno-common -dynamic -I/usr/local/include -I/usr/local/opt/sqlite/include -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Isrc/rules -I/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/rulespy/rules.c -o build/temp.macosx-10.10-x86_64-2.7/src/rulespy/rules.o

src/rulespy/rules.c:2:10: fatal error: 'rules.h' file not found

#include <rules.h>

         ^

1 error generated.

error: command 'clang' failed with exit status 1

----------------------------------------
Cleaning up...
Command /Users/mjm/Dropbox/Devel/Rules/venv/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/wd/dw1f3w9x0xv2nm57vcs7z3g00000gn/T/pycharm-packaging0.tmp/durable-rules/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/wd/dw1f3w9x0xv2nm57vcs7z3g00000gn/T/pip-2LrYKg-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/mjm/Dropbox/Devel/Rules/venv/bin/../include/site/python2.7 failed with error code 1 in /private/var/folders/wd/dw1f3w9x0xv2nm57vcs7z3g00000gn/T/pycharm-packaging0.tmp/durable-rules
Storing debug log for failure in /Users/mjm/.pip/pip.log
```

**Comment by jruizgit** [comment]
Hi mjmare, thanks a lot for your interest in 'durable_rules'. Yes it should be 'pip install durable_rules' (durable was the name of the old package). However, as I kept all my focus on performance benchmarks, I haven't finished the Python package. Please give me a couple of days. I'll let you know when it is ready.

**Comment by mjmare** [comment]
Hi Jesus

Thanks for working on the project since a rules engine in python is really needed IMHO. There are some other projects but they seem abandoned or are very hard to understand. That’s why durable is so interesting. Hope you can work out the kinks. To make it more accessible to mere mortals like me, I hope you can provide a tutorial (distinct from the reference doc, which, currently, is a bit dense for me).

Kind regards

Marcel

**Comment by jruizgit** [comment]
Hi Marcel, I have uploaded a working build to PiPy (along with a wheel for OS X). I love Python, but packaging is so tricky... I updated the setup step in the doc. I'll work on adding a step by step tutorial. This might help you getting started: 

Now that your cache ready, let's write a simple rule:  

1. Start a terminal  
2. Create a directory for your app: `mkdir firstapp` `cd firstapp`  
3. In the new directory `sudo pip install durable_rules` (this will download durable_rules and its dependencies)  
4. In that same directory create a test.py file using your favorite editor  
5. Copy/Paste and save the following code:
  ```python
  from durable.lang import *
  with ruleset('test'):
      @when_all(m.subject == 'World')
      def say_hello(c):
          print ('Hello {0}'.format(c.m.subject))

      @when_start
      def start(host):
          host.post('test', {'id': 1, 'sid': 1, 'subject': 'World'})

  run_all()
  ```
7. In the terminal type `python test.py`  
8. You should see the message: `Hello World`  

Note: If you are using [Redis To Go](https://redistogo.com), replace the last line.
  ```python
  d.runAll([{'host': 'hostName', 'port': port, 'password': 'password'}]);
  ```

**Comment by mjmare** [comment]
On my local install (python3, brew installed redis, durable rules 0.31.23) I get this traceback:

Traceback (most recent call last):
  File "/Users/mjm/Dropbox/Devel/Rules/test.py", line 1, in <module>
    from durable.lang import *
  File "/Users/mjm/Dropbox/Devel/Rules/venv3/lib/python3.4/site-packages/durable/lang.py", line 1, in <module>
    import engine
ImportError: No module named 'engine'

**Comment by jruizgit** [comment]
Hi Marcel, thanks for trying this again. I'm sorry it still doesn't work. May I ask a few more questions?

1. I assume you did `pip install durable_rules`, did the package compile and install without errors?
2. If you do `ls /Users/mjm/Dropbox/Devel/Rules/venv3/lib/python3.4/site-packages/durable`, what do you see? Do you see engine.py in the directory?
3. Do you have python 2.7 installed? I'm surprised to see the package under python 3.4 (as right not it is only supported for 2.7)

Thanks,

**Comment by mjmare** [comment]
> On 15 Apr 2015, at 22:42, Jesus Ruiz <notifications@github.com> wrote:
> 
> Hi Marcel, thanks for trying this again. I'm sorry it still doesn't work. May I ask a few more questions?
> 
> I assume you did pip install durable_rules, did the package compile and install without errors?
Yes, no errors
> If you do ls /Users/mjm/Dropbox/Devel/Rules/venv3/lib/python3.4/site-packages/durable, what do you see? Do you see engine.py in the directory?
__init__.py  __pycache__  engine.py    interface.py lang.py

> Do you have python 2.7 installed? I'm surprised to see the package under python 3.4 (as right not it is only supported for 2.7)
You’re correct: it was python3. I have now installed python2 and it works. 

Will experiment further. 

Marcel

**Comment by jruizgit** [comment]
Cool, the package has all the right files and it is installing it correctly. For now only Python 2.7. Please let me know if you have any other questions.
