### ISSUE TITLE
npm install fails on Node 4.6.2

### ISSUE THREAD

**Issue by dpaczewski** [jruizgit/rules#50]
Hello.

Tried to launch the installer on clean installation of version 4.6.2 of node.js (Windows10 Pro) and if fails on node-gyp. Additional details can be found in the attached file.

`npm ERR! durable@0.36.45 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the durable@0.36.45 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the durable package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs durable
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls durable
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]
`

Best regards,
DP.
[npm-debug.txt](https://github.com/jruizgit/rules/files/587946/npm-debug.txt)

**Comment by jruizgit** [comment]
Hi, thanks for reporting the problem. Windows requires a few extra steps to enable building extensions written in C. Would you mind trying the following steps?

1. Install VC++ build tools (http://go.microsoft.com/fwlink/?LinkId=691132), make sure you select Windows 8.1 and Windows 10 SDKs (if you don't select both, the installer will set the ucrt path incorrectly and node-gyp build will fail)
2. Install Python 2.7 (https://www.python.org/downloads/) and add it to your PATH
3. npm config set python python2.7 (from cmd terminal)
4. npm config set msvs_version 2015 --global (from cmd terminal)

At this point you can do:

`npm install durable`

**Comment by dpaczewski** [comment]
Hi @jruizgit!

Link [http://go.microsoft.com/fwlink/?LinkId=691132](url) doesn't seem to work. What should I download?

Will this be OK?

[http://landinghub.visualstudio.com/visual-cpp-build-tools](url)

**Comment by dpaczewski** [comment]
@jruizgit - the installation worked, but the script doesn't seem to produce any output.

Here is the code:

`'use strict';

var d = require('durable');

var m = d.m, s = d.s, c = d.c, timeout = d.timeout;

d.ruleset('fraud1_0', {
		whenAll: [ m.amount.eq(null) ],
		run: function(c) {
			console.log('fraud1_0 detected ' + c.m.amount);
		}
	},
	function (host) {
		host.post('fraud1_0', {id: 1, sid: 1, amount: 200});
		host.post('fraud1_0', {id: 2, sid: 1, amount: null});
	}
);`

And here is the output:

> C:\Users\Darek\WebstormProjects\game>npm config set python python2.7

C:\Users\Darek\WebstormProjects\game>npm config set msvs_version 2015 --global

C:\Users\Darek\WebstormProjects\game>node test.js

C:\Users\Darek\WebstormProjects\game>

**Comment by jruizgit** [comment]
I'm sorry for the delay in my reply, I'm just catching up. I'm happy to hear the installation is working.

I think you are missing one line at the end:

```javascript
d.runAll();
```

The last line will fail if you don't have a redis server running in the localhost port 6379. If you are using a redis server in a different host:

```javascript
d.runAll({host: hostName, port: portNumber , password:null}]);
```
