### ISSUE TITLE
Timers Example Failing

### ISSUE THREAD

**Issue by burkaygur** [jruizgit/rules#51]
I am trying to run the timer example from the docs and 5 seconds later getting this error on the local server:

peekTimers err string ERR Error running script (call to f_41deee5150afc8fbc6364545d32fe6ce92c385d4): @user_script:6: @user_script: 6: Lua redis() command arguments must be strings or integers
unexpected error Could not assert timers, error code: 302
peekTimers err string ERR Error running script (call to f_41deee5150afc8fbc6364545d32fe6ce92c385d4): @user_script:6: @user_script: 6: Lua redis() command arguments must be strings or integers
unexpected error Could not assert timers, error code: 302
peekTimers err string ERR Error running script (call to f_41deee5150afc8fbc6364545d32fe6ce92c385d4): @user_script:6: @user_script: 6: Lua redis() command arguments must be strings or integers
unexpected error Could not assert timers, error code: 302
peekTimers err string ERR Error running script (call to f_41deee5150afc8fbc6364545d32fe6ce92c385d4): @user_script:6: @user_script: 6: Lua redis() command arguments must be strings or integers
unexpected error Could not assert timers, error code: 302
peekTimers err string ERR Error running script (call to f_41deee5150afc8fbc6364545d32fe6ce92c385d4): @user_script:6: @user_script: 6: Lua redis() command arguments must be strings or integers
unexpected error Could not assert timers, error code: 302
peekTimers err string ERR Error running script (call to f_41deee5150afc8fbc6364545d32fe6ce92c385d4): @user_script:6: @user_script: 6: Lua redis() command arguments must be strings or integers
unexpected error Could not assert timers, error code: 302

**Comment by jruizgit** [comment]
Hi, thanks a lot for reporting this issue. There was an incompatibility issue with redis 3.2.5. I have published a new node.js, python and ruby version (0.36.46, 0.33.76 and 0.34.13 respectively).

**Comment by burkaygur** [comment]
Thank you very much for the quick response. Will try out asap. Really loving this project.
