### ISSUE TITLE
Choice of Sequences Example Not Working Properly?

### ISSUE THREAD

**Issue by burkaygur** [jruizgit/rules#52]
Not sure, if this is working properly. From the description the rule should fire only when A && B || C && D but it fires only when A is true.

**Comment by jruizgit** [comment]
That is correct, the rule should fire when both A and B are satisfied or C and D are satisfied. I just tried the example in node.js, Python and Ruby. It seems to work fine. Would you mind pasting the scenario that does not work for you?

**Comment by burkaygur** [comment]
I have been playing with that example, and trying to wrap my head around it. It looks like when I send:

amount: 10,000
subject: jumbo

in any order after n many events, it always matches. Similarly with approve and 1,000. In any order, these two events get paired up. Is this the expected behavior?

Now the question is, I can use the same 'id' to send two events with different parameters within the same sid. Is that normal behavior? That means I can have two events sharing the same id with different event parameters?

**Comment by jruizgit** [comment]
Hi, thanks for reporting this issue. Let me try your scenario and I will report back. The same id should not be used. When an event is accepted, the API will return 0 otherwise it will return 1. If you are using the REST API, the Post call will return a JSON object with the call outcome ({ "outcome":1 }).

**Comment by burkaygur** [comment]
Any updates on this @jruizgit ? Thank you for your help!

**Comment by jruizgit** [comment]
Hi, I have been testing the scenario. Two events with the following properties in any order should always match.  

amount: 10,000
subject: jumbo

The all operator means all events that match in any order. Any operator means any of the events that match. Are you seeing different behavior, would you mind pasting your code so I can better understand your scenario?
