### ISSUE TITLE
Redis cannot specify DB?

### ISSUE THREAD

**Issue by TracyDa** [jruizgit/rules#54]
Hi ,I've been using durable rules for several weeks,and here is my problem,I want to run two or more servers and choose different redis DB,but I can not find how to specify the redis DB?
Is there anyway to set this?
Ths.

```
def run_all(databases = [{'host': 'localhost', 'port': 6379, 'password':None}], host_name = '127.0.0.1', port = 5000, routing_rules = [], run = None, state_cache_size = 1024):
    main_host = create_host(databases, state_cache_size)
    main_app = interface.Application(main_host, host_name, port, routing_rules, run)
    main_app.run()
```

**Comment by jruizgit** [comment]
Hi, thanks for posting your question. The `runAll` function takes an array of objects, which define how to access the DB. The host member is the IP or the DNS address of the DB, you can also specify port and password. If you specify multiple DBs, the state will be sharded across the databases using `sid` as key.

```javascript
var d = require('durable');
var m = d.m, s = d.s, c = d.c;

d.ruleset('a1', {
        whenAll: [ m.amount.eq(200) ],
        run: function(c) {
            console.log(c.m.amount);
        }
    },
    function (host) {
        host.post('a1', {id: 1, sid: 1, amount: 200});
    }
);

d.runAll([{host: 'dnshostname'}]);
```

**Comment by TracyDa** [comment]
@jruizgit  Thanks for your reply,but it still confused me.

There are `id` and `sid` in parameters to run my rules,but I want to add a test server,I mean they will have two or more same name method.And I've tried to run two rule servers,when I call the rules,one server always give me `INIT` status.I think the reason is that both of them store data to redis db 0,so I started two redis with different port and they all work well.

I'm using Python2.Can I run the rules server with specific redis db,like this?

`run_all(databases = [{'host': 'localhost', 'port': 6379, ,db=0}]`

If so,can you give me a demo Python script?

Thank you.

**Comment by jruizgit** [comment]
Oh, I see, I'm sorry I misunderstood your question. Right now, there is no way to select the Redis db. Adding the support is pretty simple. I'll look into this in a couple of days.

Thanks.

**Comment by TracyDa** [comment]
@jruizgit  Thank you so much ,I really appreciate it.

**Comment by jruizgit** [comment]
Hi I have added support for db selection. For example, if you want to select db #1:

**Python**
```python
run_all([{'host': 'localhost', 'port': 6379, 'db': 1}])
```
**Ruby**
```ruby
Durable.run_all [{:host => 'localhost', :port => 6379, :db => 1}]
```
**Node.js**
```javascript
d.runAll([{host: 'localhost', port: 6379, db: 1}])
```

I have pushed the change to the master branch and published to npm, PyPi and gem.

**Comment by TracyDa** [comment]
@jruizgit  Thanks.
