### ISSUE TITLE
Python installation faild on Windows10

### ISSUE THREAD

**Issue by MET92** [jruizgit/rules#55]
Hello Jesus

I am very interested by your package.
I am trying to install durable_rules on Windows 10 with Python 2.7 and it is unfortunately long and painful. (I understand that Window is not the favorite environment of Python)

I have intalled redis & werkzeug as advised. I have also installed VC++2008 compiler to keep some comptability with the Python libraries and have also VC++2012 compiler.

The log of my installation is 

C:\WINDOWS\system32>pip install durable_rules
Collecting durable_rules
  Using cached durable_rules-0.33.76.tar.gz
Requirement already satisfied: werkzeug in c:\python27\lib\site-packages (from durable_rules)
Building wheels for collected packages: durable-rules
  Running setup.py bdist_wheel for durable-rules ... error
  Complete output from command c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\mdethuy\\appdata\\local\\temp\\pip-build-tmix3a\\durable-rules\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d c:\users\mdethuy\appdata\local\temp\tmprnzjolpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-2.7
  creating build\lib.win-amd64-2.7\durable
  copying libpy\durable\engine.py -> build\lib.win-amd64-2.7\durable
  copying libpy\durable\interface.py -> build\lib.win-amd64-2.7\durable
  copying libpy\durable\lang.py -> build\lib.win-amd64-2.7\durable
  copying libpy\durable\__init__.py -> build\lib.win-amd64-2.7\durable
  running build_clib
  building 'rules_py' library
  creating build\temp.win-amd64-2.7
  creating build\temp.win-amd64-2.7\deps
  creating build\temp.win-amd64-2.7\deps\hiredis
  creating build\temp.win-amd64-2.7\src
  creating build\temp.win-amd64-2.7\src\rules
  _C:\Users\mdethuy\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG /Tcdeps/hiredis/hiredis.c /Fobuild\temp.win-amd64-2.7\deps/hiredis/hiredis.obj
  hiredis.c
  c:\users\mdethuy\appdata\local\temp\pip-build-tmix3a\durable-rules\deps\hiredis\hiredis.h(38) : fatal error C1083: Cannot open include file: 'sys/time.h': No such file or directory
  error: command 'C:\\Users\\mdethuy\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2_

  ----------------------------------------
  Failed building wheel for durable-rules
  Running setup.py clean for durable-rules
Failed to build durable-rules
Installing collected packages: durable-rules
  Running setup.py install for durable-rules ... error
    Complete output from command c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\mdethuy\\appdata\\local\\temp\\pip-build-tmix3a\\durable-rules\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\mdethuy\appdata\local\temp\pip-fpsmku-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-2.7
    creating build\lib.win-amd64-2.7\durable
    copying libpy\durable\engine.py -> build\lib.win-amd64-2.7\durable
    copying libpy\durable\interface.py -> build\lib.win-amd64-2.7\durable
    copying libpy\durable\lang.py -> build\lib.win-amd64-2.7\durable
    copying libpy\durable\__init__.py -> build\lib.win-amd64-2.7\durable
    running build_clib
    building 'rules_py' library
    creating build\temp.win-amd64-2.7
    creating build\temp.win-amd64-2.7\deps
    creating build\temp.win-amd64-2.7\deps\hiredis
    creating build\temp.win-amd64-2.7\src
    creating build\temp.win-amd64-2.7\src\rules
    C:\Users\mdethuy\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG /Tcdeps/hiredis/hiredis.c /Fobuild\temp.win-amd64-2.7\deps/hiredis/hiredis.obj
    hiredis.c
    c:\users\mdethuy\appdata\local\temp\pip-build-tmix3a\durable-rules\deps\hiredis\hiredis.h(38) : fatal error C1083: Cannot open include file: 'sys/time.h': No such file or directory
    error: command 'C:\\Users\\mdethuy\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\mdethuy\\appdata\\local\\temp\\pip-build-tmix3a\\durable-rules\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\mdethuy\appdata\local\temp\pip-fpsmku-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\mdethuy\appdata\local\temp\pip-build-tmix3a\durable-rules\

C:\WINDOWS\system32>

It seems that "sys/time.h" is required but for Windows the library is time.h
I tried to change it but always the same error.

Have you any idea ?

Thank you for your help

**Comment by SDMitchell** [comment]
I had this problem last week and assumed it was something I was doing wrong. It looks like it is trying to compile the *nix version of Redis in the Windows environment (unistd.h, sys/time.h, etc are all *nix headers).

If you need to get up and going in a hurry (because you are evaluating Durable, for example) it runs perfectly fine if you install it inside Bash for Windows:

sudo apt-get install python-pip
sudo apt-get install python-dev
pip install durable_rules

I'm not claiming we aren't doing something wrong, but I was in a hurry and forgot to attempt to solve the problem on my end. Hope this helps you or somebody, at least.

**Comment by jruizgit** [comment]
Thanks for reporting this problem. Yes, the setup.py file is compiling the *nix version, it should be setting the _WIN32 flag and referencing the hiredis_win library. I'll work on fixing this tomorrow. 

Using Bash for windows is a nice workaround for evaluation purposes.

**Comment by MET92** [comment]
Thank to both of you for your workaround and support.

I come to the same conclusion when I was trying to install the ruby version. It gives me equivalent errors on redis with a non-Windows library referenced

------------------------------------------
C:\Ruby23-x64\lib\ruby>gem install durable_rules
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing durable_rules:
        ERROR: Failed to build gem native extension

current directory: C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/durable_rules-0.34.13/src/rulesrb
C:/Ruby23-x64/bin/ruby.exe -r ./siteconf20170114-8220-bnzr6v.rb extconf.rb
gcc -std=c99 -pedantic -c -O3 -fPIC  -Wall -W -Wstrict-prototypes -Wwrite-strings -g -ggdb  net.c

net.c:1:0: warning: -fPIC ignored for target (all code is position independent) [enabled by default]

```
net.c:37:24: fatal error: sys/socket.h: No such file or directory

compilation terminated.
make: *** [net.o] Error 1
*** extconf.rb failed ***

```
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby23-x64/bin/$(RUBY_BASE_NAME)
extconf.rb:23:in `block in <main>': Building hiredis failed (RuntimeError)
        from extconf.rb:21:in `chdir'
        from extconf.rb:21:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/durable_rules-0.34.13 for inspection.
Results logged to C:/Ruby23-x64/lib/ruby/gems/2.3.0/extensions/x64-mingw32/2.3.0/durable_rules-0.34.13/gem_make.out

Kind regards,
