### ISSUE TITLE
Can't build it on Mac OS 10.11.6

### ISSUE THREAD

**Issue by azraelwillson** [jruizgit/rules#56]
Hello,
i very appreciate your job, it's a very nice tools and it's perfect for my project.
I installed it on my virtual OS(linux) and it went well, but when I install it on my mac, there is a problem.

command  
`#python ./setup.py build`

and it reports build failure error as below
```
ar: build/temp.macosx-10.11-intel-2.7/librules_py.a is a fat file (use libtool(1) or lipo(1) and ar(1) on it)
ar: build/temp.macosx-10.11-intel-2.7/librules_py.a: Inappropriate file type or format
error: command 'ar' failed with exit status 1
```

ToT

**Comment by jruizgit** [comment]
Hi, thank you for reporting this problem. I have tried building durable_rules for Python in 10.11 and 10.12. The build succeeded in both cases. Can you please verify you are running the latest version of XCode command line tools?

**Comment by azraelwillson** [comment]
Hi, the latest version of XCode command line tools was installed, though I cannot build it, i still can install it through pip. Still don't know the root cause of that failure.

**Comment by jruizgit** [comment]
Cleaning up issues. Closing this one as no further action is required.
