### ISSUE TITLE
Scaling question

### ISSUE THREAD

**Issue by dkhan11** [jruizgit/rules#59]
Hi,

Thank you for this great effort! 

I have tried to understand from the docs how rules scales. 
Lets say that I define a flowchart with different stages and each state propagates the event to others. Just like you have in the example here:
https://github.com/jruizgit/rules/blob/master/docs/py/reference.md#flowchart

1. Does the response/state from each stage is routed thru queues in Redis? 
2. Can I really scale this horizontally?  meaning if I have several servers running it with the same Redis server, will it distribute the load between servers? is it possible that one stage will run on server A while stage two will run on another?

Thank you in advance,
DD.

**Comment by jruizgit** [comment]
Hi, thank you for posting the question. For all rulestes (including flowchart), the state is checkpointed (stored in redis) after an action is executed. In addition an event is emitted so you can write rules to reason about the state. In the case of flowchart, a stage is an action execution.

If the same ruleset is run in multiple hosts, using the same redis instance, actions will be executed in any host (the first available). The framework guarantees a single action execution at any point in time for a given sid (state id). An action will be considered abandoned after 15 seconds.


On Jan 26, 2017, at 1:30 AM, dkhan11 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

Thank you for this great effort!

I have tried to understand from the docs how rules scales.
Lets say that I define a flowchart with different stages and each state propagates the event to others. Just like you have in the example here:
https://github.com/jruizgit/rules/blob/master/docs/py/reference.md#flowchart

  1.  Does the response/state from each stage is routed thru queues in Redis?
  2.  Can I really scale this horizontally? meaning if I have several servers running it with the same Redis server, will it distribute the load between servers? is it possible that one stage will run on server A while stage two will run on another?

Thank you in advance,
DD.

-

**Comment by dkhan11** [comment]
I see. Great job and thank you for the fast response!!!
