### ISSUE TITLE
Refer to Lists in rules

### ISSUE THREAD

**Issue by dkhan11** [jruizgit/rules#60]
Hi,

Is there a way to post and refer to data that contains lists? something like:
host.post('test', {'id': 1, 'sid': 1, 'subjects': ['World', 'News', 'Sports']})
I can see that if I'm posting such data it just being disregarded without any error.

Also, if it is possible, can I refer to those lists inside rules? for example, can I refer to the list length inside a rule declaration?

Thank you for all your work!
DD.

**Comment by jruizgit** [comment]
Hi, thanks for posting the question. The data in the object should not be lost (if it is lost, it is a bug, I'll take a look). There are no rules operators over arrays yet, there is a number of scenarios which require length and contains. I'll add that to the list of pending work.

Sent from my iPhone

On Jan 30, 2017, at 8:03 AM, dkhan11 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

Is there a way to post and refer to data that contains lists? something like:
host.post('test', {'id': 1, 'sid': 1, 'subjects': ['World', 'News', 'Sports']})
I can see that if I'm posting such data it just being disregarded without any error.

Also, if it is possible, can I refer to those lists inside rules? for example, can I refer to the list length inside a rule declaration?

Thank you for all your work!
DD.

-

**Comment by dkhan11** [comment]
Cool, thanks for adding it to the pending work!
I have tried to open the debugger with this simple example and the array data(mydata in the post request) is always None. I would love if it can be fixed. I'm using the latest version, using pip install.

from durable.lang import *
with ruleset('test'):
    @when_all(m.subject == 'World')
    def say_hello(c):
        print ('Hello {0}'.format(c.m.subject))

    @when_start
    def start(host):
        host.post('test', {'id': 1, 'sid': 11221, 'subject': 'World', 'mydata': ['World','games']})

run_all()

**Comment by dkhan11** [comment]
Would love to see that fix...

**Comment by jruizgit** [comment]
Hi, I have this item in my list of work. It will take me a couple more days.


Thanks,


JR


________________________________

**Comment by jruizgit** [comment]
Hi, I just tried your scenario. It actually preserves the data. Please note the whole object is contained in the variable `c.m`. The code below works for me:

```python
with ruleset('test'):
    @when_all(m.subject == 'World')
    def say_hello(c):
        print ('Hello {0}'.format(len(c.m.mydata)))

    @when_start
    def start(host):
        host.post('test', {'id': 1, 'sid': 11221, 'subject': 'World', 'mydata': ['World','games']})

run_all()
```
run_all()

**Comment by dkhan11** [comment]
Thank you! I will test your code and let you know.

**Comment by harsha20-creator** [comment]
hi @jruizgit, I have a question on how to access the fields/attributes that are part of nested json. Eg here is my json 
{"choclate": [{"snickers": "peanut", "kitkat": "peanut1"}]}
so if i do c.m.choclate[0].snickers so that it should print peanut.. but its not doing that.. Can we retrieve individual attributes that are nested
