### ISSUE TITLE
Testing dynamic rules

### ISSUE THREAD

**Issue by dkhan11** [jruizgit/rules#61]
Hi,

I'm trying to use your testdynamic.py and I have another question.
I can see that in the form that submits the new rule has the following syntax for a "run" statement:
 "run": "suspect"

And whenever the state chart reaches that point, I can see that the console prints "Executing " and the the value of the "run" field. I tried to understand how the get_action function works but I'm still puzzled...
Can the run statement really contain runnable function, just like in the regular state chart definition?

Also, it is a little bit buggy... not sure if all the tests run fine.

Thanks in advance for a great piece of software!
DD.

**Comment by jruizgit** [comment]
Hi, thanks for asking the question. The ruleset definition in JSON is purely declarative and is always executed by the C engine. The action execution is delegated to the scripting language. The python Host class has two extensibility points for managing Rulesets defined in JSON and one for resolving action names to functions. The get_action function will get the string defined in the "run" property of the JSON ruleset. It is up to you to translate such string into a function (for instance, you can store the functions in a dictionary and look them up when get_action is called). In the the test_dynamic example, all strings are translated to the same function, which really only prints out the "run" string.

```python
class Host(engine.Host):

    def get_action(self, action_name):
        def print_lamba(c):
            c.s.label = action_name
            print('Executing {0}'.format(action_name))
        return print_lamba;

    def load_ruleset(self, ruleset_name):

    def save_ruleset(self, ruleset_name, ruleset_definition):

```

**Comment by dkhan11** [comment]
Thank you for the fast answer. 
Got it. Well planned. I will test it.
DD.
