### ISSUE TITLE
Issue with regular expressions

### ISSUE THREAD

**Issue by jgluna** [jruizgit/rules#64]
Hello.

I have an issue with the matches statement in the Ruby implementation. Here is the code:

```
Durable.ruleset :split_string do
  when_all (m.subject.matches("/.*?(\d{2}-?\w{3}-?\d{2}\/)?-?(\w{3,6}\*?)(-\d{8})?-(\w{4})(-\d{4})?-(\w{1}).*/")) do
    splitted = m.subject.split("//").select{|segment| segment.match(/.*?(\d{2}-?\w{3}-?\d{2}\/)?-?(\w{3,6}\*?)(-\d{8})?-(\w{4})(-\d{4})?-(\w{1})/)}
    i=1
    splitted.each do |segment|
      post :process_string,{:id=>m.id, :sid=>m.sid.to_s+i.to_s, :segment=>segment}
      i=i+1
    end
  end
  when_start do
    post :split_string, {:id=>1, :sid=>2, :subject =>"AAA/CV/KK:01ENE01//ABCCDE*-CVCV-X//GTY-CVCV-X//XYZ-CVCV-X//TRE-CVCV-X//HUK*-CVCV-X//ABC-CVCV-U//N"}
  end
end

Durable.ruleset :process_string do
  when_all (m.segment !="") do
    puts "segment => #{m.segment}"
  end
end

Durable.run_all
```

The regular expression at the when_all statement in the :split_string rule is working regularly in ruby but not in here, actually, the application stalls when the rules are being loaded.

Is there a way to use regular expressions? Or, if it's something else, it would be nice to have it in the documentation.

I'm using 
Ruby version 2.4.0
Durable rules version 0.34.19

**Comment by jruizgit** [comment]
Hi, thanks a lot for posting the question. durable_rules implements a simple pattern matching dialect. Similar to lua, it uses % to escape, which vastly simplifies writing expressions. Expressions are compiled down into a deterministic state machine, thus expressiveness of the dialect is not as rich as ruby, python or jscript. Event processing is O(n) guaranteed (n being the size of the event). 

I fixed a few bugs in the pattern matching code this week. I just published a new version this morning. I recommend you use this new version. This is what is supported by pattern matching:

**Repetition**
\+ 1 or more repetitions
\* 0 or more repetitions
? optional (0 or 1 occurrence)

**Special**
() group
| disjunct
[] range
{} repeat

**Character classes**
.	all characters
%a	letters
%c	control characters
%d	digits
%l	lower case letters
%p	punctuation characters
%s	space characters
%u	upper case letters
%w	alphanumeric characters
%x	hexadecimal digits

I changed your expression just a little bit, the code below worked for me:

```ruby
require "durable"
Durable.ruleset :split_itinerary do
  when_all (m.subject.matches(".*(/(%d{2}-?%w{3}-?%d{2}/)?-?(%w{3,6}%*?)(-%d{8})?-(%w{4})(-%d{4})?-(%w{1})/)+.*")) do
    splitted = m.subject.split("//").select{|segment| segment.match(/.*?(\d{2}-?\w{3}-?\d{2}\/)?-?(\w{3,6}\*?)(-\d{8})?-(\w{4})(-\d{4})?-(\w{1})/)}
    i=1
    splitted.each do |segment|
      post :domestic_trip,{:id=>m.id, :sid=>m.sid.to_s+i.to_s, :segment=>segment}
      i=i+1
    end
  end
  when_start do
    post :split_itinerary, {:id=>1, :sid=>2, :subject =>"/SYDADL*-QFQF-X//PER-QFQF-X//BME-QFQF-X//DRW-QFQF-X//BNE*-QFQF-X//SYD-QFQF-U//N"}
    post :split_itinerary, {:id=>2, :sid=>2, :subject =>"/23-wer-33/345*-12345678-1234-1234-w/"}
  end
end

Durable.ruleset :domestic_trip do
  when_all (m.segment !="") do
    puts "segment => #{m.segment}"
  end
end

Durable.run_all
```

**Comment by jgluna** [comment]
Hi, sorry for the late response.

Is working fine with this documentation so I'm closing this issue, but it will be nice if it's added to the main documentation of the project.

Thank you.
