### ISSUE TITLE
Rules are not executing more than once

### ISSUE THREAD

**Issue by DareUrDream** [jruizgit/rules#67]
HI,

I have the below test code 
```
import notifier
from durable.lang import *

with ruleset('testrules'):

    @when_all(m.subject == 'World')
    def patternABC(c):
        print('Hello {0}'.format(c.m.subject))
        notify("Pattern ABC Found")
        
    @when_all(m.subject == 'Worlds')
    def patternABCD(c):
        print("In Worlds")
        notify("Pattern ABCD Found")
    
    @when_all(+s.exception)
    def exception_handler(c):
        print('Error message: {0}'.format(c.s.exception))
        c.s.exception = None

run_all()
```

When i execute the below request 

`curl -H "Content-type: application/json" -X GET -d '{"id": 1, "subject": "World"}' http://localhost:5000/testrules2/1`

for the very first time "Hello World" is printed in the console and output is {outcome:0}. But for subsequent requests the method is not executed and I don't see the output in the console and the output is {outcome:212}.

In my use-case I would like to get the function executed everytime the pattern matches. Request you to please guide.

Thanks,
DareUrDream

**Comment by jruizgit** [comment]
Hi, thanks for posting the question. `{outcome:212}` means the event has already been observed. Every event is expected to have a different `id`.

**Comment by DareUrDream** [comment]
HI,

Thanks for your quick response.

@jruizgit As i am building a log analysis tool based on pattern matching, same log lines would be parsed over and over again. Could you please tell me what should I do so that the function is executed if the passed data matches the defined pattern?

Thanks,
DareUrDream

**Comment by manoj8385** [comment]
In my case, the script is running indefinitely without producing any result.

**Comment by jruizgit** [comment]
Hi, thanks for reporting the issue, would you mind pasting your code sample, I would like to debug the problem?

Sent from my iPhone

On Mar 20, 2017, at 8:17 PM, Manoj Jayabalan <notifications@github.com<mailto:notifications@github.com>> wrote:


In my case, the script is running indefinitely without producing any result.

**Comment by manoj8385** [comment]
I tried executing the sample codes given in your github. 

As I understand from your comment given above, ID should not be repeated, If I execute code more than once, the script running indefinitely. without producing the outcome:212.

IDE: PhyCharm community Edition
OS: Windows 10
Python version 3.5.2 installed 

Thanks a lot for your package. It saved me a lot.

**Comment by jruizgit** [comment]
Hi, I tried the samples provided in the readme and they work fine. Which sample did you try? Does it produce any output at least once? I noticed you are using Windows, what redis server are you using?

Thanks,

**Comment by manoj8385** [comment]
Hi, I have installed Redis-x64-3.2.100.

Please find the attached file for the codes not working. 
[Rules.docx](https://github.com/jruizgit/rules/files/866375/Rules.docx)

**Comment by jruizgit** [comment]
Hi, thanks a lot for reporting the problems. I have updated the samples in the docs. As the framework has evolved, I did not keep the docs up to date. All samples should work now.

**Comment by DareUrDream** [comment]
@jruizgit Thanks a lot for the update.
