### ISSUE TITLE
symbol issue 

### ISSUE THREAD

**Issue by agale031176** [jruizgit/rules#7]
Hi 

When I am trying to use this I am getting the following error on an Ubuntu box:

ImportError: /home/aaron/.virtualenvs/rules2/local/lib/python2.7/site-packages/rules.so: undefined symbol: redisFormatCommandArgv

Any ideas what could be wrong here?

**Comment by jruizgit** [comment]
Hi, thanks for the feedback. Let me look into this. I'll get back to you soon.

**Comment by jruizgit** [comment]
This should work now. I just tried it using an AWS instance. To get this to work I changed:

1. Passed the right compiler options in setup.py
2. Compiled rules and hiredis into a single library
3. Changed the order of arguments in pyBindRuleset (to workaround a bug in PyArg_ParseTuple
