### ISSUE TITLE
Query - Wildcard pattern matching OR contains check

### ISSUE THREAD

**Issue by DareUrDream** [jruizgit/rules#70]
HI,

How could I have **_contains_** like check in the rules. In my below use-case, I would like to print any string that have 'James Bond' in it ( case-insensitive **contains/contains_i** )

```
@when_all(m.text.matches('James Bond'))
    def say_hello(c):
        print (c.m.text)
```
My expectation is the below statements would be evaluated to true.

1. James Bond movies are great.
2. Die another Day is a James Bond movie

**Comment by jruizgit** [comment]
Hi, thanks for posting the question. The pattern can be expressed as follows:

```python
from durable.lang import *

with ruleset('a0'):
    @when_all(m.text.matches('.*(J|j)(A|a)(M|m)(E|e)(S|s) (B|b)(O|o)(N|n)(D|d).*'))
    def say_hello(c):
        print (c.m.text)

    @when_start
    def start(host):
        host.post('a0', {'id': 1, 'sid': 1, 'text': 'Contains the James Bond name'})
        host.post('a0', {'id': 2, 'sid': 1, 'text': 'Contains the james bond name'})
        host.post('a0', {'id': 3, 'sid': 1, 'text': 'James Bond movies are great.'})
        host.post('a0', {'id': 4, 'sid': 1, 'text': 'Die another Day is a James Bond movie'})
        host.post('a0', {'id': 5, 'sid': 1, 'text': 'Does not contain'})

run_all()
```

**Comment by DareUrDream** [comment]
Hi,

Thanks for you answer. I have tried this approach but it is very tedious to do the same for long text based rules and on top if you want to do case insensitive then the complexity increases further. 

Cheers,

**Comment by jruizgit** [comment]
Hi, I'm planning to add explicit support for contains/starts_with/ends_with functions. I will do that after completing the javascript syntax project.

**Comment by DareUrDream** [comment]
@jruizgit, Thanks a lot for the update

**Comment by jruizgit** [comment]
Hi, I have added support for case insensitive match. Please use version `0.33.103`. The example below shows how it works:

```python
from durable.lang import *

with ruleset('imatch'):
    @when_all(m.text.imatches('.*James bond.*'))
    def say_hello(c):
        print (c.m.text)

    @when_start
    def start(host):
        host.post('imatch', { 'text': 'Contains the James Bond name' })
        host.post('imatch', { 'text': 'Contains the james bond name' })
        host.post('imatch', { 'text': 'James Bond movies are great. James' })
        host.post('imatch', { 'text': 'Die another Day is a James Bond movie '})
        host.post('imatch', { 'text': 'Does not contain' })


run_all()
```

**Comment by DareUrDream** [comment]
@jruizgit.Thanks a lot for the update. I will check and get back to it
