### ISSUE TITLE
Weird issue with parsing when there is 'u' in a specific location/word combintion.

### ISSUE THREAD

**Issue by DareUrDream** [jruizgit/rules#71]
```
@when_all(m.logLine.matches('.*(usage manager memory limit).*'))
    def liveDataSlowConsumer(c):
        msg = 'usage memory limit'
        task = Task(msg)
        publish(task)
```

`{"id": millis(), "logLine": '8490899: nov 03 09:19:06.003 cst %mivr-ss_rmcm-7-unk:usage manager memory limit (134217728) reached.Stopping prodA'}`

In the above json data if we replace 'A' in the word 'prodA' with 'u' the rule does not work otherwise the rule works beautifully.

`{"id": millis(), "logLine": '8490899: nov 03 09:19:06.003 cst %mivr-ss_rmcm-7-unk:usage manager memory limit (134217728) reached.stopping aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'}`

In the above json data if we add 'u' the rule does not work otherwise the rule works beautifully whatever you add.

**Comment by jruizgit** [comment]
Hi, thank you for reporting this problem. I confirmed there is a bug in when generating the DFA for expressions starting and finishing with `.*` . I will be fixing it in the next few days.

**Comment by jruizgit** [comment]
Hi, I have published a fix for this problem. Please use version `0.33.102`.

**Comment by DareUrDream** [comment]
@jruizgit Thanks a lot for the update. I will check and get back to it
