### ISSUE TITLE
SID creation from a field value

### ISSUE THREAD

**Issue by thomasknowles** [jruizgit/rules#77]
I don't know if this is possible, but I would like to know if it is possible to be able to generate the state (which I am presuming is derived by the use of the SID) using another field. 

For example: if I am tracking usernames on a website or a system, I would like the context to be derived by that username {user: "thomasknowles", action: "FailedAuthentication"}, at the moment I am finding it difficult to implement such logic.

Thanks.

Also, great job on durable-rules.

**Comment by jruizgit** [comment]
Hi, thanks for posting the question. Right now the only way to identify the state is by using 'sid'. In your example above you would need to assert facts or post events like this: `{sid:"thomasknowles", action:"FailedAuthentication"}`.

**Comment by thomasknowles** [comment]
Thank you, I'll close this.
