### ISSUE TITLE
durable_rules lambda aws

### ISSUE THREAD

**Issue by ammarwm** [jruizgit/rules#78]
Hi,

is it possible to use durable_rules in a lambda function ?

thank you for the great work

**Comment by jruizgit** [comment]
Hi, thank you for your interest in durable_rules. Would you mind describing the scenario you have in mind? I imagine running a ruleset inside a lambda function could work, but it might not be super efficient as the ruleset would be loaded on every lambda execution. An alternative would be to host the ruleset in an EC2 instance and send notifications using http or the queue API.

**Comment by ammarwm** [comment]
Hi,
I am currently hosting the ruleset in EC2 and sending notifications. But I am implementing serverless architecture. So different rulesets could sit in different lambdas and I call the lambdas through API gateway in aws. But could not be straightforward to install as well.
