### ISSUE TITLE
Cannot build properly under windows & compatiblity with nodejs 4.x.x, 5.x.x

### ISSUE THREAD

**Issue by williamwsmith** [jruizgit/rules#8]
This an extremely interesting project.
For some time have been using and modifying
NOOLS.
https://github.com/c2fo/nools

However your solution with Redis persistence is much more scalable.
Nice to see if these two projects could combine forces.

**Comment by jruizgit** [comment]
Hi William, thanks a lot for reporting this issue. I will look into it. 

Thanks for your suggestion, I appreciate your insight. Even though nools and durable_rules have different architectures, nools provides nice support for the purely declarative rules language, which is not available in durable_rules. What is your perspective? How would a combined solution look like?

**Comment by jruizgit** [comment]
Hi William, I'm sorry for the delay on this. Quick update on your issue. Windows should be working now. Please note you will need to install VC++ tools as npm need to compile the native Node.js extension on download.   

1. Install VC++ build tools (http://go.microsoft.com/fwlink/?LinkId=691132), make sure you select Windows 8.1 and Windows 10 SDKs (if you don't select both, the installer will set the ucrt path incorrectly and node-gyp build will fail) 
2. Install Python 2.7 (https://www.python.org/downloads/) and add it to your PATH
3. npm config set python python2.7 (from cmd terminal)
4. npm config set msvs_version 2015 --global (from cmd terminal) 

At this point you can do:

- npm install durable
