### ISSUE TITLE
Query active timer for context and python3 bytes to string issue

### ISSUE THREAD

**Issue by thomasknowles** [jruizgit/rules#80]
Hello Jesus,

2 issues here:

1)

I have taken a look through the source code and I am not sure if this is possible. I would like to be able to query whether there is an active "timer" running in a context. In the code below I have a rule which checks if the result is equal to failed, then it creates a context based increment counter, then below if the counter is equal to 3 perform an action.

However, I would like to evaluate whether the counter is equal to 3 AND there is a current timer running against this context. So something like this:

@when_all(all(s.failed_counter == 3, c.get_timer("failed_auth_time", c.s.sid))

So if there is a timer present it'll return as true.

```
from durable.lang import *
import datetime

with ruleset('auth'):
    # when first timer or less than 5 timeouts
    @when_all(m.result == "failed")
    def failed(c):
        try:
            c.s.failed_counter += 1
        except:
            c.s.failed_counter = 1
            c.start_timer('failed_auth_timer', 15, c.s.sid)

    @when_all(all(s.failed_counter == 3))
    def failed_threshold(c):
        print("did it work?")
        c.s.failed_counter = 0

    @when_all(timeout('failed_auth_timer'))
    def pulse(c):
        # We'll just let this die.
        print("{0} failed {1} times logging in".format(c.s.sid, c.s.failed_counter))
        print('pulse ->{0}'.format(datetime.datetime.now().strftime('%I:%M:%S%p')))

run_all()
```
I'd send 3 of these events within 15 seconds:

`curl -H "Content-type: application/json" -X POST -d '{"sid":"1", "result": "failed", "username": "thomas.knowles"}'  http://localhost:5000/auth/events`

2)

In python3 the REST API is not happy with the curl command above due to the data being interpreted as bytes as opposed to strings (the way python2 handles it) and requires myself to add ".decode("utf-8")" to the end of the following:

durable/lib/python3.5/site-packages/durable/interface.py

`message = json.loads(request.stream.read())`

So it looks like this:

`message = json.loads(request.stream.read().decode("utf-8") )`

**Comment by jruizgit** [comment]
Thanks for posting the question. I will look into your scenario soon. I will report back on my findings in a couple of days.

**Comment by jruizgit** [comment]
Hi, reporting back on this. Currently there is no efficient way to query if there is a pending timer. However, I think the following example might cover your scenario (detect if there are 3 failures in 15 seconds). Please use version `0.33.102` . This week I fixed a number of bugs in the timers area.

```python
with statechart('auth'):
    with state('start'):
        @to('meter')
        def start(c):
            c.start_timer('FailureTimer', 15)

    with state('meter'):
        @to('fail')
        @when_all(count(3), m.result == 'failed')
        def failure(c):
            print('Three failures')

        @to('success')
        @when_all(timeout('FailureTimer'))
        def exit(c):
            print('Succeeded')

    state('fail')
    state('success')

run_all()
```

**Comment by thomasknowles** [comment]
Thanks I'll check this out
