### ISSUE TITLE
Facts behaviour 

### ISSUE THREAD

**Issue by ammarwm** [jruizgit/rules#83]
from durable.lang import *

with ruleset('risk'):
    @when_all(c.first << m.t == 'purchase',
              c.second << m.location != c.first.location)
    # the event pair will only be observed once
    def fraud(c):
        print('Fraud detected -> {0}, {1}'.format(c.first.location, c.second.location))
        c.delete()

    @when_start
    def start(host):
        # 'post' submits events, try 'assert' instead and to see differt behavior
        host.assert_fact('risk', {'t': 'purchase', 'location': 'US'});
        host.assert_fact('risk', {'t': 'purchase', 'location': 'CA'});

run_all()

When running the above code for the output is :
Fraud detected -> US, CA
Fraud detected -> CA, US

Could you please explain why I am getting such output ? thank you

**Comment by jruizgit** [comment]
Hi, thanks for posting the question. The reason is because both facts satisfy the first condition `m.t == 'purchase'` and each fact satisfies the second condition `m.location != c.first.location` in relation to the facts which satisfied the first. 

Given that, you might be wondering why post behaves differently: the reason is because an event is an ephemeral fact, as soon as it is scheduled to be dispatched, it is retracted. When using post in the example above, by the time the second pair is calculated the events have already been retracted.

And why is the difference between events and facts important? Retracting events before dispatch reduces the number of combinations to be calculated for dispatch. Thus, processing events is much more efficient (orders of magnitude faster in some cases).

**Comment by ammarwm** [comment]
Thanks for immediate response. Could you please explain the steps of execution for the above code? what exactly is happening ? I am not sure why there are two output statements. We are starting with the first fact, that satisfy (c.first << m.t == 'purchase'),  that fact also will be referenced by c.first. Then the second fact is evaluated against the second part of the antecendent (c.second << m.location != c.first.location). The location of the second fact satisfies that antecendent and there will be action to print Fraud detected -> US, CA. But why the second statement is printed ( Fraud detected -> CA, US ) as well ?

Thank you

**Comment by ammarwm** [comment]
In a related issue, the below code:

from durable.lang import *

with statechart('payslip'):
    with state('input'):
        @to('valid')
        @when_all(c.fact1 << m.required_document_age != None,
                  c.fact2 << m.document_age <= c.fact1.required_document_age)
        def valid(c):
            print ('Valid Payslip')

        @to('invalid')
        @when_all(c.fact1 << m.required_document_age != None,
                  c.fact2 << m.document_age > c.fact1.required_document_age)
        def invalid(c):
            print ('Invalid Payslip')

    state('valid')
    state('invalid')

    @when_start
    def on_start(host):
        host.assert_fact('payslip',{'sid':1,"required_document_age":14})
        host.post('payslip',{'sid':1, "document_age":10})

run_all()

What could be wrong with the above code ? it is producing nothing.

thank you

**Comment by jruizgit** [comment]
Hi, I tried the code above and it actually works well. I get `Valid Payslip` for `{'sid':1, "document_age":10}` and `Invalid Payslip` for `{'sid':1, "document_age":20}`. Would you mind trying a different 'sid' or clearing the redis db (flusdhdb)?

Back to your first questions, this is how the rule works:
1. `{'t': 'purchase', 'location': 'US'}` is asserted 
2. It matches the alpha nodes for `first` and `second` expressions
3. It is stored twice in the beta node that joins `first` and `second` expressions (once for every alpha match)
4. No action is scheduled at this point as first and second don't satisfy the `location` condition
5.  `{'t': 'purchase', 'location': 'CA'}` is asserted
6. It matches the alpha nodes for `first` and `second` expressions
7. It is stored twice in the beta node that joins `first` and `second` expressions 
8. At this point two pairs of facts satisfy the `location` condition
9. The frames corresponding to the two matches are added to the action queue
10. The client picks up the last action from the queue and dispatches it
11. The action is successful (Fraud detected -> US, CA), the action is removed from the queue
12. The client picks up the last action from the queue and dispatches it
13. The action is successful (Fraud detected -> CA, US), the action is removed from the queue

**Comment by ammarwm** [comment]
Thank you so much for your reply. It was really helpful. What is really the difference between stagechart and statechart ?

**Comment by ammarwm** [comment]
Thank you so much it was helpful.
