### ISSUE TITLE
compilation issue on Windows

### ISSUE THREAD

**Issue by michael-yxf** [jruizgit/rules#90]
Tried to build on Windows 7 64bit, the ``pip install durable_rules`` fails with the following error messages:

> Collecting durable_rules
  Using cached durable_rules-0.33.108.tar.gz
Requirement already satisfied: werkzeug in c:\programdata\anaconda2\lib\site-packages (from durable_rules)
Building wheels for collected packages: durable-rules
  Running setup.py bdist_wheel for durable-rules: started
  Running setup.py bdist_wheel for durable-rules: finished with status 'error'
  Complete output from command C:\ProgramData\Anaconda2\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\michael\\.babun\\cygwin\\tmp\\pip-build-cworry\\durable-rules\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d c:\users\michael\.babun\cygwin\tmp\tmpgckp9vpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-2.7
  creating build\lib.win-amd64-2.7\durable
  copying libpy\durable\engine.py -> build\lib.win-amd64-2.7\durable
  copying libpy\durable\interface.py -> build\lib.win-amd64-2.7\durable
  copying libpy\durable\lang.py -> build\lib.win-amd64-2.7\durable
  copying libpy\durable\__init__.py -> build\lib.win-amd64-2.7\durable
  running build_clib
  building 'rules_py' library
  creating build\temp.win-amd64-2.7
  creating build\temp.win-amd64-2.7\deps
  creating build\temp.win-amd64-2.7\deps\Win32_Interop
  creating build\temp.win-amd64-2.7\deps\hiredis_win
  creating build\temp.win-amd64-2.7\src
  creating build\temp.win-amd64-2.7\src\rules
  C:\Users\michael\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG /Tcdeps/Win32_Interop/win32_error.c /Fobuild\temp.win-amd64-2.7\deps/Win32_Interop/win32_error.obj
  win32_error.c
  deps/Win32_Interop/win32_error.c(37) : error C2065: 'EADDRINUSE' : undeclared identifier
  deps/Win32_Interop/win32_error.c(38) : error C2065: 'EADDRINUSE' : undeclared identifier
  deps/Win32_Interop/win32_error.c(39) : error C2065: 'EADDRNOTAVAIL' : undeclared identifier
  deps/Win32_Interop/win32_error.c(40) : error C2065: 'EAFNOSUPPORT' : undeclared identifier
  deps/Win32_Interop/win32_error.c(42) : error C2065: 'EALREADY' : undeclared identifier
  deps/Win32_Interop/win32_error.c(48) : error C2065: 'ECANCELED' : undeclared identifier
  deps/Win32_Interop/win32_error.c(49) : error C2065: 'ECANCELED' : undeclared identifier
  deps/Win32_Interop/win32_error.c(50) : error C2065: 'ECONNABORTED' : undeclared identifier
  deps/Win32_Interop/win32_error.c(51) : error C2065: 'ECONNABORTED' : undeclared identifier
  deps/Win32_Interop/win32_error.c(52) : error C2065: 'ECONNREFUSED' : undeclared identifier
  deps/Win32_Interop/win32_error.c(53) : error C2065: 'ECONNREFUSED' : undeclared identifier
  deps/Win32_Interop/win32_error.c(54) : error C2065: 'ECONNRESET' : undeclared identifier
  deps/Win32_Interop/win32_error.c(55) : error C2065: 'ECONNRESET' : undeclared identifier
  deps/Win32_Interop/win32_error.c(60) : error C2065: 'EHOSTUNREACH' : undeclared identifier
  deps/Win32_Interop/win32_error.c(61) : error C2065: 'EHOSTUNREACH' : undeclared identifier
  deps/Win32_Interop/win32_error.c(85) : error C2065: 'EISCONN' : undeclared identifier
  deps/Win32_Interop/win32_error.c(86) : error C2065: 'ELOOP' : undeclared identifier
  deps/Win32_Interop/win32_error.c(89) : error C2065: 'EMSGSIZE' : undeclared identifier
  deps/Win32_Interop/win32_error.c(91) : error C2065: 'ENETUNREACH' : undeclared identifier
  deps/Win32_Interop/win32_error.c(92) : error C2065: 'ENETUNREACH' : undeclared identifier
  deps/Win32_Interop/win32_error.c(93) : error C2065: 'ENOBUFS' : undeclared identifier
  deps/Win32_Interop/win32_error.c(110) : error C2065: 'ENOTCONN' : undeclared identifier
  deps/Win32_Interop/win32_error.c(111) : error C2065: 'ENOTCONN' : undeclared identifier
  deps/Win32_Interop/win32_error.c(113) : error C2065: 'ENOTSOCK' : undeclared identifier
  deps/Win32_Interop/win32_error.c(114) : error C2065: 'ENOTSUP' : undeclared identifier
  deps/Win32_Interop/win32_error.c(122) : error C2065: 'EPROTONOSUPPORT' : undeclared identifier
  deps/Win32_Interop/win32_error.c(124) : error C2065: 'ETIMEDOUT' : undeclared identifier
  deps/Win32_Interop/win32_error.c(125) : error C2065: 'ETIMEDOUT' : undeclared identifier
  deps/Win32_Interop/win32_error.c(154) : warning C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
  error: command 'C:\\Users\\michael\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2

  ----------------------------------------
  Failed building wheel for durable-rules

Have tried with Python 2.7 and 3.5: 
```bash
python -V
Python 2.7.13 :: Anaconda custom (64-bit)
```

Any ideas how to work around it? Thanks.

**Comment by jruizgit** [comment]
Hi, thanks for posting the question. Windows is a little complicated. Only python 3.5 is supported. You need to install VC++ 14 (see https://wiki.python.org/moin/WindowsCompilers). Using a C++ terminal (the shortcuts are installed by the VC++ installer), you can do pip install durable_rules. Please make sure you use the 64 bit terminal if you installed Python 64 bit build.

**Comment by michael-yxf** [comment]
Thanks for the information. I've got it successfully compiled and installed on Windows following the instructions.
